In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("SmartPrice AI 🚀")
print("Pandas:", pd.__version__)

SmartPrice AI 🚀
Pandas: 3.0.6

In [2]:
from pathlib import Path

pasta_dados = Path("../data/raw")

arquivos = list(pasta_dados.glob("*.xlsx"))

print("Arquivos encontrados:")
for arquivo in arquivos:
    print("-", arquivo.name)

Arquivos encontrados:
- GUIAS DE ITBI PAGAS (28012026) XLS.xlsx

In [3]:
arquivo_itbi = arquivos[0]

excel = pd.ExcelFile(arquivo_itbi)

print("Arquivo:", arquivo_itbi.name)
print("\nPlanilhas encontradas:")

for planilha in excel.sheet_names:
    print("-", planilha)

Arquivo: GUIAS DE ITBI PAGAS (28012026) XLS.xlsx

Planilhas encontradas:
- JAN-2025
- FEV-2025
- MAR-2025
- ABR-2025
- MAI-2025
- JUN-2025
- JUL-2025
- AGO-2025
- SET-2025
- OUT-2025
- NOV-2025
- DEZ-2025
- LEGENDA
- EXPLICAÇÕES
- Tabela de USOS
- Tabela de PADRÕES

In [4]:
legenda = pd.read_excel(
    arquivo_itbi,
    sheet_name="LEGENDA",
    header=None
)

legenda.head(30)

    0        1                                                  2
0 NaN      NaN                                                NaN
1 NaN  LEGENDA                                                NaN
2 NaN      NaN                                                NaN
3 NaN      NaN                    Dados extraídos da base do ITBI
4 NaN      NaN    Dados extraídos da base do IPTU (Exercício A...
5 NaN      NaN    Dado calculado (VVR proporcional = Proporção...

In [5]:
explicacoes = pd.read_excel(
    arquivo_itbi,
    sheet_name="EXPLICAÇÕES",
    header=None
)

explicacoes.head(30)

,0,1,2,3,4,5,6,7
0,CAMPO,PREENCHIMENTO NA DTI (Delcaração de Transações...,CONCEITO,TIPO,TAMANHO,DOMÍNIO (Valores válidos),CONDIÇÕES,OBSERVAÇÕES
1,N° do Cadastro (SQL),Declarado pelo contribuinte,Número que individualiza o imóvel no cadastro ...,Numérico,11,{setor: 001 a 310} - {quadra: 001 a 999} - {lo...,Obrigatório,1. Tem dígito de controle (0 à 9)
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2. Não existe o setor 092
3,Nome do Logradouro,Inserido automaticamente pelo sistema a partir...,"Nome do logradouro do endereço do imóvel (rua,...",Alfanumérico,41,Sem restrição,Não é passível de reedição pelo contribuinte,"Os caractéres permitidos são letras, números, ..."
4,Número do Imóvel,Inserido automaticamente pelo sistema a partir...,Numeração do imóvel no seu respectivo logradou...,Numérico,5,{00000 a 99999},Não é passível de reedição pelo contribuinte,NaN
5,Complemento do Imóvel,Inserido automaticamente pelo sistema a partir...,Complemento do endereço do imóvel,Alfanumérico,18,Sem restrição,É passível de reedição pelo contribuinte,"Os caractéres permitidos são letras, números, ..."
6,Bairro,Inserido automaticamente pelo sistema a partir...,Bairro do endereço do imóvel,Alfanumérico,22,Sem restrição,Não é passível de reedição pelo contribuinte,"Os caractéres permitidos são letras, números, ..."
7,Referência,"Não é campo integrante da DTI, mas somente da ...",Referência do endereço do imóvel,Alfanumérico,20,Sem restrição,NaN,"Os caractéres permitidos são letras, números, ..."
8,CEP,Inserido automaticamente pelo sistema a partir...,CEP do logradouro do endereço do imóvel,Numérico,8,{00000000 a 99999999},Não é passível de reedição pelo contribuinte,NaN
9,Natureza da Transação,Declarado pelo contribuinte,Indica o tipo de negócio jurídico por meio do ...,Numérico,2,{1 a 99},Obrigatório,Exs.: 1. Compra e venda; 2. Cessão de direitos...
10,NaN,NaN,NaN,Alfanumérico,150,Sem restrição,NaN,NaN
11,Valor de Transação,Declarado pelo contribuinte,Valor econômico que está sendo dado pela aquis...,Numérico,11,"{0,01 a 999.999.999,99}",Obrigatório,Valor expresso somente em R$
12,Data de Transação,Declarado pelo contribuinte,Data do instrumento particular ou escritura pú...,Numérico,8,{dia: 01 a 31} - {mês: 01 a 12} - {ano: 0100 a...,Obrigatório,O ano 00XX é assumido automaticamente como 19X...
13,Valor Venal de Referência,Buscado pelo sistema a partir do SQL e da Dat...,"Valor divulgado pela Prefeitura, que servirá c...",Numérico,11,"{0,01 a 999.999.999,99}",Obrigatório,Valor expresso somente em R$
14,Proporção Transmitida,Declarado pelo contribuinte,Parte do imóvel (em percentual) que está sendo...,Numérico,5,"{0,00 a 999,99}",Obrigatório,Caso o contribuinte assinale que está sendo tr...
15,Valor Venal de Referência (Proporcional),"Calculado automaticamente pelo sistema, aplica...",Valor que será comparado com o Valor de Transa...,Numérico,11,"{0,01 a 999.999.999,99}",Obrigatório,Valor expresso somente em R$
16,Base de Cálculo adotada,"Calculado automaticamente pelo sistema, que ve...",Base de Cálculo do ITBI,Numérico,11,"{0,01 a 999.999.999,99}",Obrigatório,Valor expresso somente em R$
17,Tipo de Financiamento,Declarado pelo contribuinte,Modalidade de financiamento vinculado à aquisi...,Alfanumérico,160,Sem restrição,Facultativo,Válido somente para a natureza de transação 1....
18,Valor Financiado,Declarado pelo contribuinte,Valor do financiamento concedido pelo banco ou...,Numérico,11,"{0,01 a 999.999.999,99}",Facultativo,Valor expresso somente em R$
19,Cartório de Registro,Declarado pelo contribuinte,Cartório de Registro de Imóvel responsável pel...,Alfanumérico,40,Sem restrição,Obrigatório,NaN
20,Matrícula do Imóvel,Declarado pelo contribuinte,Número da matrícula (ou transcrição) do imóvel...,Numérico,7,{1 a 9999999},Obrigatório,NaN
21,Situação do SQL,"Não é campo integrante da DTI, mas somente da ...",Sinaliza se determinado SQL está ativo ou canc...,Alfanumérico,NaN,Sem restrição,Obrigatório,NaN
22,Área do Terreno (m2),"Não é campo integrante da DTI, mas somente da ...",Informa a área do terreno em m²,Numérico,7,{1 a 5.000.000},Obrigatório,Quando a área total do terreno contiver fração...
23,Testada (m),"Não é campo integrante da DTI, mas somente da ...","Medida, em metros, da frente do imóvel para o ...",Numérico,6,"{em branco} - {0,01 a 9.000,00}",Obrigatório (*),(*) O campo fica em branco no caso de terreno ...
24,Fração ideal,"Não é campo integrante da DTI, mas somente da ...",Percentual atribuído a cada unidade autônoma e...,Numérico,5,"{em branco} - {0,0001 a 1,0000}",Obrigatório,Nos casos em que o imóvel não estiver em condo...
25,Área Construída (m2),"Não é campo integrante da DTI, mas somente da ...",Informa a área construída em m²,Numérico,6,{0 a 951.000},Obrigatório,Não corresponde necessariamente a área ocupada...
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Em caso de condomínio, além da área privativa..."
27,Uso (IPTU),"Não é campo integrante da DTI, mas somente da ...",Código relativo à finalidade preponderante a q...,Numérico,2,Vide Tabela de USOS,Obrigatório,NaN
28,Descrição do uso (IPTU),"Não é campo integrante da DTI, nem tampouco da...",Identifica a finalidade preponderante a que o ...,Alfanumérico,NaN,Vide Tabela de USOS,Obrigatório,Dado extraído mediante correlação com uma tabe...
29,Padrão (IPTU),"Não é campo integrante da DTI, mas somente da ...",Código relativo ao tipo e padrão da construção,Numérico,2,Vide Tabela de PADRÕES,Obrigatório,NaN

In [6]:
amostra_janeiro = pd.read_excel(
    arquivo_itbi,
    sheet_name="JAN-2025",
    nrows=10
)

print("Dimensão da amostra:", amostra_janeiro.shape)
print("\nColunas encontradas:")

for i, coluna in enumerate(amostra_janeiro.columns, start=1):
    print(f"{i:02d} - {coluna}")

Dimensão da amostra: (10, 28)

Colunas encontradas:
01 - N° do Cadastro (SQL)
02 - Nome do Logradouro
03 - Número
04 - Complemento
05 - Bairro
06 - Referência
07 - CEP
08 - Natureza de Transação
09 - Valor de Transação (declarado pelo contribuinte)
10 - Data de Transação
11 - Valor Venal de Referência
12 - Proporção Transmitida (%)
13 - Valor Venal de Referência (proporcional)
14 - Base de Cálculo adotada
15 - Tipo de Financiamento
16 - Valor Financiado
17 - Cartório de Registro
18 - Matrícula do Imóvel
19 - Situação do SQL
20 - Área do Terreno (m2)
21 - Testada (m)
22 - Fração Ideal
23 - Área Construída (m2)
24 - Uso (IPTU)
25 - Descrição do uso (IPTU)
26 - Padrão (IPTU)
27 - Descrição do padrão (IPTU)
28 - ACC (IPTU)

In [7]:
amostra_janeiro.head()

,N° do Cadastro (SQL),Nome do Logradouro,Número,Complemento,Bairro,Referência,CEP,Natureza de Transação,Valor de Transação (declarado pelo contribuinte),Data de Transação,...,Situação do SQL,Área do Terreno (m2),Testada (m),Fração Ideal,Área Construída (m2),Uso (IPTU),Descrição do uso (IPTU),Padrão (IPTU),Descrição do padrão (IPTU),ACC (IPTU)
0,30106900789,AV CARLOS QUEIROZ TELLES,99999,Apto 163 Bloc L,IBIRAPUERA,NaN,5704150,1.Compra e venda,625100.00,2024-12-20,...,Ativo Territorial,8066,8.00,1.0000,0,0,TERRENO,0,TERRENO,NaN
1,17130212951,R DR LUIZ MIGLIANO,1870,APTO 223 TORRE E,COND MONUMENTO SP,NaN,5711001,1.Compra e venda,573915.07,2024-12-20,...,Ativo Territorial,59923,256.24,0.5155,0,0,TERRENO,0,TERRENO,NaN
2,9900500245,R CAP JOSE INACIO DO ROSARIO,133,AP 2015 TORRE B,LAPA,NaN,5038070,1.Compra e venda,288435.00,2024-12-20,...,Ativo Predial,22903,0.00,1.0000,11382,71,ESCOLA,94,"TEMPLO, CLUBE, GINÁSIO OU ESTÁDIOESPORTIVO, MU...",2002.0
3,2601502142,R MARCOS ARRUDA,729,AP 2411 T A,BELENZINHO,NaN,3020000,1.Compra e venda,237000.00,2024-12-20,...,Ativo Predial,13221,137.95,1.0000,33835,71,ESCOLA,44,COMERCIAL VERTICAL,1959.0
4,1904806211,R NEWTON PRADO,767,AP 136B E VG,COND ESTILO,TORRE B,1127000,4.Arrematação (em leilão ou hasta pública),251576.26,2024-12-18,...,Ativo Predial,5199,55.50,0.0048,95,20,APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL),22,RESIDENCIAL VERTICAL,2014.0

In [8]:
df_jan = pd.read_excel(
    arquivo_itbi,
    sheet_name="JAN-2025"
)

print(f"Linhas: {df_jan.shape[0]:,}")
print(f"Colunas: {df_jan.shape[1]}")

Linhas: 14,456
Colunas: 28

In [9]:
df_jan.info()

<class 'pandas.DataFrame'>
RangeIndex: 14456 entries, 0 to 14455
Data columns (total 28 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   N° do Cadastro (SQL)                              14456 non-null  int64
 1   Nome do Logradouro                                14456 non-null  str
 2   Número                                            14456 non-null  int64
 3   Complemento                                       12924 non-null  object
 4   Bairro                                            8672 non-null   object
 5   Referência                                        6011 non-null   object
 6   CEP                                               14456 non-null  int64
 7   Natureza de Transação                             14456 non-null  str
 8   Valor de Transação (declarado pelo contribuinte)  14456 non-null  float64
 9   Data de Transação                                 14456 non-null  datetime64[us]
 10  Valor Venal de Referência                         14456 non-null  float64
 11  Proporção Transmitida (%)                         14456 non-null  float64
 12  Valor Venal de Referência (proporcional)          14456 non-null  float64
 13  Base de Cálculo adotada                           14456 non-null  float64
 14  Tipo de Financiamento                             6723 non-null   str
 15  Valor Financiado                                  14456 non-null  float64
 16  Cartório de Registro                              14456 non-null  str
 17  Matrícula do Imóvel                               14456 non-null  int64
 18  Situação do SQL                                   14456 non-null  str
 19  Área do Terreno (m2)                              14456 non-null  int64
 20  Testada (m)                                       14456 non-null  float64
 21  Fração Ideal                                      14456 non-null  float64
 22  Área Construída (m2)                              14456 non-null  int64
 23  Uso (IPTU)                                        14456 non-null  int64
 24  Descrição do uso (IPTU)                           14456 non-null  str
 25  Padrão (IPTU)                                     14456 non-null  int64
 26  Descrição do padrão (IPTU)                        14456 non-null  str
 27  ACC (IPTU)                                        11893 non-null  float64
dtypes: datetime64[us](1), float64(9), int64(8), object(3), str(7)
memory usage: 3.1+ MB

In [10]:
df_jan["Descrição do uso (IPTU)"].value_counts().head(15)

Descrição do uso (IPTU)
APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL)                                                                 5232
TERRENO                                                                                                        2563
RESIDÊNCIA                                                                                                     1989
GARAGEM (UNIDADE AUTÔNOMA) EM EDIFÍCIO EM CONDOMÍNIO DE USO EXCLUSIVAMENTE RESIDENCIAL (EXIGE FRAÇÃO IDEAL)     701
INDÚSTRIA                                                                                                       481
LOJA                                                                                                            453
OUTRAS EDIFICAÇÕES DO TIPO, COM UTILIZAÇÃO MÚLTIPLA                                                             412
RESIDÊNCIA COLETIVA, EXCLUSIVE CORTIÇO (MAIS DE UMA RESIDÊNCIA NO LOTE)                                         374
ESCRITÓRIO/CONSULTÓRIO EM CONDOMÍNIO (UNID AUTÔNOMA EXIGE FRAÇÃO IDEAL)                                         370
HOTEL, PENSÃO OU HOSPEDARIA                                                                                     306
ESCOLA                                                                                                          236
PRÉDIO DE ESCRITÓRIO OU CONSULTÓRIO, NÃO EM CONDOMÍNIO, COM OU SEM LOJAS                                        231
ARMAZÉNS GERAIS E DEPÓSITOS                                                                                     199
FLAT DE USO COMERCIAL (SEMELHANTE À HOTEL)                                                                      170
RESIDÊNCIA E OUTRO USO (PREDOMINÂNCIA RESIDENCIAL)                                                              138
Name: count, dtype: int64

In [11]:
planilhas_2025 = [
    nome for nome in excel.sheet_names
    if nome.endswith("-2025")
]

print(planilhas_2025)

['JAN-2025', 'FEV-2025', 'MAR-2025', 'ABR-2025', 'MAI-2025', 'JUN-2025', 'JUL-2025', 'AGO-2025', 'SET-2025', 'OUT-2025', 'NOV-2025', 'DEZ-2025']

In [12]:
dados_mensais = []

for planilha in planilhas_2025:
    print(f"Carregando {planilha}...")

    df_mes = pd.read_excel(
        arquivo_itbi,
        sheet_name=planilha
    )

    df_mes["Mes_Arquivo"] = planilha
    dados_mensais.append(df_mes)

df_2025 = pd.concat(
    dados_mensais,
    ignore_index=True
)

print("\nConsolidação concluída 🚀")
print(f"Linhas: {df_2025.shape[0]:,}")
print(f"Colunas: {df_2025.shape[1]}")

Carregando JAN-2025...

Carregando FEV-2025...

Carregando MAR-2025...

Carregando ABR-2025...

Carregando MAI-2025...

Carregando JUN-2025...

Carregando JUL-2025...

Carregando AGO-2025...

Carregando SET-2025...

Carregando OUT-2025...

Carregando NOV-2025...

Carregando DEZ-2025...

Consolidação concluída 🚀
Linhas: 230,525
Colunas: 30

In [13]:
df_2025["Descrição do uso (IPTU)"].value_counts().head(15)

Descrição do uso (IPTU)
APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL)                                                                 79108
TERRENO                                                                                                        39808
RESIDÊNCIA                                                                                                     31057
GARAGEM (UNIDADE AUTÔNOMA) EM EDIFÍCIO EM CONDOMÍNIO DE USO EXCLUSIVAMENTE RESIDENCIAL (EXIGE FRAÇÃO IDEAL)    10212
INDÚSTRIA                                                                                                       8247
OUTRAS EDIFICAÇÕES DO TIPO, COM UTILIZAÇÃO MÚLTIPLA                                                             7878
LOJA                                                                                                            7166
ESCRITÓRIO/CONSULTÓRIO EM CONDOMÍNIO (UNID AUTÔNOMA EXIGE FRAÇÃO IDEAL)                                         6704
RESIDÊNCIA COLETIVA, EXCLUSIVE CORTIÇO (MAIS DE UMA RESIDÊNCIA NO LOTE)                                         6097
ARMAZÉNS GERAIS E DEPÓSITOS                                                                                     5296
PRÉDIO DE ESCRITÓRIO OU CONSULTÓRIO, NÃO EM CONDOMÍNIO, COM OU SEM LOJAS                                        4755
ESCOLA                                                                                                          4087
FLAT DE USO COMERCIAL (SEMELHANTE À HOTEL)                                                                      2960
RESIDÊNCIA E OUTRO USO (PREDOMINÂNCIA RESIDENCIAL)                                                              2056
LOJA E RESIDÊNCIA (PREDOMINÂNCIA COMERCIAL)                                                                     1939
Name: count, dtype: int64

In [14]:
data_transacao_tmp = pd.to_datetime(
    df_2025["Data de Transação"],
    errors="coerce",
    dayfirst=True
)

print("Período das transações (conversão temporária):")
print("Inicial:", data_transacao_tmp.min())
print("Final:", data_transacao_tmp.max())

print("\nDatas inválidas na conversão temporária:")
print(data_transacao_tmp.isna().sum())

print("\nTotal de registros:", f"{len(df_2025):,}")

Período das transações (conversão temporária):
Inicial: 1995-01-01 00:00:00
Final: 2026-01-06 00:00:00

Datas inválidas na conversão temporária:
7

Total de registros: 230,525

In [15]:
print("Tipo da coluna:")
print(df_2025["Data de Transação"].dtype)

print("\nTipos de valores encontrados:")
print(
    df_2025["Data de Transação"]
    .map(type)
    .value_counts()
)

Tipo da coluna:
object

Tipos de valores encontrados:
Data de Transação
<class 'pandas.Timestamp'>     130716
<class 'datetime.datetime'>     99802
<class 'str'>                       7
Name: count, dtype: int64

In [16]:
df_2025["Data de Transação"] = pd.to_datetime(
    df_2025["Data de Transação"],
    errors="coerce",
    dayfirst=True
)

print("Novo tipo:")
print(df_2025["Data de Transação"].dtype)

print("\nDatas inválidas após conversão:")
print(df_2025["Data de Transação"].isna().sum())

Novo tipo:
datetime64[us]

Datas inválidas após conversão:
7

In [17]:
print("Período das transações:")
print("Inicial:", df_2025["Data de Transação"].min())
print("Final:", df_2025["Data de Transação"].max())

print("\nTotal de registros:")
print(f"{len(df_2025):,}")

Período das transações:
Inicial: 1995-01-01 00:00:00
Final: 2026-01-06 00:00:00

Total de registros:
230,525

In [18]:
tipo_apartamento = "APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL)"

df_apartamentos = df_2025[
    df_2025["Descrição do uso (IPTU)"] == tipo_apartamento
].copy()

print("Apartamentos encontrados:")
print(f"{len(df_apartamentos):,}")

print(
    f"\nPercentual da base: "
    f"{len(df_apartamentos) / len(df_2025) * 100:.2f}%"
)

Apartamentos encontrados:
79,108

Percentual da base: 34.32%

In [19]:
df_apartamentos[
    [
        "Bairro",
        "CEP",
        "Valor de Transação (declarado pelo contribuinte)",
        "Área Construída (m2)",
        "Padrão (IPTU)",
        "Descrição do padrão (IPTU)",
        "Data de Transação"
    ]
].head(10)

,Bairro,CEP,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Padrão (IPTU),Descrição do padrão (IPTU),Data de Transação
4,COND ESTILO,1127000.0,251576.26,95,22,RESIDENCIAL VERTICAL,2024-12-18
22,VL PRUDENTE,3147000.0,252363.14,116,22,RESIDENCIAL VERTICAL,2024-12-23
28,BLOCO B,4305000.0,612708.6,117,22,RESIDENCIAL VERTICAL,2024-12-23
109,TORRE 1,5634001.0,1500000.0,218,23,RESIDENCIAL VERTICAL,2024-12-30
137,CIDADE DUTRA,4808900.0,950000.0,253,23,RESIDENCIAL VERTICAL,2024-12-27
143,HORTO DO YPE,5782370.0,250000.0,52,22,RESIDENCIAL VERTICAL,2024-12-27
145,BUTANTA,5573900.0,490000.0,117,22,RESIDENCIAL VERTICAL,2024-12-20
146,BL II CONDOMINIO,4777001.0,420000.0,110,22,RESIDENCIAL VERTICAL,2024-12-20
147,EDIF LAGOON BAY,4562030.0,5300000.0,383,24,RESIDENCIAL VERTICAL,2024-12-20
157,NaN,1423001.0,40000.0,52,22,RESIDENCIAL VERTICAL,2024-12-23

In [20]:
col_preco = "Valor de Transação (declarado pelo contribuinte)"
col_area = "Área Construída (m2)"

df_apartamentos[[col_preco, col_area]].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

       Área Construída (m2)
count          79108.000000
mean             127.059299
std              104.728826
min                6.000000
1%                32.000000
5%                39.000000
25%               69.000000
50%              100.000000
75%              147.000000
95%              311.000000
99%              554.000000
max             2757.000000

In [21]:
print("Apartamentos com área <= 0:")
print((df_apartamentos[col_area] <= 0).sum())

print("\nApartamentos com valor <= 0:")
print((df_apartamentos[col_preco] <= 0).sum())

print("\nValores ausentes:")
print(
    df_apartamentos[
        [col_preco, col_area, "CEP", "Bairro", "Padrão (IPTU)"]
    ].isna().sum()
)

Apartamentos com área <= 0:
0

Apartamentos com valor <= 0:
0

Valores ausentes:
Valor de Transação (declarado pelo contribuinte)        0
Área Construída (m2)                                    0
CEP                                                     0
Bairro                                              28901
Padrão (IPTU)                                           0
dtype: int64

In [22]:
df_apartamentos.assign(
    _preco_numerico=pd.to_numeric(
        df_apartamentos[col_preco],
        errors="coerce"
    )
).nlargest(
    10,
    "_preco_numerico"
)[
    [
        col_preco,
        col_area,
        "CEP",
        "Bairro",
        "Descrição do padrão (IPTU)",
        "Data de Transação"
    ]
]

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),CEP,Bairro,Descrição do padrão (IPTU),Data de Transação
209680,70000000.0,1231,4538083.0,NaN,RESIDENCIAL VERTICAL,2025-12-05
27913,64765000.0,1451,1454030.0,NaN,RESIDENCIAL VERTICAL,2025-02-25
31733,59700000.0,1433,1454030.0,NaN,RESIDENCIAL VERTICAL,2025-03-07
199535,57500000,1491,1454010.0,E 2DP,RESIDENCIAL VERTICAL,2025-11-18
180199,50000000,1490,4542012.0,TRIPLEX,RESIDENCIAL VERTICAL,2025-10-20
99826,47000000,1491,1454010.0,E 2DP,RESIDENCIAL VERTICAL,2025-06-17
168091,40000000,1088,1454030.0,JARDIM EUROPA,RESIDENCIAL VERTICAL,2025-10-07
187606,39688081.57,1379,4533030.0,NaN,RESIDENCIAL VERTICAL,2025-10-30
187538,38500000,1379,4533030.0,NaN,RESIDENCIAL VERTICAL,2025-10-30
72291,37000000.0,957,4542001.0,JD PAULISTA,RESIDENCIAL VERTICAL,2025-05-15

In [23]:
print("Tipo da coluna de preço:")
print(df_apartamentos[col_preco].dtype)

print("\nTipos de valores encontrados:")
print(
    df_apartamentos[col_preco]
    .map(type)
    .value_counts()
)

Tipo da coluna de preço:
object

Tipos de valores encontrados:
Valor de Transação (declarado pelo contribuinte)
<class 'float'>    51542
<class 'int'>      27566
Name: count, dtype: int64

In [24]:
valores_nao_numericos = pd.to_numeric(
    df_apartamentos[col_preco],
    errors="coerce"
).isna() & df_apartamentos[col_preco].notna()

print("Valores não numéricos encontrados:")
print(valores_nao_numericos.sum())

df_apartamentos.loc[
    valores_nao_numericos,
    [col_preco, "Mes_Arquivo"]
].head(20)

Valores não numéricos encontrados:
0

Empty DataFrame
Columns: [Valor de Transação (declarado pelo contribuinte), Mes_Arquivo]
Index: []

In [25]:
df_apartamentos[col_preco] = pd.to_numeric(
    df_apartamentos[col_preco]
)

print("Novo tipo da coluna:")
print(df_apartamentos[col_preco].dtype)

Novo tipo da coluna:
float64

In [26]:
print("Tipo da coluna de área:")
print(df_apartamentos[col_area].dtype)

print("\nTipos de valores encontrados:")
print(
    df_apartamentos[col_area]
    .map(type)
    .value_counts()
)

Tipo da coluna de área:
int64

Tipos de valores encontrados:
Área Construída (m2)
<class 'int'>    79108
Name: count, dtype: int64

In [27]:
df_apartamentos[[col_preco, col_area]].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

       Valor de Transação (declarado pelo contribuinte)  Área Construída (m2)
count                                      7.910800e+04          79108.000000
mean                                       6.874400e+05            127.059299
std                                        1.279298e+06            104.728826
min                                        1.000000e-02              6.000000
1%                                         2.773667e+03             32.000000
5%                                         8.018722e+04             39.000000
25%                                        2.570000e+05             69.000000
50%                                        4.000000e+05            100.000000
75%                                        7.250000e+05            147.000000
95%                                        1.975000e+06            311.000000
99%                                        4.800000e+06            554.000000
max                                        7.000000e+07           2757.000000

In [28]:
print("Apartamentos com área <= 0:")
print((df_apartamentos[col_area] <= 0).sum())

print("\nApartamentos com valor <= 0:")
print((df_apartamentos[col_preco] <= 0).sum())

Apartamentos com área <= 0:
0

Apartamentos com valor <= 0:
0

In [29]:
col_proporcao = "Proporção Transmitida (%)"

df_apartamentos.nsmallest(
    20,
    col_preco
)[
    [
        col_preco,
        col_proporcao,
        col_area,
        "Natureza de Transação",
        "CEP",
        "Bairro",
        "Data de Transação"
    ]
]

,Valor de Transação (declarado pelo contribuinte),Proporção Transmitida (%),Área Construída (m2),Natureza de Transação,CEP,Bairro,Data de Transação
5862,0.01,100.0,63,35.Demais transações de direitos de compromiss...,4324110.0,CJ HAB JABAQUARA,2025-01-14
9457,0.01,100.0,108,1.Compra e venda,3358020.0,VILA FORMOSA,2025-01-24
10018,0.01,100.0,47,1.Compra e venda,8465000.0,C H PRESID JUSCELINO,2025-01-22
10134,0.01,100.0,74,1.Compra e venda,1525901.0,NaN,2025-01-23
17293,0.01,100.0,97,1.Compra e venda,4253000.0,IPIRANGA,2025-02-05
17321,0.01,100.0,111,1.Compra e venda,3345900.0,VL STA CLARA,2025-02-08
18703,0.01,100.0,110,1.Compra e venda,3694900.0,A E CARVALHO,2025-02-10
20712,0.01,100.0,59,1.Compra e venda,3590100.0,CONJ PE M DA NOBREGA,2025-02-11
24596,0.01,100.0,162,1.Compra e venda,2518000.0,ED PORTO FRADE,2025-02-21
24742,0.01,100.0,63,1.Compra e venda,3688010.0,CIDADE A E CARVALHO,2025-02-18
24818,0.01,100.0,162,1.Compra e venda,2518000.0,NaN,2025-02-21
25471,0.01,100.0,63,1.Compra e venda,2611900.0,BLOCO 9,2025-02-19
26505,0.01,100.0,94,1.Compra e venda,3136900.0,VILA PRUDENTE,2025-02-27
26828,0.01,100.0,73,1.Compra e venda,8225271.0,BLOCO 4A,2025-02-21
27112,0.01,100.0,92,1.Compra e venda,2422120.0,MANDAQUI,2025-02-21
28120,0.01,100.0,63,1.Compra e venda,3688010.0,CIDADE A E CARVALHO,2025-02-25
28259,0.01,100.0,112,1.Compra e venda,5847500.0,NaN,2025-02-25
28900,0.01,100.0,109,1.Compra e venda,3059050.0,BELENZINHO,2025-03-02
29249,0.01,100.0,67,1.Compra e venda,3694000.0,CJ HAB DAS PEROLAS,2025-02-26
29306,0.01,100.0,49,1.Compra e venda,8475170.0,STA ETELVINA VII,2025-02-25

In [30]:
df_apartamentos.nlargest(
    20,
    col_preco
)[
    [
        col_preco,
        col_proporcao,
        col_area,
        "Natureza de Transação",
        "CEP",
        "Bairro",
        "Data de Transação"
    ]
]

,Valor de Transação (declarado pelo contribuinte),Proporção Transmitida (%),Área Construída (m2),Natureza de Transação,CEP,Bairro,Data de Transação
209680,70000000.00,100.0,1231,1.Compra e venda,4538083.0,NaN,2025-12-05
27913,64765000.00,100.0,1451,1.Compra e venda,1454030.0,NaN,2025-02-25
31733,59700000.00,100.0,1433,1.Compra e venda,1454030.0,NaN,2025-03-07
199535,57500000.00,100.0,1491,1.Compra e venda,1454010.0,E 2DP,2025-11-18
180199,50000000.00,100.0,1490,1.Compra e venda,4542012.0,TRIPLEX,2025-10-20
99826,47000000.00,100.0,1491,1.Compra e venda,1454010.0,E 2DP,2025-06-17
168091,40000000.00,100.0,1088,1.Compra e venda,1454030.0,JARDIM EUROPA,2025-10-07
187606,39688081.57,100.0,1379,1.Compra e venda,4533030.0,NaN,2025-10-30
187538,38500000.00,100.0,1379,2.Cessão de direitos relativos a compromisso d...,4533030.0,NaN,2025-10-30
72291,37000000.00,100.0,957,1.Compra e venda,4542001.0,JD PAULISTA,2025-05-15
139383,36250000.00,100.0,909,1.Compra e venda,4533050.0,ITAIM BIBI,2025-08-20
101739,35000000.00,100.0,1088,1.Compra e venda,1454030.0,NaN,2025-06-26
175047,34500000.00,100.0,1189,1.Compra e venda,1454020.0,8 VGS E 1 DEP,2025-10-14
12049,32500000.00,100.0,1007,1.Compra e venda,1454030.0,JD AMERICA,2025-01-31
137545,32000000.00,100.0,1103,1.Compra e venda,5676900.0,ED JABUTICABEIRAS T6,2025-08-15
111259,31500000.00,100.0,1217,1.Compra e venda,4542012.0,DUPLEX COBERTURA,2025-07-12
197504,31000000.00,100.0,1134,1.Compra e venda,4510010.0,NaN,2025-11-20
37655,30000000.00,100.0,1134,1.Compra e venda,4510010.0,NaN,2025-03-11
222547,30000000.00,100.0,759,1.Compra e venda,4533030.0,NaN,2025-12-24
73328,29728189.27,100.0,1350,1.Compra e venda,4542011.0,NaN,2025-05-13

In [31]:
df_apartamentos["Natureza de Transação"].value_counts().head(20)

Natureza de Transação
1.Compra e venda                                                          68486
17.Resolução da alienação fiduciária por inadimplemento                    2481
20.Realização ou integralização de capital                                 2114
12.Dação em pagamento por escritura pública                                2097
4.Arrematação (em leilão ou hasta pública)                                  947
15.Permuta por escritura pública                                            556
2.Cessão de direitos relativos a compromisso de compra e venda              491
26.Cessão de direitos sobre o imóvel com alienação fiduciária               361
29.Excesso de meação na partilha (separação / divórcio)                     333
5.Adjudicação compulsória                                                   194
3.Adjudicação (vinculada a processo de execução ou cobrança de dívida)      176
23.Cisão total ou parcial                                                   167
40.Excesso na integralização de capital                                     163
21.Incorporação                                                             103
8.Cessão de direitos hereditários (ou sucessórios)                           92
34.Demais sentenças judiciais                                                81
33.Demais atos onerosos translativos                                         75
30.Excesso de meação na partilha (dissolução da união estável)               46
28.Excesso de meação ou quinhão na partilha (sucessão causa mortis)          31
25.Desincorporação do bem imóvel pertencente à pessoa jurídica               29
Name: count, dtype: int64

In [32]:
# ============================================================
# FILTRO DA BASE: APARTAMENTOS
# ============================================================

tipo_apartamento = "APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL)"

df_apartamentos = df_2025[
    df_2025["Descrição do uso (IPTU)"] == tipo_apartamento
].copy()

print("Apartamentos encontrados:")
print(f"{len(df_apartamentos):,}")

print(
    "\nPercentual da base: "
    f"{len(df_apartamentos) / len(df_2025) * 100:.2f}%"
)

Apartamentos encontrados:
79,108

Percentual da base: 34.32%

In [33]:
# Colunas principais da análise

col_preco = "Valor de Transação (declarado pelo contribuinte)"
col_area = "Área Construída (m2)"
col_proporcao = "Proporção Transmitida (%)"

print("Colunas definidas:")
print("Preço:", col_preco)
print("Área:", col_area)
print("Proporção:", col_proporcao)

Colunas definidas:
Preço: Valor de Transação (declarado pelo contribuinte)
Área: Área Construída (m2)
Proporção: Proporção Transmitida (%)

In [34]:
# Garantir tipos numéricos

df_apartamentos[col_preco] = pd.to_numeric(
    df_apartamentos[col_preco],
    errors="coerce"
)

df_apartamentos[col_area] = pd.to_numeric(
    df_apartamentos[col_area],
    errors="coerce"
)

df_apartamentos[col_proporcao] = pd.to_numeric(
    df_apartamentos[col_proporcao],
    errors="coerce"
)

print(df_apartamentos[
    [col_preco, col_area, col_proporcao]
].dtypes)

Valor de Transação (declarado pelo contribuinte)    float64
Área Construída (m2)                                  int64
Proporção Transmitida (%)                           float64
dtype: object

In [35]:
# ============================================================
# BASE V1 — COMPRAS E VENDAS INTEGRAIS
# ============================================================

df_v1 = df_apartamentos[
    (df_apartamentos["Natureza de Transação"] == "1.Compra e venda") &
    (df_apartamentos[col_proporcao] == 100)
].copy()

print("Base original de apartamentos:")
print(f"{len(df_apartamentos):,}")

print("\nBase V1:")
print(f"{len(df_v1):,}")

print(
    "\nPercentual preservado: "
    f"{len(df_v1) / len(df_apartamentos) * 100:.2f}%"
)

Base original de apartamentos:

79,108

Base V1:
64,951

Percentual preservado: 82.10%

In [36]:
# ============================================================
# ANÁLISE ESTATÍSTICA DA BASE V1
# ============================================================

df_v1[[col_preco, col_area]].describe(
    percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
)

       Valor de Transação (declarado pelo contribuinte)  Área Construída (m2)
count                                      6.495100e+04          64951.000000
mean                                       7.427646e+05            126.429185
std                                        1.343524e+06             97.603593
min                                        1.000000e-02              6.000000
1%                                         2.900510e+03             32.000000
5%                                         1.305040e+05             39.000000
10%                                        2.010489e+05             47.000000
25%                                        2.850000e+05             71.000000
50%                                        4.400000e+05            101.000000
75%                                        7.805735e+05            147.000000
90%                                        1.425000e+06            229.000000
95%                                        2.085241e+06            303.000000
99%                                        5.100000e+06            522.000000
max                                        7.000000e+07           2023.000000

In [37]:
# ============================================================
# PREÇO POR METRO QUADRADO
# ============================================================

df_v1 = df_v1[
    (df_v1[col_preco] > 0) &
    (df_v1[col_area] > 0)
].copy()

df_v1["Preco_m2"] = (
    df_v1[col_preco] / df_v1[col_area]
)

df_v1[
    [col_preco, col_area, "Preco_m2"]
].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
)

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2
count,6.495100e+04,64951.000000,64951.000000
mean,7.427646e+05,126.429185,5363.963493
std,1.343524e+06,97.603593,3075.495867
min,1.000000e-02,6.000000,0.000022
1%,2.900510e+03,32.000000,28.717921
5%,1.305040e+05,39.000000,1812.917731
25%,2.850000e+05,71.000000,3495.145631
50%,4.400000e+05,101.000000,4850.000000
75%,7.805735e+05,147.000000,6600.000000
95%,2.085241e+06,303.000000,10384.615385
99%,5.100000e+06,522.000000,15771.449171
max,7.000000e+07,2023.000000,56864.337937

In [38]:
# ============================================================
# INVESTIGAÇÃO DOS MENORES PREÇOS POR M²
# ============================================================

colunas_investigacao = [
    col_preco,
    col_area,
    "Preco_m2",
    "Natureza de Transação",
    col_proporcao,
    "CEP",
    "Bairro",
    "Descrição do padrão (IPTU)",
    "Data de Transação"
]

df_v1.nsmallest(
    30,
    "Preco_m2"
)[colunas_investigacao]

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,Natureza de Transação,Proporção Transmitida (%),CEP,Bairro,Descrição do padrão (IPTU),Data de Transação
107197,0.01,454,0.000022,1.Compra e venda,100.0,1422003.0,DEP. 02 - 3 SS.,RESIDENCIAL VERTICAL,2025-07-07
192669,0.01,401,0.000025,1.Compra e venda,100.0,5713420.0,"E VGS 8,16,17 E D8",RESIDENCIAL VERTICAL,2025-11-10
103604,0.01,385,0.000026,1.Compra e venda,100.0,3113010.0,NaN,RESIDENCIAL VERTICAL,2025-06-27
223791,0.01,318,0.000031,1.Compra e venda,100.0,3511010.0,E 3 VG VL MATILDE,RESIDENCIAL VERTICAL,2025-12-18
217455,0.01,239,0.000042,1.Compra e venda,100.0,1333904.0,E VAGA,RESIDENCIAL VERTICAL,2025-12-16
141421,0.01,214,0.000047,1.Compra e venda,100.0,4080919.0,NaN,RESIDENCIAL VERTICAL,2025-08-25
93629,0.01,188,0.000053,1.Compra e venda,100.0,5416010.0,NaN,RESIDENCIAL VERTICAL,2025-06-09
36779,0.01,186,0.000054,1.Compra e venda,100.0,5639100.0,BLOCO B,RESIDENCIAL VERTICAL,2025-03-18
176010,0.01,180,0.000056,1.Compra e venda,100.0,5406100.0,PINHEIROS,RESIDENCIAL VERTICAL,2025-10-20
50265,0.01,178,0.000056,1.Compra e venda,100.0,5019000.0,PERDIZES,RESIDENCIAL VERTICAL,2025-04-04
156158,0.01,178,0.000056,1.Compra e venda,100.0,5019000.0,PERDIZES,RESIDENCIAL VERTICAL,2025-09-12
111190,0.01,165,0.000061,1.Compra e venda,100.0,2518000.0,NaN,RESIDENCIAL VERTICAL,2025-07-08
194358,0.01,164,0.000061,1.Compra e venda,100.0,2925160.0,NaN,RESIDENCIAL VERTICAL,2025-11-07
24596,0.01,162,0.000062,1.Compra e venda,100.0,2518000.0,ED PORTO FRADE,RESIDENCIAL VERTICAL,2025-02-21
24818,0.01,162,0.000062,1.Compra e venda,100.0,2518000.0,NaN,RESIDENCIAL VERTICAL,2025-02-21
128904,0.01,146,0.000068,1.Compra e venda,100.0,4674901.0,PORTAL DO BROOKLIN,RESIDENCIAL VERTICAL,2025-08-07
178355,0.01,139,0.000072,1.Compra e venda,100.0,3373000.0,NaN,RESIDENCIAL VERTICAL,2025-10-23
228623,0.01,133,0.000075,1.Compra e venda,100.0,3411120.0,TATUAPE,RESIDENCIAL VERTICAL,2025-12-26
143742,0.01,132,0.000076,1.Compra e venda,100.0,3132090.0,BLOCO 3,RESIDENCIAL VERTICAL,2025-08-26
176761,0.01,131,0.000076,1.Compra e venda,100.0,4291000.0,BL 2 SAUDE,RESIDENCIAL VERTICAL,2025-10-14
34062,0.01,128,0.000078,1.Compra e venda,100.0,4291000.0,JD. DA SAUDE,RESIDENCIAL VERTICAL,2025-03-10
36797,0.01,125,0.000080,1.Compra e venda,100.0,2179020.0,COND JARDIM NOVO MUNDO,RESIDENCIAL VERTICAL,2025-03-20
161271,0.01,125,0.000080,1.Compra e venda,100.0,4514906.0,UBERABINHA,RESIDENCIAL VERTICAL,2025-09-22
59098,0.01,124,0.000081,1.Compra e venda,100.0,2344040.0,BLOCO B,RESIDENCIAL VERTICAL,2025-04-16
134589,0.01,124,0.000081,1.Compra e venda,100.0,5847000.0,NaN,RESIDENCIAL VERTICAL,2025-08-14
115655,0.01,123,0.000081,1.Compra e venda,100.0,2344080.0,BLOCO B,RESIDENCIAL VERTICAL,2025-07-14
144834,0.01,121,0.000083,1.Compra e venda,100.0,8225345.0,BLOCO 3,RESIDENCIAL VERTICAL,2025-08-31
208407,0.01,121,0.000083,1.Compra e venda,100.0,8225270.0,BLOCO 7,RESIDENCIAL VERTICAL,2025-12-02
75368,0.01,119,0.000084,1.Compra e venda,100.0,4292900.0,JD DA SAUDE,RESIDENCIAL VERTICAL,2025-05-14
110344,0.01,119,0.000084,1.Compra e venda,100.0,4292900.0,JD DA SAUDE,RESIDENCIAL VERTICAL,2025-07-03

In [39]:
# ============================================================
# DISTRIBUIÇÃO DOS PREÇOS POR M² MUITO BAIXOS
# ============================================================

limites = [100, 500, 1000, 1500, 2000]

for limite in limites:
    quantidade = (df_v1["Preco_m2"] < limite).sum()
    percentual = quantidade / len(df_v1) * 100

    print(
        f"Abaixo de R$ {limite:,.0f}/m²: "
        f"{quantidade:,} registros "
        f"({percentual:.2f}%)"
    )

Abaixo de R$ 100/m²: 1,074 registros (1.65%)
Abaixo de R$ 500/m²: 1,274 registros (1.96%)
Abaixo de R$ 1,000/m²: 1,861 registros (2.87%)
Abaixo de R$ 1,500/m²: 2,485 registros (3.83%)
Abaixo de R$ 2,000/m²: 3,804 registros (5.86%)

In [40]:
# ============================================================
# INVESTIGAÇÃO DOS VALORES DE TRANSAÇÃO MUITO BAIXOS
# ============================================================

limites_preco = [
    1,
    100,
    1000,
    10000,
    50000,
    100000,
    150000,
    200000
]

for limite in limites_preco:
    quantidade = (df_v1[col_preco] < limite).sum()
    percentual = quantidade / len(df_v1) * 100

    print(
        f"Abaixo de R$ {limite:,.0f}: "
        f"{quantidade:,} registros "
        f"({percentual:.2f}%)"
    )

Abaixo de R$ 1: 144 registros (0.22%)
Abaixo de R$ 100: 222 registros (0.34%)
Abaixo de R$ 1,000: 343 registros (0.53%)
Abaixo de R$ 10,000: 1,070 registros (1.65%)
Abaixo de R$ 50,000: 1,374 registros (2.12%)
Abaixo de R$ 100,000: 2,184 registros (3.36%)
Abaixo de R$ 150,000: 3,781 registros (5.82%)
Abaixo de R$ 200,000: 5,988 registros (9.22%)

In [41]:
# ============================================================
# FAIXAS DOS VALORES BAIXOS
# ============================================================

faixas = [
    0,
    1,
    100,
    1000,
    10000,
    50000,
    100000,
    150000,
    200000,
    300000
]

pd.cut(
    df_v1[col_preco],
    bins=faixas,
    right=False
).value_counts().sort_index()

Valor de Transação (declarado pelo contribuinte)
[0, 1)                144
[1, 100)               78
[100, 1000)           121
[1000, 10000)         727
[10000, 50000)        304
[50000, 100000)       810
[100000, 150000)     1597
[150000, 200000)     2207
[200000, 300000)    11734
Name: count, dtype: int64

In [42]:
# ============================================================
# DISTRIBUIÇÃO DETALHADA DO PREÇO POR M²
# ============================================================

faixas_m2 = [
    0,
    100,
    250,
    500,
    750,
    1000,
    1500,
    2000,
    2500,
    3000,
    4000,
    5000,
    7500,
    10000,
    15000,
    20000,
    30000,
    50000,
    100000
]

distribuicao_m2 = (
    pd.cut(
        df_v1["Preco_m2"],
        bins=faixas_m2,
        right=False
    )
    .value_counts()
    .sort_index()
)

distribuicao_m2

Preco_m2
[0, 100)            1074
[100, 250)            34
[250, 500)           166
[500, 750)           281
[750, 1000)          306
[1000, 1500)         624
[1500, 2000)        1319
[2000, 2500)        2545
[2500, 3000)        4320
[3000, 4000)       11583
[4000, 5000)       11707
[5000, 7500)       20025
[7500, 10000)       7136
[10000, 15000)      3053
[15000, 20000)       479
[20000, 30000)       203
[30000, 50000)        94
[50000, 100000)        2
Name: count, dtype: int64

In [43]:
# ============================================================
# ESTATÍSTICAS DOS IMÓVEIS COM PREÇO/M² MUITO BAIXO
# ============================================================

df_v1.loc[
    df_v1["Preco_m2"] < 2000,
    [col_preco, col_area, "Preco_m2"]
].describe(
    percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
)

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2
count,3.804000e+03,3804.000000,3804.000000
mean,1.312183e+05,127.397476,965.087834
std,1.730919e+05,105.814998,727.652282
min,1.000000e-02,7.000000,0.000022
1%,1.000000e-02,34.000000,0.000089
5%,2.460000e+00,47.000000,0.021934
10%,1.435241e+03,49.000000,12.829137
25%,2.901000e+03,70.000000,49.140067
50%,9.000000e+04,97.000000,1031.869529
75%,1.701079e+05,138.000000,1666.666667
90%,2.999263e+05,238.000000,1875.000000
95%,4.592500e+05,336.000000,1938.775510
99%,8.898500e+05,607.970000,1986.752358
max,1.713775e+06,1038.000000,1999.213846

In [44]:
# ============================================================
# DISTRIBUIÇÃO DETALHADA DO PREÇO POR M²
# ============================================================

faixas_m2 = [
    0,
    100,
    250,
    500,
    750,
    1000,
    1500,
    2000,
    2500,
    3000,
    4000,
    5000,
    7500,
    10000,
    15000,
    20000,
    30000,
    50000,
    100000
]

distribuicao_m2 = (
    pd.cut(
        df_v1["Preco_m2"],
        bins=faixas_m2,
        right=False
    )
    .value_counts()
    .sort_index()
)

distribuicao_m2

Preco_m2
[0, 100)            1074
[100, 250)            34
[250, 500)           166
[500, 750)           281
[750, 1000)          306
[1000, 1500)         624
[1500, 2000)        1319
[2000, 2500)        2545
[2500, 3000)        4320
[3000, 4000)       11583
[4000, 5000)       11707
[5000, 7500)       20025
[7500, 10000)       7136
[10000, 15000)      3053
[15000, 20000)       479
[20000, 30000)       203
[30000, 50000)        94
[50000, 100000)        2
Name: count, dtype: int64

In [45]:
# ============================================================
# ESTATÍSTICAS DOS IMÓVEIS COM PREÇO/M² ABAIXO DE R$ 2.000
# ============================================================

df_preco_m2_baixo = df_v1[
    df_v1["Preco_m2"] < 2000
].copy()

print("Quantidade de registros:")
print(f"{len(df_preco_m2_baixo):,}")

print("\nPercentual da Base V1:")
print(f"{len(df_preco_m2_baixo) / len(df_v1) * 100:.2f}%")

df_preco_m2_baixo[
    [col_preco, col_area, "Preco_m2"]
].describe(
    percentiles=[
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ]
)

Quantidade de registros:
3,804

Percentual da Base V1:
5.86%

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2
count,3.804000e+03,3804.000000,3804.000000
mean,1.312183e+05,127.397476,965.087834
std,1.730919e+05,105.814998,727.652282
min,1.000000e-02,7.000000,0.000022
1%,1.000000e-02,34.000000,0.000089
5%,2.460000e+00,47.000000,0.021934
10%,1.435241e+03,49.000000,12.829137
25%,2.901000e+03,70.000000,49.140067
50%,9.000000e+04,97.000000,1031.869529
75%,1.701079e+05,138.000000,1666.666667
90%,2.999263e+05,238.000000,1875.000000
95%,4.592500e+05,336.000000,1938.775510
99%,8.898500e+05,607.970000,1986.752358
max,1.713775e+06,1038.000000,1999.213846

In [46]:
# ============================================================
# DISTRIBUIÇÃO GEOGRÁFICA DOS PREÇOS/M² BAIXOS
# ============================================================

bairros_preco_baixo = (
    df_preco_m2_baixo
    .groupby("Bairro", dropna=False)
    .agg(
        Quantidade=("Preco_m2", "size"),
        Preco_m2_mediano=("Preco_m2", "median"),
        Valor_mediano=(col_preco, "median"),
        Area_mediana=(col_area, "median")
    )
    .sort_values("Quantidade", ascending=False)
    .head(30)
)

bairros_preco_baixo

,Quantidade,Preco_m2_mediano,Valor_mediano,Area_mediana
Bairro,,,,
NaN,970,926.561534,87000.000,100.0
STA ETELVINA IIA,56,1582.074694,77521.660,49.0
STA ETELVINA VII,56,1498.657653,73434.225,49.0
BLOCO B,47,909.090909,80000.000,88.0
LIBERDADE,46,443.037975,35000.000,79.0
BLOCO A,45,1041.666667,100000.000,97.0
TATUAPE,36,1220.086580,187750.000,145.0
TORRE 1,33,1273.843711,118961.000,105.0
BLOCO 2,31,539.051818,61250.000,91.0
MORUMBI,29,1730.389881,517979.450,380.0
IPIRANGA,28,35.808765,2900.510,89.0
TORRE 2,28,1443.307234,125859.005,102.5
SAUDE,27,36.971754,2900.510,111.0
CJ HAB JOSE BONIFACIO,27,1578.947368,81100.000,57.0
TORRE A,26,1615.369974,162500.005,100.0
STA ETELVINA I VIA,24,1604.784634,73723.000,48.0
CIDADE A E CARVALHO,24,0.000159,0.010,71.0
GUAIANAZES,24,1645.989975,103602.030,73.0
TORRE B,24,862.264265,104272.650,113.0
BUTANTA,23,1617.315429,140000.000,107.0
VILA PRUDENTE,22,994.987890,70000.000,85.0
BLOCO 1,21,1222.515464,97778.110,109.0
SANTANA,21,1067.078838,133685.900,172.0
MOOCA,21,1232.876712,180000.000,151.0
C H PRESID JUSCELINO,20,1503.609422,72890.180,47.0
BLOCO 3,20,1636.363636,117419.285,105.5
PIRITUBA,20,700.277210,55839.175,92.0
ITAQUERA,17,687.858095,72000.000,94.0
BLOCO 4,17,1006.110194,104000.000,107.0
BOM RETIRO,16,809.836066,100000.000,122.0

In [47]:
# ============================================================
# VALORES DE TRANSAÇÃO BAIXOS MAIS FREQUENTES
# ============================================================

df_v1.loc[
    df_v1[col_preco] < 10000,
    col_preco
].value_counts().head(30)

Valor de Transação (declarado pelo contribuinte)
2900.51    440
0.01       129
1.00        42
900.00       9
300.00       6
2000.00      5
1500.00      5
2901.00      5
2500.00      5
450.00       4
600.00       4
2750.00      4
1200.00      3
0.80         3
2000.51      3
150.00       3
2900.52      3
3000.00      3
0.50         3
30.00        2
2400.00      2
6900.00      2
0.08         2
4200.00      2
18.00        2
1000.00      2
3.14         2
1350.00      2
270.00       2
400.00       2
Name: count, dtype: int64

In [48]:
# ============================================================
# EXEMPLOS DAS TRANSAÇÕES ABAIXO DE R$ 10 MIL
# ============================================================

df_v1.loc[
    df_v1[col_preco] < 10000,
    [
        col_preco,
        col_area,
        "Preco_m2",
        "CEP",
        "Bairro",
        "Data de Transação"
    ]
].sort_values(col_preco).head(50)

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,CEP,Bairro,Data de Transação
228623,0.01,133,0.000075,3411120.0,TATUAPE,2025-12-26
226327,0.01,103,0.000097,5845240.0,JD SAO LUIS,2025-11-06
17321,0.01,111,0.000090,3345900.0,VL STA CLARA,2025-02-08
17293,0.01,97,0.000103,4253000.0,IPIRANGA,2025-02-05
18703,0.01,110,0.000091,3694900.0,A E CARVALHO,2025-02-10
110344,0.01,119,0.000084,4292900.0,JD DA SAUDE,2025-07-03
107197,0.01,454,0.000022,1422003.0,DEP. 02 - 3 SS.,2025-07-07
103604,0.01,385,0.000026,3113010.0,NaN,2025-06-27
110757,0.01,73,0.000137,8225310.0,BLOCO 6A,2025-07-11
110870,0.01,102,0.000098,4079903.0,NaN,2025-07-08
103456,0.01,76,0.000132,1529001.0,ACLIMACAO,2025-06-27
114595,0.01,93,0.000108,2345000.0,NaN,2025-07-14
111190,0.01,165,0.000061,2518000.0,NaN,2025-07-08
118708,0.01,62,0.000161,3164902.0,C H BRESSER III,2025-07-18
118039,0.01,90,0.000111,2035011.0,NaN,2025-07-18
115655,0.01,123,0.000081,2344080.0,BLOCO B,2025-07-14
121164,0.01,110,0.000091,3694900.0,A E CARVALHO,2025-07-25
24818,0.01,162,0.000062,2518000.0,NaN,2025-02-21
118061,0.01,110,0.000091,3694900.0,A E CARVALHO,2025-07-24
112467,0.01,84,0.000119,3152130.0,VILA PRUDENTE,2025-07-15
112704,0.01,71,0.000141,3688000.0,CIDADE A E CARVALHO,2025-07-15
20712,0.01,59,0.000169,3590100.0,CONJ PE M DA NOBREGA,2025-02-11
24596,0.01,162,0.000062,2518000.0,ED PORTO FRADE,2025-02-21
24742,0.01,63,0.000159,3688010.0,CIDADE A E CARVALHO,2025-02-18
93629,0.01,188,0.000053,5416010.0,NaN,2025-06-09
120949,0.01,63,0.000159,3688010.0,CIDADE A E CARVALHO,2025-07-29
26505,0.01,94,0.000106,3136900.0,VILA PRUDENTE,2025-02-27
26828,0.01,73,0.000137,8225271.0,BLOCO 4A,2025-02-21
25471,0.01,63,0.000159,2611900.0,BLOCO 9,2025-02-19
125184,0.01,40,0.000250,8470410.0,STA ETELVINA I VIA,2025-07-30
123745,0.01,119,0.000084,4292900.0,JD DA SAUDE,2025-07-28
123474,0.01,113,0.000088,1419002.0,JD. PAULISTA,2025-08-01
34062,0.01,128,0.000078,4291000.0,JD. DA SAUDE,2025-03-10
36779,0.01,186,0.000054,5639100.0,BLOCO B,2025-03-18
131923,0.01,79,0.000127,2422200.0,MANDAQUI,2025-08-14
132029,0.01,61,0.000164,3042000.0,CJ HAB BRAS VII,2025-08-07
29249,0.01,67,0.000149,3694000.0,CJ HAB DAS PEROLAS,2025-02-26
29306,0.01,49,0.000204,8475170.0,STA ETELVINA VII,2025-02-25
27112,0.01,92,0.000109,2422120.0,MANDAQUI,2025-02-21
28120,0.01,63,0.000159,3688010.0,CIDADE A E CARVALHO,2025-02-25
90028,0.01,50,0.000200,4313210.0,VL GUARANI,2025-06-04
216370,0.01,63,0.000159,3688010.0,CIDADE A E CARVALHO,2025-12-09
217455,0.01,239,0.000042,1333904.0,E VAGA,2025-12-16
28259,0.01,112,0.000089,5847500.0,NaN,2025-02-25
128000,0.01,79,0.000127,2422190.0,MANDAQUI,2025-08-08
28900,0.01,109,0.000092,3059050.0,BELENZINHO,2025-03-02
134589,0.01,124,0.000081,5847000.0,NaN,2025-08-14
128904,0.01,146,0.000068,4674901.0,PORTAL DO BROOKLIN,2025-08-07
79019,0.01,72,0.000139,5640001.0,NaN,2025-05-20
141421,0.01,214,0.000047,4080919.0,NaN,2025-08-25

In [49]:
# ============================================================
# INVESTIGAÇÃO DO VALOR RECORRENTE R$ 2.900,51
# ============================================================

df_2900 = df_v1[
    df_v1[col_preco].round(2) == 2900.51
].copy()

print("Quantidade:")
print(len(df_2900))

print("\nDescrição do uso:")
print(
    df_2900["Descrição do uso (IPTU)"]
    .value_counts(dropna=False)
    .head(10)
)

print("\nPadrão IPTU:")
print(
    df_2900["Descrição do padrão (IPTU)"]
    .value_counts(dropna=False)
    .head(10)
)

print("\nCEP mais frequentes:")
print(
    df_2900["CEP"]
    .value_counts(dropna=False)
    .head(15)
)

print("\nBairros mais frequentes:")
print(
    df_2900["Bairro"]
    .value_counts(dropna=False)
    .head(15)
)

Quantidade:
440

Descrição do uso:
Descrição do uso (IPTU)
APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL)    440
Name: count, dtype: int64

Padrão IPTU:
Descrição do padrão (IPTU)
RESIDENCIAL VERTICAL    439
COMERCIAL VERTICAL        1
Name: count, dtype: int64

CEP mais frequentes:
CEP
1520000.0    6
1221001.0    5
4184000.0    4
4349000.0    4
5145901.0    4
3257180.0    3
3156001.0    3
4252000.0    3
3210001.0    3
5144085.0    3
4195040.0    3
4086010.0    3
3210900.0    2
4253000.0    2
3701011.0    2
Name: count, dtype: int64

Bairros mais frequentes:
Bairro
NaN              153
IPIRANGA          10
SAUDE              9
VILA PRUDENTE      6
TORRE B            6
BLOCO 2            5
SACOMA             5
BLOCO 1            5
CONSOLACAO         5
CAMBUCI            4
BLOCO A            4
BLOCO B            4
TORRE A            4
MOOCA              4
TORRE 1            4
Name: count, dtype: int64

In [50]:
# ============================================================
# DISTRIBUIÇÃO TEMPORAL DO VALOR R$ 2.900,51
# ============================================================

data_2900_tmp = pd.to_datetime(
    df_2900["Data de Transação"],
    errors="coerce"
)

print("Tipo original da coluna:")
print(df_2900["Data de Transação"].dtype)

print("\nPeríodo:")
print(data_2900_tmp.min())
print(data_2900_tmp.max())

print("\nQuantidade por mês:")
print(
    data_2900_tmp
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

Tipo original da coluna:
datetime64[us]

Período:
2025-01-29 00:00:00
2025-11-28 00:00:00

Quantidade por mês:

Data de Transação
2025-01     2
2025-02    27
2025-03    52
2025-04    69
2025-05    61
2025-06    51
2025-07    40
2025-08    36
2025-09    34
2025-10    38
2025-11    30
Freq: M, Name: count, dtype: int64

In [51]:
# ============================================================
# CORRIGIR DATA E ANALISAR DISTRIBUIÇÃO MENSAL
# ============================================================

df_2900["Data de Transação"] = pd.to_datetime(
    df_2900["Data de Transação"],
    errors="coerce"
)

print("Tipo da coluna:")
print(df_2900["Data de Transação"].dtype)

print("\nPeríodo:")
print(df_2900["Data de Transação"].min())
print(df_2900["Data de Transação"].max())

print("\nQuantidade por mês:")
print(
    df_2900["Data de Transação"]
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

Tipo da coluna:
datetime64[us]

Período:
2025-01-29 00:00:00
2025-11-28 00:00:00

Quantidade por mês:
Data de Transação
2025-01     2
2025-02    27
2025-03    52
2025-04    69
2025-05    61
2025-06    51
2025-07    40
2025-08    36
2025-09    34
2025-10    38
2025-11    30
Freq: M, Name: count, dtype: int64

In [52]:
# ============================================================
# BASE V2 — REMOÇÃO DE VALORES DE TRANSAÇÃO ANÔMALOS
# ============================================================

limite_valor_minimo = 10000

df_v2 = df_v1[
    df_v1[col_preco] >= limite_valor_minimo
].copy()

print("Base V1:")
print(f"{len(df_v1):,} registros")

print("\nRegistros removidos:")
print(f"{len(df_v1) - len(df_v2):,}")

print(
    f"{(len(df_v1) - len(df_v2)) / len(df_v1) * 100:.2f}% da V1"
)

print("\nBase V2:")
print(f"{len(df_v2):,} registros")

print(
    f"{len(df_v2) / len(df_v1) * 100:.2f}% preservados"
)

Base V1:
64,951 registros

Registros removidos:
1,070
1.65% da V1

Base V2:
63,881 registros
98.35% preservados

In [53]:
# ============================================================
# ANÁLISE DO PREÇO POR M² — BASE V2
# ============================================================

# Recalcular o preço por m²
df_v2["Preco_m2"] = (
    df_v2[col_preco] / df_v2[col_area]
)

# Estatísticas
print("Estatísticas do preço por m² — V2:\n")

print(
    df_v2["Preco_m2"].describe(
        percentiles=[
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
)

# Distribuição da cauda inferior
print("\nQuantidade abaixo de determinados valores:\n")

limites_m2 = [
    100,
    250,
    500,
    750,
    1000,
    1500,
    2000,
    2500,
    3000
]

for limite in limites_m2:
    quantidade = (df_v2["Preco_m2"] < limite).sum()
    percentual = quantidade / len(df_v2) * 100

    print(
        f"Abaixo de R$ {limite:,.0f}/m²: "
        f"{quantidade:,} registros "
        f"({percentual:.2f}%)"
    )

Estatísticas do preço por m² — V2:

count    63881.000000
mean      5453.382564
std       3021.874739
min         25.763359
1%         881.826742
5%        2109.375000
10%       2643.678161
25%       3563.829787
50%       4897.959184
75%       6640.625000
90%       8743.275862
95%      10424.355789
99%      15846.734398
max      56864.337937
Name: Preco_m2, dtype: float64

Quantidade abaixo de determinados valores:

Abaixo de R$ 100/m²: 13 registros (0.02%)
Abaixo de R$ 250/m²: 39 registros (0.06%)
Abaixo de R$ 500/m²: 205 registros (0.32%)
Abaixo de R$ 750/m²: 485 registros (0.76%)
Abaixo de R$ 1,000/m²: 791 registros (1.24%)
Abaixo de R$ 1,500/m²: 1,415 registros (2.22%)
Abaixo de R$ 2,000/m²: 2,734 registros (4.28%)
Abaixo de R$ 2,500/m²: 5,279 registros (8.26%)
Abaixo de R$ 3,000/m²: 9,599 registros (15.03%)

In [54]:
# ============================================================
# INVESTIGAÇÃO DOS APARTAMENTOS COM PREÇO < R$ 2.000/m²
# ============================================================

df_baixo_m2 = df_v2[
    df_v2["Preco_m2"] < 2000
].copy()

print("Quantidade:")
print(f"{len(df_baixo_m2):,}")

print("\nPercentual da V2:")
print(f"{len(df_baixo_m2) / len(df_v2) * 100:.2f}%")

print("\nEstatísticas:")
display(
    df_baixo_m2[
        [col_preco, col_area, "Preco_m2"]
    ].describe(
        percentiles=[
            0.01, 0.05, 0.10,
            0.25, 0.50, 0.75,
            0.90, 0.95, 0.99
        ]
    )
)

print("\nValores de transação mais frequentes:")
display(
    df_baixo_m2[col_preco]
    .value_counts()
    .head(30)
)

print("\nBairros mais frequentes:")
display(
    df_baixo_m2["Bairro"]
    .value_counts(dropna=False)
    .head(30)
)

Quantidade:
2,734

Percentual da V2:
4.28%

Estatísticas:

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2
count,2.734000e+03,2734.000000,2734.000000
mean,1.817778e+05,136.824067,1332.821105
std,1.805511e+05,116.872437,505.432757
min,1.000000e+04,7.000000,25.763359
1%,1.500000e+04,36.330000,202.217069
5%,3.500000e+04,48.000000,443.037975
10%,4.715032e+04,49.000000,567.010309
25%,8.000000e+04,70.000000,916.162901
50%,1.280678e+05,101.000000,1472.455820
75%,2.082981e+05,150.000000,1769.662310
90%,3.746100e+05,266.700000,1909.444635
95%,5.433155e+05,367.350000,1952.126417
99%,9.872881e+05,634.010000,1989.876820
max,1.713775e+06,1038.000000,1999.213846

Valores de transação mais frequentes:

Valor de Transação (declarado pelo contribuinte)
100000.0    72
150000.0    61
200000.0    61
120000.0    45
35000.0     36
70000.0     35
80000.0     34
250000.0    32
90000.0     30
180000.0    28
60000.0     25
160000.0    21
130000.0    20
50000.0     20
500000.0    19
65000.0     19
75000.0     18
30000.0     18
85000.0     17
190000.0    16
270000.0    16
230000.0    15
220000.0    15
140000.0    15
210000.0    15
110000.0    14
400000.0    14
170000.0    12
40000.0     12
350000.0    11
Name: count, dtype: int64

Bairros mais frequentes:

Bairro
NaN                      650
STA ETELVINA IIA          55
STA ETELVINA VII          52
LIBERDADE                 43
BLOCO A                   34
TATUAPE                   32
BLOCO B                   31
MORUMBI                   29
GUAIANAZES                24
TORRE 1                   24
STA ETELVINA I VIA        22
TORRE 2                   20
CJ HAB JOSE BONIFACIO     20
BLOCO 2                   20
SANTANA                   19
BUTANTA                   19
C H PRESID JUSCELINO      18
TORRE A                   18
CD RES SAINT AGOSTINI     15
TORRE B                   15
MOOCA                     15
BLOCO 4                   15
BLOCO 3                   15
BLOCO 1                   14
ITAQUERA                  14
VILA PRUDENTE             13
VILA ANDRADE              13
BROOKLIN                  13
BELENZINHO                12
SITIO CONCEICAO           12
Name: count, dtype: int64

In [55]:
# ============================================================
# COLUNAS AUXILIARES PARA INVESTIGAR A CAUDA BAIXA DA V2
# ============================================================

col_base_calculo = "Base de Cálculo adotada"

df_v2_analise = df_v2.copy()
df_baixo_m2_analise = df_baixo_m2.copy()

for base in [df_v2_analise, df_baixo_m2_analise]:
    cep_num = pd.to_numeric(base["CEP"], errors="coerce")
    base["CEP_8"] = cep_num.round().astype("Int64").astype("string").str.zfill(8)
    base.loc[cep_num.isna(), "CEP_8"] = pd.NA
    base["CEP_prefixo_5"] = base["CEP_8"].str[:5]
    base["Mes_Transacao"] = base["Data de Transação"].dt.to_period("M")
    base["Data_fora_2025"] = ~base["Data de Transação"].between(
        "2025-01-01",
        "2025-12-31"
    )

colunas_qualidade = [
    col_preco,
    col_area,
    "Preco_m2",
    "CEP",
    "CEP_8",
    "Bairro",
    "Data de Transação",
    "N° do Cadastro (SQL)",
    "Matrícula do Imóvel",
    "Descrição do padrão (IPTU)",
    col_base_calculo,
]

print("Valores ausentes em df_baixo_m2:")
display(
    df_baixo_m2_analise[colunas_qualidade]
    .isna()
    .sum()
    .to_frame("n_missing")
)

print("CEPs únicos no grupo baixo m²:")
print(df_baixo_m2_analise["CEP_8"].nunique(dropna=True))

print("\nCEPs com tamanho inválido após normalização:")
print(df_baixo_m2_analise["CEP_8"].dropna().str.len().ne(8).sum())

print("\nDatas fora de 2025 na V2:")
print(
    f"{df_v2_analise['Data_fora_2025'].sum():,} "
    f"({df_v2_analise['Data_fora_2025'].mean() * 100:.2f}%)"
)

print("\nDatas fora de 2025 no grupo baixo m²:")
print(
    f"{df_baixo_m2_analise['Data_fora_2025'].sum():,} "
    f"({df_baixo_m2_analise['Data_fora_2025'].mean() * 100:.2f}%)"
)

Valores ausentes em df_baixo_m2:

                                                  n_missing
Valor de Transação (declarado pelo contribuinte)          0
Área Construída (m2)                                      0
Preco_m2                                                  0
CEP                                                       0
CEP_8                                                     0
Bairro                                                  650
Data de Transação                                         0
N° do Cadastro (SQL)                                      0
Matrícula do Imóvel                                       0
Descrição do padrão (IPTU)                                0
Base de Cálculo adotada                                   0

CEPs únicos no grupo baixo m²:
1494

CEPs com tamanho inválido após normalização:
0

Datas fora de 2025 na V2:
669 (1.05%)

Datas fora de 2025 no grupo baixo m²:
71 (2.60%)

In [56]:
# ============================================================
# SEVERIDADE DA CAUDA INFERIOR POR FAIXAS DE PREÇO/M²
# ============================================================

limites_m2_investigar = [100, 250, 500, 750, 1000, 1500, 2000]
resumo_limites_m2 = []

for limite in limites_m2_investigar:
    parte = df_baixo_m2_analise[
        df_baixo_m2_analise["Preco_m2"] < limite
    ].copy()

    base_calculo = pd.to_numeric(
        parte[col_base_calculo],
        errors="coerce"
    )
    razao_preco_base = parte[col_preco] / base_calculo.replace(0, np.nan)

    resumo_limites_m2.append(
        {
            "Limite_Preco_m2": limite,
            "Quantidade": len(parte),
            "Percentual_V2": len(parte) / len(df_v2_analise) * 100,
            "Preco_mediano": parte[col_preco].median(),
            "Area_mediana": parte[col_area].median(),
            "Base_calculo_zero": (base_calculo == 0).sum(),
            "Razao_preco_base_lt_0_2": (razao_preco_base < 0.2).sum(),
            "Datas_fora_2025": parte["Data_fora_2025"].sum(),
        }
    )

resumo_limites_m2 = pd.DataFrame(resumo_limites_m2)
display(resumo_limites_m2)

,Limite_Preco_m2,Quantidade,Percentual_V2,Preco_mediano,Area_mediana,Base_calculo_zero,Razao_preco_base_lt_0_2,Datas_fora_2025
0,100,13,0.020350,13200.000,246.0,10,3,1
1,250,39,0.061051,15000.000,125.0,13,23,5
2,500,205,0.320909,35000.000,98.0,14,154,11
3,750,485,0.759224,51712.500,101.0,14,280,17
4,1000,791,1.238240,65327.000,106.0,14,331,43
5,1500,1415,2.215056,95000.000,104.0,14,345,53
6,2000,2734,4.279833,128067.835,101.0,14,345,71

In [57]:
# ============================================================
# CONCENTRAÇÃO TEMPORAL E POR PREFIXO DE CEP
# ============================================================

mes_total = (
    df_v2_analise["Mes_Transacao"]
    .value_counts(dropna=False)
    .sort_index()
    .rename("V2_total")
)

mes_baixo = (
    df_baixo_m2_analise["Mes_Transacao"]
    .value_counts(dropna=False)
    .sort_index()
    .rename("Baixo_m2")
)

comparativo_mensal_baixo = (
    pd.concat([mes_total, mes_baixo], axis=1)
    .fillna(0)
)
comparativo_mensal_baixo["Percentual_baixo"] = (
    comparativo_mensal_baixo["Baixo_m2"]
    / comparativo_mensal_baixo["V2_total"]
    * 100
)

print("Distribuição mensal da V2 e da cauda baixa:")
display(comparativo_mensal_baixo.tail(18))

cep_baixo = df_baixo_m2_analise["CEP_prefixo_5"].value_counts(dropna=False).rename("Baixo_m2")
cep_total = df_v2_analise["CEP_prefixo_5"].value_counts(dropna=False).rename("V2_total")

comparativo_cep_baixo = (
    pd.concat([cep_baixo, cep_total], axis=1)
    .fillna(0)
)
comparativo_cep_baixo["Percentual_baixo_no_prefixo"] = (
    comparativo_cep_baixo["Baixo_m2"]
    / comparativo_cep_baixo["V2_total"]
    * 100
)

print("\nPrefixos de CEP mais frequentes no grupo baixo m²:")
display(
    comparativo_cep_baixo
    .sort_values(["Baixo_m2", "Percentual_baixo_no_prefixo"], ascending=False)
    .head(30)
)

print("\nPrefixos com maior concentração relativa, considerando ao menos 10 registros na V2:")
display(
    comparativo_cep_baixo[comparativo_cep_baixo["V2_total"] >= 10]
    .sort_values("Percentual_baixo_no_prefixo", ascending=False)
    .head(30)
)

Distribuição mensal da V2 e da cauda baixa:

               V2_total  Baixo_m2  Percentual_baixo
Mes_Transacao
2024-08               6       5.0         83.333333
2024-09               9       2.0         22.222222
2024-10              11       4.0         36.363636
2024-11              26       3.0         11.538462
2024-12             529      16.0          3.024575
2025-01            4512     163.0          3.612589
2025-02            5007     217.0          4.333932
2025-03            4897     200.0          4.084133
2025-04            5389     210.0          3.896827
2025-05            5656     214.0          3.783593
2025-06            5279     220.0          4.167456
2025-07            5333     235.0          4.406525
2025-08            5370     229.0          4.264432
2025-09            5515     231.0          4.188577
2025-10            5884     221.0          3.755948
2025-11            4902     176.0          3.590371
2025-12            5468     347.0          6.346013
2026-01              11       0.0          0.000000

Prefixos de CEP mais frequentes no grupo baixo m²:

               Baixo_m2  V2_total  Percentual_baixo_no_prefixo
CEP_prefixo_5
08485                86       152                    56.578947
08475                46        94                     48.93617
08260                43       138                     31.15942
01320                39        69                    56.521739
08470                25        35                    71.428571
05782                23       168                    13.690476
05356                22        51                    43.137255
05724                22       180                    12.222222
08471                21        28                         75.0
08473                19        23                    82.608696
08460                19        29                    65.517241
05630                19        93                    20.430108
05713                19       137                    13.868613
03928                18        59                    30.508475
03220                17        69                    24.637681
05641                16       147                    10.884354
08290                15       126                    11.904762
08295                15       147                    10.204082
02435                15       160                        9.375
04703                14        17                    82.352941
08381                14        19                    73.684211
08490                13        34                    38.235294
05642                13        87                    14.942529
08253                13       107                    12.149533
08465                12        18                    66.666667
01034                12        22                    54.545455
08140                12        25                         48.0
08410                12        42                    28.571429
03362                12        43                    27.906977
05583                12        60                         20.0

Prefixos com maior concentração relativa, considerando ao menos 10 registros na V2:

               Baixo_m2  V2_total  Percentual_baixo_no_prefixo
CEP_prefixo_5
08473                19        23                    82.608696
04703                14        17                    82.352941
08471                21        28                         75.0
08381                14        19                    73.684211
08470                25        35                    71.428571
08461                11        16                        68.75
08040                 8        12                    66.666667
08465                12        18                    66.666667
08460                19        29                    65.517241
08320                 6        10                         60.0
08485                86       152                    56.578947
01320                39        69                    56.521739
08081                 6        11                    54.545455
08474                 6        11                    54.545455
01034                12        22                    54.545455
03584                11        21                    52.380952
08257                 6        12                         50.0
03276                 5        10                         50.0
08341                 5        10                         50.0
08475                46        94                     48.93617
08140                12        25                         48.0
04291                 7        15                    46.666667
02815                 7        15                    46.666667
05886                 5        11                    45.454545
03151                 5        11                    45.454545
02550                11        25                         44.0
05356                22        51                    43.137255
05659                11        26                    42.307692
08412                 5        12                    41.666667
03374                 9        22                    40.909091

In [58]:
# ============================================================
# DUPLICATAS EXATAS E POSSÍVEIS DUPLICATAS ADMINISTRATIVAS
# ============================================================

colunas_chave_duplicata = [
    "N° do Cadastro (SQL)",
    col_preco,
    col_area,
    "Data de Transação",
    "CEP",
    "Matrícula do Imóvel",
]

resumo_duplicatas = pd.DataFrame(
    [
        {
            "Base": "V2",
            "Duplicatas_linha_completa": df_v2_analise.duplicated().sum(),
            "Duplicatas_chave_candidata": df_v2_analise.duplicated(
                subset=colunas_chave_duplicata,
                keep=False
            ).sum(),
        },
        {
            "Base": "Baixo_m2",
            "Duplicatas_linha_completa": df_baixo_m2_analise.duplicated().sum(),
            "Duplicatas_chave_candidata": df_baixo_m2_analise.duplicated(
                subset=colunas_chave_duplicata,
                keep=False
            ).sum(),
        },
    ]
)

display(resumo_duplicatas)

duplicatas_baixo_m2 = df_baixo_m2_analise[
    df_baixo_m2_analise.duplicated(
        subset=colunas_chave_duplicata,
        keep=False
    )
].sort_values(colunas_chave_duplicata)

display(
    duplicatas_baixo_m2[
        colunas_chave_duplicata
        + ["Mes_Arquivo", "Preco_m2", "Bairro"]
    ].head(30)
)

       Base  Duplicatas_linha_completa  Duplicatas_chave_candidata
0        V2                         48                         118
1  Baixo_m2                          5                          12

,N° do Cadastro (SQL),Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Data de Transação,CEP,Matrícula do Imóvel,Mes_Arquivo,Preco_m2,Bairro
158209,603004741,48986.94,73,2025-09-16,1314000.0,81852,SET-2025,671.053973,CONSOLACAO
158220,603004741,48986.94,73,2025-09-16,1314000.0,81852,SET-2025,671.053973,CONSOLACAO
130316,4905901235,123020.24,236,2025-08-05,4286100.0,160037,AGO-2025,521.272203,NaN
130328,4905901235,123020.24,236,2025-08-05,4286100.0,160037,AGO-2025,521.272203,NaN
33347,6104700675,63789.00,134,2025-03-06,3605000.0,132950,MAR-2025,476.037313,NaN
33360,6104700675,63789.00,134,2025-03-06,3605000.0,132950,MAR-2025,476.037313,NaN
203074,6747402960,145494.00,95,2025-11-24,2276100.0,19546,NOV-2025,1531.515789,JACANA
203099,6747402960,145494.00,95,2025-11-24,2276100.0,19546,NOV-2025,1531.515789,JACANA
171347,15523013004,66500.00,104,2025-10-09,3220300.0,139503,OUT-2025,639.423077,NaN
171350,15523013004,66500.00,104,2025-10-09,3220300.0,139503,OUT-2025,639.423077,NaN
8500,21500204860,27888.75,57,2025-01-20,2815020.0,81700,JAN-2025,489.276316,C H BRIG ED GOMES
98911,21500204860,27888.75,57,2025-01-20,2815020.0,81700,JUN-2025,489.276316,C H BRIG ED GOMES

In [59]:
# ============================================================
# RELAÇÃO ENTRE VALOR DECLARADO E BASE DE CÁLCULO
# ============================================================

base_calculo_baixo = pd.to_numeric(
    df_baixo_m2_analise[col_base_calculo],
    errors="coerce"
)

razao_preco_base_baixo = (
    df_baixo_m2_analise[col_preco]
    / base_calculo_baixo.replace(0, np.nan)
)

print("Base de cálculo igual a zero no grupo baixo m²:")
print(
    f"{(base_calculo_baixo == 0).sum():,} "
    f"({(base_calculo_baixo == 0).mean() * 100:.2f}%)"
)

print("\nRazão valor declarado / base de cálculo:")
display(
    razao_preco_base_baixo.describe(
        percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nCasos com preço/m² mais baixo na V2:")
display(
    df_baixo_m2_analise
    .nsmallest(30, "Preco_m2")[
        [
            col_preco,
            col_area,
            "Preco_m2",
            "CEP_8",
            "Bairro",
            "Descrição do padrão (IPTU)",
            "Data de Transação",
            "Mes_Arquivo",
            col_base_calculo,
            "Valor Venal de Referência",
        ]
    ]
)

Base de cálculo igual a zero no grupo baixo m²:
14 (0.51%)

Razão valor declarado / base de cálculo:

count    2720.000000
mean        0.528498
std         0.282662
min         0.009126
1%          0.089156
5%          0.133372
10%         0.179611
25%         0.283075
50%         0.500157
75%         0.738130
90%         1.000000
95%         1.000000
99%         1.000000
max         1.000000
dtype: float64

Casos com preço/m² mais baixo na V2:

,Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,CEP_8,Bairro,Descrição do padrão (IPTU),Data de Transação,Mes_Arquivo,Base de Cálculo adotada,Valor Venal de Referência
46447,13500.00,524,25.763359,02022051,NaN,RESIDENCIAL VERTICAL,2025-03-31,MAR-2025,0.0,0.0
9522,19091.58,618,30.892524,01240000,E 21 / CONCOLACAO,RESIDENCIAL VERTICAL,2024-11-21,JAN-2025,0.0,0.0
226081,19800.00,532,37.218045,05605020,E DEP 07,RESIDENCIAL VERTICAL,2025-12-19,DEZ-2025,0.0,0.0
170699,10357.46,246,42.103496,03118001,NaN,RESIDENCIAL VERTICAL,2025-09-19,OUT-2025,0.0,0.0
65038,12000.00,276,43.478261,03322000,DEPOSITO 04 1 SS,RESIDENCIAL VERTICAL,2025-04-29,ABR-2025,1314981.0,1314981.0
37106,13034.57,246,52.986057,05351080,TORRE B,RESIDENCIAL VERTICAL,2025-01-14,MAR-2025,0.0,0.0
106604,13200.00,218,60.550459,05634001,TORRE 5,RESIDENCIAL VERTICAL,2025-07-02,JUL-2025,0.0,0.0
51266,14114.31,220,64.155955,05713410,NaN,RESIDENCIAL VERTICAL,2025-03-12,ABR-2025,0.0,0.0
37761,25593.39,371,68.984879,04027000,TORRE RES 1,RESIDENCIAL VERTICAL,2025-02-10,MAR-2025,0.0,0.0
212529,11577.60,154,75.179221,01224010,HIGIENOPOLIS,RESIDENCIAL VERTICAL,2025-12-03,DEZ-2025,0.0,0.0
203953,10203.96,125,81.631680,04002001,NaN,RESIDENCIAL VERTICAL,2025-12-02,NOV-2025,671926.0,671926.0
146314,10000.00,120,83.333333,02671020,BLOCO J,RESIDENCIAL VERTICAL,2025-09-02,AGO-2025,269841.0,269841.0
172481,24228.36,277,87.467004,01227200,NaN,RESIDENCIAL VERTICAL,2025-08-28,OUT-2025,0.0,0.0
173190,10000.00,87,114.942529,03257180,VILA INDUSTRIAL,RESIDENCIAL VERTICAL,2003-02-12,OUT-2025,39601.0,39601.0
221744,25650.00,219,117.123288,05577100,TORRE P-2 ESPACO OMEGA,RESIDENCIAL VERTICAL,2025-12-16,DEZ-2025,0.0,0.0
217906,52282.62,446,117.225605,05018010,VAGAS 61 94 A 96 SS 1,RESIDENCIAL VERTICAL,2025-12-09,DEZ-2025,0.0,0.0
221491,12000.00,101,118.811881,04195010,EDIFICIO UBATUBA,RESIDENCIAL VERTICAL,2025-12-18,DEZ-2025,241792.0,241792.0
221122,10000.00,80,125.000000,05038902,ED. CANARIO,RESIDENCIAL VERTICAL,2025-12-19,DEZ-2025,236152.0,236152.0
85982,15000.00,107,140.186916,05583070,BUTANTA,RESIDENCIAL VERTICAL,2025-05-29,MAI-2025,247688.0,247688.0
141775,15000.00,103,145.631068,05845240,BLOCO 10,RESIDENCIAL VERTICAL,2025-08-29,AGO-2025,247867.0,247867.0
38001,20000.00,131,152.671756,08473130,CJ HAB SITIO CONCEICAO,RESIDENCIAL VERTICAL,2025-03-20,MAR-2025,289713.0,289713.0
83670,25288.59,152,166.372303,04566000,IBIRAPUERA,RESIDENCIAL VERTICAL,2025-03-19,MAI-2025,0.0,0.0
89868,16000.00,87,183.908046,05145901,BLOCO 13,RESIDENCIAL VERTICAL,2025-06-03,JUN-2025,239910.0,239910.0
22353,15000.00,81,185.185185,08040600,TORRE 05 S M PAULISTA,RESIDENCIAL VERTICAL,2025-02-20,FEV-2025,181231.0,181231.0
23113,26769.00,142,188.514085,01533000,LIBERDADE,RESIDENCIAL VERTICAL,2025-02-12,FEV-2025,427385.0,427385.0
10393,10000.00,53,188.679245,08191350,ITAIM PAULISTA,RESIDENCIAL VERTICAL,2025-01-24,JAN-2025,112145.0,112145.0
158681,24000.00,120,200.000000,05145901,BLOCO 18,RESIDENCIAL VERTICAL,2025-09-23,SET-2025,330861.0,330861.0
209000,15500.00,77,201.298701,03116900,NaN,RESIDENCIAL VERTICAL,2025-09-30,DEZ-2025,15500.0,0.0
211794,10000.00,49,204.081633,08485010,STA ETELVINA IIA,RESIDENCIAL VERTICAL,2025-12-03,DEZ-2025,82296.0,82296.0
221955,105600.00,508,207.874016,03309060,NaN,RESIDENCIAL VERTICAL,2025-12-18,DEZ-2025,2476408.0,2476408.0

### Leitura parcial da cauda baixa da V2

- O grupo `Preco_m2 < 2000` tem 2.734 registros, ou 4,28% da V2. Ele ainda é grande demais para ser removido automaticamente sem separar subgrupos.
- Abaixo de `R$ 500/m²` restam 205 registros, apenas 0,32% da V2. Esse subgrupo concentra os sinais mais fortes de anomalia econômica/administrativa: valores absolutos muito baixos, vários casos com razão valor declarado/base de cálculo muito pequena e alguns casos com base de cálculo/valor venal igual a zero.
- `Bairro` segue ruidoso; para esta investigação, `CEP_8` e prefixos de CEP são mais úteis. O grupo baixo m² tem 1.494 CEPs únicos e nenhum CEP inválido após normalização simples para oito dígitos.
- Existe uma inconsistência temporal relevante: a V2 possui 669 registros com `Data de Transação` fora de 2025 (1,05% da V2), e o grupo baixo m² possui 71 (2,60%). Antes de modelagem temporal, esses registros precisam ser tratados explicitamente.
- Foram encontrados registros duplicados ou potencialmente duplicados, mas eles explicam uma parte pequena da cauda baixa. A deduplicação deve ser analisada como uma regra própria, não misturada com o corte de preço/m².

Próximo passo recomendado: não cortar todos os imóveis abaixo de `R$ 2.000/m²`. Investigar primeiro uma regra candidata mais conservadora para o subgrupo extremo (`Preco_m2 < 500`, base de cálculo zero, ou razão valor declarado/base de cálculo muito baixa), em paralelo com uma decisão separada sobre datas fora de 2025 e duplicatas.

## VALIDAÇÃO DAS REGRAS CANDIDATAS PARA V3

Esta seção avalia cada regra sem alterar a V2 e sem criar a V3. As regras R1–R5 entram apenas em uma união hipotética; R6 permanece exclusivamente diagnóstica.

- **R1:** `Preco_m2 < 500`.
- **R2:** `Base de Cálculo adotada == 0`.
- **R3:** valor de transação dividido pela base de cálculo adotada `< 0.2`; bases iguais a zero ou ausentes não recebem razão e são tratadas apenas por R2.
- **R4:** data de transação fora de 2025; datas inválidas ou ausentes também ficariam fora do recorte.
- **R5:** cópias excedentes de linhas exatamente iguais, preservando a primeira ocorrência. O total de participantes dos grupos duplicados também é informado.
- **R6:** possíveis duplicatas por chaves de negócio. Não integra a união e não implica remoção.

### Significado da Base de Cálculo adotada

No ITBI paulistano, a base de cálculo tem natureza **fiscal**: o art. 7º da [Lei Municipal nº 11.154/1991](https://legislacao.prefeitura.sp.gov.br/lei-11154-de-30-de-dezembro-de-1991) a define como o valor venal do bem ou direito transmitido, entendido como o valor de negociação à vista em condições normais de mercado. A própria legislação também prevê situações e procedimentos específicos de arbitramento ou avaliação.

Portanto, `Base de Cálculo adotada` não deve ser tratada automaticamente como verdade observada do preço de mercado nem como uma medição independente do valor declarado. R2 e R3 são sinais de auditoria da coerência administrativa/econômica do registro. A célula seguinte verifica o tipo, a completude e a distribuição empírica antes de construir essas regras.

In [60]:
# ============================================================
# AUDITORIA DA COLUNA BASE DE CÁLCULO ADOTADA
# ============================================================

col_base_calculo = "Base de Cálculo adotada"
base_calculo_original = df_v2[col_base_calculo]
base_calculo_v2 = pd.to_numeric(base_calculo_original, errors="coerce")
vvr_v2 = pd.to_numeric(df_v2["Valor Venal de Referência"], errors="coerce")

auditoria_base_calculo = pd.DataFrame(
    {
        "Métrica": [
            "dtype original",
            "registros",
            "ausentes originais",
            "falhas adicionais na conversão numérica",
            "valores iguais a zero",
            "valores negativos",
            "valores positivos",
            "valores únicos",
        ],
        "Valor": [
            str(base_calculo_original.dtype),
            len(base_calculo_original),
            int(base_calculo_original.isna().sum()),
            int((base_calculo_original.notna() & base_calculo_v2.isna()).sum()),
            int(base_calculo_v2.eq(0).sum()),
            int(base_calculo_v2.lt(0).sum()),
            int(base_calculo_v2.gt(0).sum()),
            int(base_calculo_v2.nunique(dropna=True)),
        ],
    }
)
display(auditoria_base_calculo)

print("Distribuição numérica da base de cálculo adotada:")
display(
    base_calculo_v2.describe(
        percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    ).to_frame("Base de Cálculo adotada")
)

faixas_base_calculo = pd.cut(
    base_calculo_v2,
    bins=[-np.inf, 0, 10_000, 50_000, 100_000, 250_000, 500_000, 1_000_000, np.inf],
    include_lowest=True,
)
distribuicao_faixas_base = (
    faixas_base_calculo.value_counts(sort=False, dropna=False)
    .rename("Registros")
    .to_frame()
)
distribuicao_faixas_base["Percentual_V2"] = (
    distribuicao_faixas_base["Registros"] / len(df_v2) * 100
)
print("Distribuição por faixas:")
display(distribuicao_faixas_base)

comparacao_base = pd.DataFrame(
    {
        "Comparação": [
            "base adotada = valor venal de referência",
            "base adotada = valor de transação",
        ],
        "Registros": [
            int(np.isclose(base_calculo_v2, vvr_v2, rtol=0, atol=0.01, equal_nan=False).sum()),
            int(np.isclose(base_calculo_v2, df_v2[col_preco], rtol=0, atol=0.01, equal_nan=False).sum()),
        ],
    }
)
comparacao_base["Percentual_V2"] = comparacao_base["Registros"] / len(df_v2) * 100
print("Relação empírica com outras colunas monetárias:")
display(comparacao_base)

print("Valores mais frequentes da base de cálculo adotada:")
display(base_calculo_v2.value_counts(dropna=False).head(15).to_frame("Registros"))

                                   Métrica    Valor
0                           dtype original  float64
1                                registros    63881
2                       ausentes originais        0
3  falhas adicionais na conversão numérica        0
4                    valores iguais a zero       14
5                        valores negativos        0
6                        valores positivos    63867
7                           valores únicos    19923

Distribuição numérica da base de cálculo adotada:

       Base de Cálculo adotada
count             6.388100e+04
mean              7.822795e+05
std               1.355110e+06
min               0.000000e+00
1%                1.100000e+05
5%                1.966510e+05
10%               2.394550e+05
25%               3.073445e+05
50%               4.650000e+05
75%               8.200000e+05
90%               1.490000e+06
95%               2.154000e+06
99%               5.200000e+06
max               7.000000e+07

Distribuição por faixas:

                         Registros  Percentual_V2
Base de Cálculo adotada
(-inf, 0.0]                     14       0.021916
(0.0, 10000.0]                   0       0.000000
(10000.0, 50000.0]              27       0.042266
(50000.0, 100000.0]            430       0.673127
(100000.0, 250000.0]          7862      12.307259
(250000.0, 500000.0]         26334      41.223525
(500000.0, 1000000.0]        17407      27.249104
(1000000.0, inf]             11807      18.482804

Relação empírica com outras colunas monetárias:

                                 Comparação  Registros  Percentual_V2
0  base adotada = valor venal de referência      13486      21.111129
1         base adotada = valor de transação      51015      79.859426

Valores mais frequentes da base de cálculo adotada:

                         Registros
Base de Cálculo adotada
300000.0                       757
350000.0                       747
250000.0                       720
400000.0                       614
500000.0                       592
450000.0                       531
320000.0                       512
280000.0                       477
270000.0                       460
330000.0                       447
600000.0                       442
260000.0                       410
290000.0                       380
240000.0                       373
380000.0                       370

In [61]:
# ============================================================
# CONSTRUÇÃO DAS MÁSCARAS DIAGNÓSTICAS R1–R5
# ============================================================

data_transacao_v2 = pd.to_datetime(df_v2["Data de Transação"], errors="coerce")
razao_transacao_base_v2 = df_v2[col_preco] / base_calculo_v2.replace(0, np.nan)

mask_r1 = df_v2["Preco_m2"].lt(500)
mask_r2 = base_calculo_v2.eq(0)
mask_r3 = razao_transacao_base_v2.lt(0.2)
mask_r4 = data_transacao_v2.dt.year.ne(2025)
mask_r5 = df_v2.duplicated(keep="first")
mask_r5_grupos = df_v2.duplicated(keep=False)

mascaras_regras = pd.DataFrame(
    {"R1": mask_r1, "R2": mask_r2, "R3": mask_r3, "R4": mask_r4, "R5": mask_r5},
    index=df_v2.index,
)

df_validacao_regras = df_v2_analise.copy()
df_validacao_regras["Base_calculo_numerica"] = base_calculo_v2
df_validacao_regras["Razao_transacao_base"] = razao_transacao_base_v2
df_validacao_regras["Data_analise"] = data_transacao_v2

contagens_iniciais = mascaras_regras.sum().rename("Registros").to_frame()
contagens_iniciais["Percentual_V2"] = contagens_iniciais["Registros"] / len(df_v2) * 100
display(contagens_iniciais)

print("R5 — participantes de grupos de linhas exatamente iguais:")
print(f"{mask_r5_grupos.sum():,} registros")
print("R5 — cópias excedentes candidatas à remoção, mantendo uma ocorrência:")
print(f"{mask_r5.sum():,} registros")

    Registros  Percentual_V2
R1        205       0.320909
R2         14       0.021916
R3        345       0.540067
R4        669       1.047260
R5         48       0.075140

R5 — participantes de grupos de linhas exatamente iguais:
96 registros
R5 — cópias excedentes candidatas à remoção, mantendo uma ocorrência:
48 registros

In [62]:
# ============================================================
# DIAGNÓSTICO INDIVIDUAL DE R1–R5
# ============================================================

colunas_exemplo_regras = [
    "N° do Cadastro (SQL)",
    col_preco,
    col_area,
    "Preco_m2",
    col_base_calculo,
    "Razao_transacao_base",
    "Data de Transação",
    "Mes_Arquivo",
    "CEP_8",
    "Matrícula do Imóvel",
]

ordenacao_exemplos = {
    "R1": ["Preco_m2"],
    "R2": ["Preco_m2"],
    "R3": ["Razao_transacao_base"],
    "R4": ["Data_analise"],
    "R5": ["N° do Cadastro (SQL)", "Data_analise"],
}

def exibir_diagnostico_regra(nome_regra, mascara, n_exemplos=10):
    parte = df_validacao_regras.loc[mascara].copy()
    percentual = len(parte) / len(df_v2) * 100

    print(f"\n{nome_regra}: {len(parte):,} registros ({percentual:.4f}% da V2)")
    estatisticas = parte[[col_preco, "Preco_m2", col_area]].describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    ).T
    display(estatisticas)

    distribuicao_ano = (
        parte["Data_analise"].dt.year
        .value_counts(dropna=False)
        .sort_index()
        .rename("Registros")
        .to_frame()
    )
    distribuicao_ano["Percentual_regra"] = distribuicao_ano["Registros"] / len(parte) * 100
    print("Distribuição por ano:")
    display(distribuicao_ano)

    distribuicao_mes = (
        parte["Data_analise"].dt.to_period("M")
        .value_counts(dropna=False)
        .sort_index()
        .rename("Registros")
        .to_frame()
    )
    distribuicao_mes["Percentual_regra"] = distribuicao_mes["Registros"] / len(parte) * 100
    print("Distribuição por mês de transação:")
    display(distribuicao_mes)

    print("Exemplos:")
    display(
        parte.sort_values(ordenacao_exemplos[nome_regra], na_position="last")
        [colunas_exemplo_regras]
        .head(n_exemplos)
    )

for regra in ["R1", "R2", "R3", "R4", "R5"]:
    exibir_diagnostico_regra(regra, mascaras_regras[regra])

print("R5 — exemplos com a ocorrência preservada e suas cópias exatas:")
display(
    df_validacao_regras.loc[mask_r5_grupos, colunas_exemplo_regras]
    .sort_values(["N° do Cadastro (SQL)", "Data de Transação", col_preco])
    .head(30)
)

R1: 205 registros (0.3209% da V2)

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
Valor de Transação (declarado pelo contribuinte),205.0,43940.864341,43352.127039,10000.000000,10000.000000,11662.080000,23000.000000,35000.000000,48000.00000,116311.040000,179400.000000,397000.000000
Preco_m2,205.0,357.850078,127.611787,25.763359,37.413463,81.972011,272.079726,403.962703,452.34375,494.344028,496.343679,499.723214
Área Construída (m2),205.0,132.624390,119.357514,43.000000,45.000000,49.200000,79.000000,98.000000,136.00000,355.400000,614.560000,1038.000000

Distribuição por ano:

              Registros  Percentual_regra
Data_analise
2003                  1          0.487805
2007                  1          0.487805
2019                  1          0.487805
2023                  1          0.487805
2024                  7          3.414634
2025                194         94.634146

Distribuição por mês de transação:

              Registros  Percentual_regra
Data_analise
2003-02               1          0.487805
2007-10               1          0.487805
2019-10               1          0.487805
2023-09               1          0.487805
2024-04               1          0.487805
2024-09               2          0.975610
2024-10               1          0.487805
2024-11               1          0.487805
2024-12               2          0.975610
2025-01               9          4.390244
2025-02              13          6.341463
2025-03              16          7.804878
2025-04               9          4.390244
2025-05              12          5.853659
2025-06               9          4.390244
2025-07              19          9.268293
2025-08              16          7.804878
2025-09              18          8.780488
2025-10               8          3.902439
2025-11               6          2.926829
2025-12              59         28.780488

Exemplos:

,N° do Cadastro (SQL),Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,Base de Cálculo adotada,Razao_transacao_base,Data de Transação,Mes_Arquivo,CEP_8,Matrícula do Imóvel
46447,7300501419,13500.00,524,25.763359,0.0,NaN,2025-03-31,MAR-2025,02022051,158789
9522,1000102343,19091.58,618,30.892524,0.0,NaN,2024-11-21,JAN-2025,01240000,58175
226081,8427400306,19800.00,532,37.218045,0.0,NaN,2025-12-19,DEZ-2025,05605020,177847
170699,3203302659,10357.46,246,42.103496,0.0,NaN,2025-09-19,OUT-2025,03118001,161190
65038,3012700293,12000.00,276,43.478261,1314981.0,0.009126,2025-04-29,ABR-2025,03322000,284754
37106,16036812107,13034.57,246,52.986057,0.0,NaN,2025-01-14,MAR-2025,05351080,196861
106604,17126705432,13200.00,218,60.550459,0.0,NaN,2025-07-02,JUL-2025,05634001,218812
51266,17001901104,14114.31,220,64.155955,0.0,NaN,2025-03-12,ABR-2025,05713410,187110
37761,4213806261,25593.39,371,68.984879,0.0,NaN,2025-02-10,MAR-2025,04027000,242922
212529,703201611,11577.60,154,75.179221,0.0,NaN,2025-12-03,DEZ-2025,01224010,28727

R2: 14 registros (0.0219% da V2)

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
Valor de Transação (declarado pelo contribuinte),14.0,20170.474286,10797.703187,10357.460000,10516.07820,11150.551000,13275.000000,16879.870000,25023.532500,34971.417000,48820.379400,52282.620000
Preco_m2,14.0,90.855807,78.077408,25.763359,26.43015,29.097316,44.824136,66.570417,109.709217,222.227686,305.212826,325.959111
Área Construída (m2),14.0,304.857143,167.663058,45.000000,58.91000,114.550000,218.250000,246.000000,427.250000,562.100000,606.820000,618.000000

Distribuição por ano:

              Registros  Percentual_regra
Data_analise
2024                  1          7.142857
2025                 13         92.857143

Distribuição por mês de transação:

              Registros  Percentual_regra
Data_analise
2024-11               1          7.142857
2025-01               1          7.142857
2025-02               2         14.285714
2025-03               3         21.428571
2025-07               1          7.142857
2025-08               1          7.142857
2025-09               1          7.142857
2025-12               4         28.571429

Exemplos:

,N° do Cadastro (SQL),Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,Base de Cálculo adotada,Razao_transacao_base,Data de Transação,Mes_Arquivo,CEP_8,Matrícula do Imóvel
46447,7300501419,13500.00,524,25.763359,0.0,NaN,2025-03-31,MAR-2025,02022051,158789
9522,1000102343,19091.58,618,30.892524,0.0,NaN,2024-11-21,JAN-2025,01240000,58175
226081,8427400306,19800.00,532,37.218045,0.0,NaN,2025-12-19,DEZ-2025,05605020,177847
170699,3203302659,10357.46,246,42.103496,0.0,NaN,2025-09-19,OUT-2025,03118001,161190
37106,16036812107,13034.57,246,52.986057,0.0,NaN,2025-01-14,MAR-2025,05351080,196861
106604,17126705432,13200.00,218,60.550459,0.0,NaN,2025-07-02,JUL-2025,05634001,218812
51266,17001901104,14114.31,220,64.155955,0.0,NaN,2025-03-12,ABR-2025,05713410,187110
37761,4213806261,25593.39,371,68.984879,0.0,NaN,2025-02-10,MAR-2025,04027000,242922
212529,703201611,11577.60,154,75.179221,0.0,NaN,2025-12-03,DEZ-2025,01224010,28727
172481,1001902483,24228.36,277,87.467004,0.0,NaN,2025-08-28,OUT-2025,01227200,48264

R3: 345 registros (0.5401% da V2)

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
Valor de Transação (declarado pelo contribuinte),345.0,88228.999391,98203.944959,10000.000000,10000.000000,15200.000000,35000.000000,56800.000000,100000.0,265240.000000,493740.766800,900000.000000
Preco_m2,345.0,560.208417,228.446723,43.478261,121.534653,219.572613,442.703313,521.272203,680.0,962.342338,1160.636475,1367.781155
Área Construída (m2),345.0,146.153623,114.521310,42.000000,45.440000,52.000000,79.000000,107.000000,168.0,360.400000,653.160000,794.000000

Distribuição por ano:

              Registros  Percentual_regra
Data_analise
2024                  6           1.73913
2025                339          98.26087

Distribuição por mês de transação:

              Registros  Percentual_regra
Data_analise
2024-04               1          0.289855
2024-09               2          0.579710
2024-11               1          0.289855
2024-12               2          0.579710
2025-01              19          5.507246
2025-02              20          5.797101
2025-03              30          8.695652
2025-04              20          5.797101
2025-05              19          5.507246
2025-06              19          5.507246
2025-07              30          8.695652
2025-08              28          8.115942
2025-09              27          7.826087
2025-10               9          2.608696
2025-11              27          7.826087
2025-12              91         26.376812

Exemplos:

,N° do Cadastro (SQL),Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,Base de Cálculo adotada,Razao_transacao_base,Data de Transação,Mes_Arquivo,CEP_8,Matrícula do Imóvel
65038,3012700293,12000.00,276,43.478261,1314981.0,0.009126,2025-04-29,ABR-2025,03322000,284754
203953,3600403311,10203.96,125,81.631680,671926.0,0.015186,2025-12-02,NOV-2025,04002001,102942
146314,30505105079,10000.00,120,83.333333,269841.0,0.037059,2025-09-02,AGO-2025,02671020,103376
221122,9904304424,10000.00,80,125.000000,236152.0,0.042346,2025-12-19,DEZ-2025,05038902,28869
221955,5408602915,105600.00,508,207.874016,2476408.0,0.042642,2025-12-18,DEZ-2025,03309060,220826
221491,15721300832,12000.00,101,118.811881,241792.0,0.049629,2025-12-18,DEZ-2025,04195010,199476
226541,8510702861,27759.23,103,269.507087,535707.0,0.051818,2025-12-23,DEZ-2025,04560010,137000
4149,909206376,30000.00,113,265.486726,520744.0,0.057610,2025-01-15,JAN-2025,01423040,37040
51137,4514103624,44822.84,166,270.017108,748473.0,0.059886,2025-04-07,ABR-2025,04047003,175658
141775,12213303451,15000.00,103,145.631068,247867.0,0.060516,2025-08-29,AGO-2025,05845240,273808

R4: 669 registros (1.0473% da V2)

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
Valor de Transação (declarado pelo contribuinte),669.0,684174.955635,1.035882e+06,10000.000000,26620.753600,45664.644000,255000.000000,412000.0,740000.000000,1.896600e+06,5.755200e+06,1.300000e+07
Preco_m2,669.0,5015.879141,3.201414e+03,30.892524,420.671121,930.981551,3229.166667,4400.0,6081.081081,1.097532e+04,1.857567e+04,2.653846e+04
Área Construída (m2),669.0,121.436472,9.446874e+01,26.000000,34.000000,43.000000,63.000000,97.0,137.000000,2.922000e+02,5.951600e+02,7.830000e+02

Distribuição por ano:

              Registros  Percentual_regra
Data_analise
2003                  1          0.149477
2007                  1          0.149477
2010                  1          0.149477
2017                  1          0.149477
2018                  1          0.149477
2019                  2          0.298954
2020                  2          0.298954
2021                  2          0.298954
2022                 12          1.793722
2023                 27          4.035874
2024                608         90.881913
2026                 11          1.644245

Distribuição por mês de transação:

              Registros  Percentual_regra
Data_analise
2003-02               1          0.149477
2007-10               1          0.149477
2010-07               1          0.149477
2017-04               1          0.149477
2018-11               1          0.149477
2019-05               1          0.149477
2019-10               1          0.149477
2020-02               1          0.149477
2020-12               1          0.149477
2021-02               1          0.149477
2021-12               1          0.149477
2022-01               1          0.149477
2022-02               2          0.298954
2022-03               1          0.149477
2022-04               1          0.149477
2022-05               1          0.149477
2022-07               2          0.298954
2022-09               1          0.149477
2022-10               2          0.298954
2022-12               1          0.149477
2023-01               5          0.747384
2023-02               5          0.747384
2023-05               2          0.298954
2023-06               1          0.149477
2023-07               2          0.298954
2023-08               2          0.298954
2023-09               2          0.298954
2023-10               3          0.448430
2023-11               2          0.298954
2023-12               3          0.448430
2024-01               2          0.298954
2024-02               3          0.448430
2024-03               5          0.747384
2024-04               6          0.896861
2024-05               3          0.448430
2024-06               3          0.448430
2024-07               5          0.747384
2024-08               6          0.896861
2024-09               9          1.345291
2024-10              11          1.644245
2024-11              26          3.886398
2024-12             529         79.073244
2026-01              11          1.644245

Exemplos:

,N° do Cadastro (SQL),Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,Base de Cálculo adotada,Razao_transacao_base,Data de Transação,Mes_Arquivo,CEP_8,Matrícula do Imóvel
173190,15523010511,10000.0,87,114.942529,39601.0,0.252519,2003-02-12,OUT-2025,03257180,118617
7552,3706402701,25000.0,83,301.204819,75315.0,0.331939,2007-10-30,JAN-2025,04010905,33686
72292,13805202716,64600.0,93,694.623656,88550.0,0.729531,2010-07-29,MAI-2025,08246000,172653
149364,4409101196,200000.0,118,1694.915254,268668.0,0.744413,2017-04-17,SET-2025,03143001,124964
132427,19700604471,240000.0,54,4444.444444,240000.0,1.000000,2018-11-01,AGO-2025,05037001,132308
193053,11411201581,175000.0,98,1785.714286,175000.0,1.000000,2019-05-02,NOV-2025,08295030,159839
110253,13900601355,36487.8,78,467.792308,102944.0,0.354443,2019-10-28,JUL-2025,08032500,140959
2175,8707307659,500000.0,138,3623.188406,500000.0,1.000000,2020-02-17,JAN-2025,04741000,409110
124575,8809502108,221930.0,55,4035.090909,221930.0,1.000000,2020-12-11,JUL-2025,04737000,431044
69514,6210508235,861200.0,151,5703.311258,861200.0,1.000000,2021-02-18,MAI-2025,03080010,253977

R5: 48 registros (0.0751% da V2)

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
Valor de Transação (declarado pelo contribuinte),48.0,439919.416042,629982.068891,48986.940000,55943.908200,86282.08400,249099.450000,304560.000000,450000.000000,798810.150000,2.859700e+06,4.500000e+06
Preco_m2,48.0,5837.431717,3055.755152,476.037313,497.297712,650.49389,3866.982185,5941.096111,7647.058824,9990.789474,1.344786e+04,1.363636e+04
Área Construída (m2),48.0,93.437500,133.043891,30.000000,31.410000,33.35000,38.750000,53.500000,102.500000,196.300000,6.059400e+02,9.340000e+02

Distribuição por ano:

              Registros  Percentual_regra
Data_analise
2025                 48             100.0

Distribuição por mês de transação:

              Registros  Percentual_regra
Data_analise
2025-02               2          4.166667
2025-03               4          8.333333
2025-04               5         10.416667
2025-05               3          6.250000
2025-06               8         16.666667
2025-07               4          8.333333
2025-08               3          6.250000
2025-09               2          4.166667
2025-10               8         16.666667
2025-11               5         10.416667
2025-12               4          8.333333

Exemplos:

,N° do Cadastro (SQL),Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,Base de Cálculo adotada,Razao_transacao_base,Data de Transação,Mes_Arquivo,CEP_8,Matrícula do Imóvel
160877,102005672,275000.00,33,8333.333333,275000.0,1.000000,2025-09-19,SET-2025,01033010,103537
215694,306020701,777600.00,146,5326.027397,777600.0,1.000000,2025-12-09,DEZ-2025,03042010,235341
180542,507633652,200000.00,36,5555.555556,200000.0,1.000000,2025-10-21,OUT-2025,01020000,125340
158220,603004741,48986.94,73,671.053973,324763.0,0.150839,2025-09-16,SET-2025,01314000,81852
92408,704906848,260000.00,34,7647.058824,260000.0,1.000000,2025-06-06,JUN-2025,01220010,114067
204114,704907283,280000.00,36,7777.777778,280000.0,1.000000,2025-11-28,NOV-2025,01220010,114111
129511,707101646,315000.00,51,6176.470588,315000.0,1.000000,2025-08-07,AGO-2025,01045001,100904
16540,707102154,605000.00,102,5931.372549,605000.0,1.000000,2025-02-05,FEV-2025,01045001,100955
109636,707102510,632400.00,102,6200.000000,632400.0,1.000000,2025-07-04,JUL-2025,01045001,100991
96680,707103037,500000.00,51,9803.921569,500000.0,1.000000,2025-06-13,JUN-2025,01045001,101043

R5 — exemplos com a ocorrência preservada e suas cópias exatas:

,N° do Cadastro (SQL),Valor de Transação (declarado pelo contribuinte),Área Construída (m2),Preco_m2,Base de Cálculo adotada,Razao_transacao_base,Data de Transação,Mes_Arquivo,CEP_8,Matrícula do Imóvel
160875,102005672,275000.00,33,8333.333333,275000.0,1.000000,2025-09-19,SET-2025,01033010,103537
160877,102005672,275000.00,33,8333.333333,275000.0,1.000000,2025-09-19,SET-2025,01033010,103537
215692,306020701,777600.00,146,5326.027397,777600.0,1.000000,2025-12-09,DEZ-2025,03042010,235341
215694,306020701,777600.00,146,5326.027397,777600.0,1.000000,2025-12-09,DEZ-2025,03042010,235341
180536,507633652,200000.00,36,5555.555556,200000.0,1.000000,2025-10-21,OUT-2025,01020000,125340
180542,507633652,200000.00,36,5555.555556,200000.0,1.000000,2025-10-21,OUT-2025,01020000,125340
158209,603004741,48986.94,73,671.053973,324763.0,0.150839,2025-09-16,SET-2025,01314000,81852
158220,603004741,48986.94,73,671.053973,324763.0,0.150839,2025-09-16,SET-2025,01314000,81852
92320,704906848,260000.00,34,7647.058824,260000.0,1.000000,2025-06-06,JUN-2025,01220010,114067
92408,704906848,260000.00,34,7647.058824,260000.0,1.000000,2025-06-06,JUN-2025,01220010,114067
204111,704907283,280000.00,36,7777.777778,280000.0,1.000000,2025-11-28,NOV-2025,01220010,114111
204114,704907283,280000.00,36,7777.777778,280000.0,1.000000,2025-11-28,NOV-2025,01220010,114111
129504,707101646,315000.00,51,6176.470588,315000.0,1.000000,2025-08-07,AGO-2025,01045001,100904
129511,707101646,315000.00,51,6176.470588,315000.0,1.000000,2025-08-07,AGO-2025,01045001,100904
16535,707102154,605000.00,102,5931.372549,605000.0,1.000000,2025-02-05,FEV-2025,01045001,100955
16540,707102154,605000.00,102,5931.372549,605000.0,1.000000,2025-02-05,FEV-2025,01045001,100955
109633,707102510,632400.00,102,6200.000000,632400.0,1.000000,2025-07-04,JUL-2025,01045001,100991
109636,707102510,632400.00,102,6200.000000,632400.0,1.000000,2025-07-04,JUL-2025,01045001,100991
96666,707103037,500000.00,51,9803.921569,500000.0,1.000000,2025-06-13,JUN-2025,01045001,101043
96680,707103037,500000.00,51,9803.921569,500000.0,1.000000,2025-06-13,JUN-2025,01045001,101043
96632,707103215,500000.00,51,9803.921569,500000.0,1.000000,2025-06-13,JUN-2025,01045001,101061
96663,707103215,500000.00,51,9803.921569,500000.0,1.000000,2025-06-13,JUN-2025,01045001,101061
37162,707105021,260000.00,34,7647.058824,260000.0,1.000000,2025-03-14,MAR-2025,01045001,113370
37164,707105021,260000.00,34,7647.058824,260000.0,1.000000,2025-03-14,MAR-2025,01045001,113370
168749,707105269,300000.00,30,10000.000000,300000.0,1.000000,2025-10-01,OUT-2025,01045001,113394
168761,707105269,300000.00,30,10000.000000,300000.0,1.000000,2025-10-01,OUT-2025,01045001,113394
96690,707106923,450000.00,34,13235.294118,450000.0,1.000000,2025-06-13,JUN-2025,01045001,113560
96696,707106923,450000.00,34,13235.294118,450000.0,1.000000,2025-06-13,JUN-2025,01045001,113560
96641,707106941,450000.00,33,13636.363636,450000.0,1.000000,2025-06-13,JUN-2025,01045001,113562
96681,707106941,450000.00,33,13636.363636,450000.0,1.000000,2025-06-13,JUN-2025,01045001,113562

### Interpretação individual das regras

- **R1 — preço/m² extremo:** é um sinal econômico forte e útil para revisão. Porém, deriva diretamente do alvo (`Valor de Transação`) e pode representar venda legítima com desconto, leilão, particularidade física não observada ou erro na área. Um corte automático introduziria seleção pelo próprio alvo; por isso, R1 é perigosa quando usada isoladamente.
- **R2 — base fiscal zero:** indica que a coluna fiscal não oferece referência monetária útil naquele registro, mas não prova que a transação declarada seja inválida. Pode refletir procedimento administrativo, decisão judicial, guia complementar ou ausência de valor de referência. R2 isolada é perigosa para exclusão.
- **R3 — razão inferior a 0,2:** evidencia grande divergência entre o valor declarado e a base fiscal adotada. Ainda assim, a base fiscal não é uma segunda observação independente do preço e pode incorporar regras administrativas. R3 deve servir como alerta de coerência, não como fundamento único de remoção.
- **R4 — data fora de 2025:** é uma incompatibilidade com o escopo temporal da base, não necessariamente uma transação anômala. Se o objetivo da V3 for representar transações ocorridas em 2025, R4 é defensável como regra de coorte; os registros continuam legítimos para outros recortes e devem permanecer preservados na fonte.
- **R5 — duplicata exata:** cópias integralmente iguais acrescentam peso artificial sem informação nova. Manter uma ocorrência por grupo é a regra candidata mais segura, desde que a ordem de ingestão usada para escolher a ocorrência preservada seja registrada.

In [63]:
# ============================================================
# R6 — POSSÍVEIS DUPLICATAS POR CHAVES DE NEGÓCIO
# ============================================================

# Visão diagnóstica com apenas uma ocorrência de cada linha exata.
# Isto evita que R5 infle a investigação de R6; df_v2 não é alterado.
base_r6 = df_validacao_regras.loc[~mask_r5].copy()

estrategias_r6 = {
    "K1_CEP_area_valor_data": ["CEP_8", col_area, col_preco, "Data_analise"],
    "K2_SQL_area_valor_data": ["N° do Cadastro (SQL)", col_area, col_preco, "Data_analise"],
    "K3_cartorio_matricula_valor_data": ["Cartório de Registro", "Matrícula do Imóvel", col_preco, "Data_analise"],
    "K4_SQL_cartorio_matricula_valor_data": ["N° do Cadastro (SQL)", "Cartório de Registro", "Matrícula do Imóvel", col_preco, "Data_analise"],
}

resumo_r6 = []
flags_r6 = pd.DataFrame(index=base_r6.index)

for nome, chaves in estrategias_r6.items():
    flag = base_r6.duplicated(subset=chaves, keep=False)
    flags_r6[nome] = flag
    tamanhos = base_r6.groupby(chaves, dropna=False).size()
    grupos = tamanhos[tamanhos.gt(1)]
    resumo_r6.append(
        {
            "Estratégia": nome,
            "Registros_em_grupos": int(flag.sum()),
            "Grupos_candidatos": int(len(grupos)),
            "Excedentes_se_deduplicasse": int((grupos - 1).sum()),
            "Percentual_V2": flag.sum() / len(df_v2) * 100,
        }
    )

resumo_r6 = pd.DataFrame(resumo_r6)
display(resumo_r6)

print("Combinações de estratégias R6 satisfeitas pelos registros candidatos:")
display(
    flags_r6.loc[flags_r6.any(axis=1)]
    .value_counts()
    .rename("Registros")
    .reset_index()
)

colunas_exemplo_r6 = [
    "N° do Cadastro (SQL)",
    "Cartório de Registro",
    "Matrícula do Imóvel",
    "CEP_8",
    col_area,
    col_preco,
    "Data de Transação",
    "Mes_Arquivo",
    "Bairro",
]

for nome, chaves in estrategias_r6.items():
    print(f"Exemplos — {nome}:")
    display(
        base_r6.loc[flags_r6[nome]]
        .sort_values(chaves)[colunas_exemplo_r6]
        .head(16)
    )

print("R6 não foi incorporada a nenhuma máscara de remoção.")

,Estratégia,Registros_em_grupos,Grupos_candidatos,Excedentes_se_deduplicasse,Percentual_V2
0,K1_CEP_area_valor_data,1262,502,760,1.975548
1,K2_SQL_area_valor_data,22,11,11,0.034439
2,K3_cartorio_matricula_valor_data,66,32,34,0.103317
3,K4_SQL_cartorio_matricula_valor_data,22,11,11,0.034439

Combinações de estratégias R6 satisfeitas pelos registros candidatos:

,K1_CEP_area_valor_data,K2_SQL_area_valor_data,K3_cartorio_matricula_valor_data,K4_SQL_cartorio_matricula_valor_data,Registros
0,True,False,False,False,1206
1,True,False,True,False,34
2,True,True,True,True,22
3,False,False,True,False,10

Exemplos — K1_CEP_area_valor_data:

,N° do Cadastro (SQL),Cartório de Registro,Matrícula do Imóvel,CEP_8,Área Construída (m2),Valor de Transação (declarado pelo contribuinte),Data de Transação,Mes_Arquivo,Bairro
155548,502201622,4º Cartório de Registro de Imóvel,87533,01004010,55,157684.81,2025-09-17,SET-2025,NaN
155583,502201665,4º Cartório de Registro de Imóvel,87526,01004010,55,157684.81,2025-09-17,SET-2025,NaN
155592,502201703,4º Cartório de Registro de Imóvel,87537,01004010,55,157684.81,2025-09-17,SET-2025,NaN
155566,502201657,4º Cartório de Registro de Imóvel,87536,01004010,69,199201.45,2025-09-17,SET-2025,NaN
155590,502201691,4º Cartório de Registro de Imóvel,87529,01004010,69,199201.45,2025-09-17,SET-2025,NaN
155560,502201649,4º Cartório de Registro de Imóvel,87535,01004010,77,220525.74,2025-09-17,SET-2025,NaN
155587,502201681,4º Cartório de Registro de Imóvel,87528,01004010,77,220525.74,2025-09-17,SET-2025,NaN
155601,502201721,4º Cartório de Registro de Imóvel,87531,01004010,77,220525.74,2025-09-17,SET-2025,NaN
155554,502201630,4º Cartório de Registro de Imóvel,87534,01004010,89,255921.33,2025-09-17,SET-2025,NaN
155584,502201673,4º Cartório de Registro de Imóvel,87527,01004010,89,255921.33,2025-09-17,SET-2025,NaN
155595,502201711,4º Cartório de Registro de Imóvel,87530,01004010,89,255921.33,2025-09-17,SET-2025,NaN
147809,507633581,1º Cartório de Registro de Imóvel,125333,01020000,36,200000.00,2025-08-29,SET-2025,NaN
147812,507633611,1º Cartório de Registro de Imóvel,125336,01020000,36,200000.00,2025-08-29,SET-2025,NaN
147824,507633598,1º Cartório de Registro de Imóvel,125334,01020000,36,200000.00,2025-08-29,SET-2025,NaN
9962,507633083,1º Cartório de Registro de Imóvel,125283,01020000,36,210000.00,2025-01-22,JAN-2025,NaN
9966,507633091,1º Cartório de Registro de Imóvel,125284,01020000,36,210000.00,2025-01-22,JAN-2025,NaN

Exemplos — K2_SQL_area_valor_data:

,N° do Cadastro (SQL),Cartório de Registro,Matrícula do Imóvel,CEP_8,Área Construída (m2),Valor de Transação (declarado pelo contribuinte),Data de Transação,Mes_Arquivo,Bairro
162569,602200997,5º Cartório de Registro de Imóvel,46457,01050060,38,200000.0,2025-09-09,SET-2025,BELA VISTA
172301,602200997,5º Cartório de Registro de Imóvel,46457,01050060,38,200000.0,2025-09-09,OUT-2025,BELA VISTA
117734,602223441,5º Cartório de Registro de Imóvel,100348,01050060,33,288000.0,2025-07-15,JUL-2025,COND SETIN DOWNTOWN
125834,602223441,5º Cartório de Registro de Imóvel,100348,01050060,33,288000.0,2025-07-15,JUL-2025,COND SETIN DOWNTOWN
129687,706004280,5º Cartório de Registro de Imóvel,67605,01220000,36,190000.0,2025-07-24,AGO-2025,VILA BUARQUE
143299,706004280,5º Cartório de Registro de Imóvel,67605,01220000,36,190000.0,2025-07-24,AGO-2025,VILA BUARQUE
128598,1306105862,13º Cartório de Registro de Imóvel,53154,05414025,155,1030000.0,2025-08-04,AGO-2025,PINHEIROS
184195,1306105862,13º Cartório de Registro de Imóvel,53154,05414025,155,1030000.0,2025-08-04,OUT-2025,PINHEIROS
104748,1306602750,10º Cartório de Registro de Imóvel,14569,05415001,122,1010000.0,2025-06-27,JUN-2025,PINHEIROS
184241,1306602750,10º Cartório de Registro de Imóvel,14569,05415001,122,1010000.0,2025-06-27,OUT-2025,PINHEIROS
70786,1501402455,10º Cartório de Registro de Imóvel,44262,05415011,142,1000000.0,2025-05-07,MAI-2025,PINHEIROS
184228,1501402455,10º Cartório de Registro de Imóvel,44262,05415011,142,1000000.0,2025-05-07,OUT-2025,PINHEIROS
171841,3505901032,6º Cartório de Registro de Imóvel,55536,01549020,163,750000.0,2025-10-03,OUT-2025,VILA MONUMENTO
172253,3505901032,6º Cartório de Registro de Imóvel,55536,01549020,163,750000.0,2025-10-03,OUT-2025,VILA MONUMENTO
95969,4113801029,14º Cartório de Registro de Imóvel,10917,04521901,86,480000.0,2025-06-09,JUN-2025,INDIANOPOLIS
114154,4113801029,14º Cartório de Registro de Imóvel,10917,04521901,86,480000.0,2025-06-09,JUL-2025,INDIANOPOLIS

Exemplos — K3_cartorio_matricula_valor_data:

,N° do Cadastro (SQL),Cartório de Registro,Matrícula do Imóvel,CEP_8,Área Construída (m2),Valor de Transação (declarado pelo contribuinte),Data de Transação,Mes_Arquivo,Bairro
104748,1306602750,10º Cartório de Registro de Imóvel,14569,05415001,122,1010000.0,2025-06-27,JUN-2025,PINHEIROS
184241,1306602750,10º Cartório de Registro de Imóvel,14569,05415001,122,1010000.0,2025-06-27,OUT-2025,PINHEIROS
70786,1501402455,10º Cartório de Registro de Imóvel,44262,05415011,142,1000000.0,2025-05-07,MAI-2025,PINHEIROS
184228,1501402455,10º Cartório de Registro de Imóvel,44262,05415011,142,1000000.0,2025-05-07,OUT-2025,PINHEIROS
135117,5906901906,12º Cartório de Registro de Imóvel,255615,03651120,86,400000.0,2025-08-05,AGO-2025,TORRE 1
179602,5906903781,12º Cartório de Registro de Imóvel,255615,03651120,86,400000.0,2025-08-05,OUT-2025,TORRE 2
128598,1306105862,13º Cartório de Registro de Imóvel,53154,05414025,155,1030000.0,2025-08-04,AGO-2025,PINHEIROS
184195,1306105862,13º Cartório de Registro de Imóvel,53154,05414025,155,1030000.0,2025-08-04,OUT-2025,PINHEIROS
95969,4113801029,14º Cartório de Registro de Imóvel,10917,04521901,86,480000.0,2025-06-09,JUN-2025,INDIANOPOLIS
114154,4113801029,14º Cartório de Registro de Imóvel,10917,04521901,86,480000.0,2025-06-09,JUL-2025,INDIANOPOLIS
151872,4621803931,14º Cartório de Registro de Imóvel,259084,04125210,105,649400.0,2025-09-11,SET-2025,NaN
151876,4621803875,14º Cartório de Registro de Imóvel,259084,04125210,105,649400.0,2025-09-11,SET-2025,NaN
73467,3407701535,16º Cartório de Registro de Imóvel,145975,01536001,124,735000.0,2025-04-30,MAI-2025,IPIRANGA
89952,3407701561,16º Cartório de Registro de Imóvel,145975,01536001,124,735000.0,2025-04-30,JUN-2025,IPIRANGA
13266,7730602814,16º Cartório de Registro de Imóvel,161534,02937040,71,262988.0,2024-12-09,JAN-2025,TORRE 1
98032,7730603799,16º Cartório de Registro de Imóvel,161534,02937040,71,262988.0,2024-12-09,JUN-2025,TORRE 2

Exemplos — K4_SQL_cartorio_matricula_valor_data:

,N° do Cadastro (SQL),Cartório de Registro,Matrícula do Imóvel,CEP_8,Área Construída (m2),Valor de Transação (declarado pelo contribuinte),Data de Transação,Mes_Arquivo,Bairro
162569,602200997,5º Cartório de Registro de Imóvel,46457,01050060,38,200000.0,2025-09-09,SET-2025,BELA VISTA
172301,602200997,5º Cartório de Registro de Imóvel,46457,01050060,38,200000.0,2025-09-09,OUT-2025,BELA VISTA
117734,602223441,5º Cartório de Registro de Imóvel,100348,01050060,33,288000.0,2025-07-15,JUL-2025,COND SETIN DOWNTOWN
125834,602223441,5º Cartório de Registro de Imóvel,100348,01050060,33,288000.0,2025-07-15,JUL-2025,COND SETIN DOWNTOWN
129687,706004280,5º Cartório de Registro de Imóvel,67605,01220000,36,190000.0,2025-07-24,AGO-2025,VILA BUARQUE
143299,706004280,5º Cartório de Registro de Imóvel,67605,01220000,36,190000.0,2025-07-24,AGO-2025,VILA BUARQUE
128598,1306105862,13º Cartório de Registro de Imóvel,53154,05414025,155,1030000.0,2025-08-04,AGO-2025,PINHEIROS
184195,1306105862,13º Cartório de Registro de Imóvel,53154,05414025,155,1030000.0,2025-08-04,OUT-2025,PINHEIROS
104748,1306602750,10º Cartório de Registro de Imóvel,14569,05415001,122,1010000.0,2025-06-27,JUN-2025,PINHEIROS
184241,1306602750,10º Cartório de Registro de Imóvel,14569,05415001,122,1010000.0,2025-06-27,OUT-2025,PINHEIROS
70786,1501402455,10º Cartório de Registro de Imóvel,44262,05415011,142,1000000.0,2025-05-07,MAI-2025,PINHEIROS
184228,1501402455,10º Cartório de Registro de Imóvel,44262,05415011,142,1000000.0,2025-05-07,OUT-2025,PINHEIROS
171841,3505901032,6º Cartório de Registro de Imóvel,55536,01549020,163,750000.0,2025-10-03,OUT-2025,VILA MONUMENTO
172253,3505901032,6º Cartório de Registro de Imóvel,55536,01549020,163,750000.0,2025-10-03,OUT-2025,VILA MONUMENTO
95969,4113801029,14º Cartório de Registro de Imóvel,10917,04521901,86,480000.0,2025-06-09,JUN-2025,INDIANOPOLIS
114154,4113801029,14º Cartório de Registro de Imóvel,10917,04521901,86,480000.0,2025-06-09,JUL-2025,INDIANOPOLIS

R6 não foi incorporada a nenhuma máscara de remoção.

### Leitura de R6

As chaves têm forças diferentes. `CEP + área + valor + data` é deliberadamente ampla e pode reunir unidades distintas do mesmo empreendimento vendidas nas mesmas condições. `SQL` é mais discriminante, enquanto `cartório + matrícula` se aproxima mais da identidade registral do imóvel. Mesmo as chaves fortes não identificam, por si sós, qual linha deveria ser descartada e podem representar guias complementares ou eventos administrativos distintos.

Por isso, os números de “excedentes se deduplicasse” são apenas uma medida de impacto potencial. R6 não deve remover registros até existir uma chave transacional estável ou uma verificação adicional de campos administrativos que diferenciem as ocorrências.

In [64]:
# ============================================================
# SOBREPOSIÇÃO ENTRE R1–R5
# ============================================================

matriz_sobreposicao = mascaras_regras.astype("int64").T.dot(
    mascaras_regras.astype("int64")
)
print("Matriz de interseção — diagonal = total da regra; fora da diagonal = interseção do par:")
display(matriz_sobreposicao)

print(f"R1 também em R3: {(mask_r1 & mask_r3).sum():,}")
print(f"R1 também em R2: {(mask_r1 & mask_r2).sum():,}")

uniao_regras = mascaras_regras.any(axis=1)
quantidade_regras_por_registro = mascaras_regras.sum(axis=1)

interpretacoes_regras = {
    "R1": "Sinal econômico forte, mas deriva do alvo; perigosa isoladamente.",
    "R2": "Base fiscal ausente em substância; não invalida a venda por si só.",
    "R3": "Divergência fiscal elevada; usar como alerta, não como prova.",
    "R4": "Regra de escopo temporal, não de qualidade intrínseca.",
    "R5": "Cópia integral redundante; manter uma ocorrência.",
}

linhas_resumo = []
for regra in mascaras_regras.columns:
    mascara = mascaras_regras[regra]
    exclusivos = mascara & quantidade_regras_por_registro.eq(1)
    sobreposicao = mascara & quantidade_regras_por_registro.gt(1)
    linhas_resumo.append(
        {
            "Regra": regra,
            "Registros": int(mascara.sum()),
            "% V2": mascara.mean() * 100,
            "Exclusivos": int(exclusivos.sum()),
            "Sobreposição": int(sobreposicao.sum()),
            "Interpretação": interpretacoes_regras[regra],
        }
    )

resumo_regras_v3 = pd.DataFrame(linhas_resumo)
display(resumo_regras_v3)

print("Combinações observadas entre as regras, excluindo quem não satisfaz nenhuma:")
display(
    mascaras_regras.loc[uniao_regras]
    .value_counts()
    .rename("Registros")
    .reset_index()
)

print("Os exclusivos são a contribuição marginal de cada regra à união completa, sem depender de ordem.")

Matriz de interseção — diagonal = total da regra; fora da diagonal = interseção do par:

     R1  R2   R3   R4  R5
R1  205  14  154   11   1
R2   14  14    0    1   0
R3  154   0  345    6   3
R4   11   1    6  669   0
R5    1   0    3    0  48

R1 também em R3: 154
R1 também em R2: 14

,Regra,Registros,% V2,Exclusivos,Sobreposição,Interpretação
0,R1,205,0.320909,32,173,"Sinal econômico forte, mas deriva do alvo; per..."
1,R2,14,0.021916,0,14,Base fiscal ausente em substância; não invalid...
2,R3,345,0.540067,188,157,"Divergência fiscal elevada; usar como alerta, ..."
3,R4,669,1.047260,657,12,"Regra de escopo temporal, não de qualidade int..."
4,R5,48,0.075140,45,3,Cópia integral redundante; manter uma ocorrência.

Combinações observadas entre as regras, excluindo quem não satisfaz nenhuma:

       R1     R2     R3     R4     R5  Registros
0   False  False  False   True  False        657
1   False  False   True  False  False        188
2    True  False   True  False  False        148
3   False  False  False  False   True         45
4    True  False  False  False  False         32
5    True   True  False  False  False         13
6    True  False   True   True  False          5
7    True  False  False   True  False          5
8   False  False   True  False   True          2
9    True   True  False   True  False          1
10  False  False   True   True  False          1
11   True  False   True  False   True          1

Os exclusivos são a contribuição marginal de cada regra à união completa, sem depender de ordem.

In [65]:
# ============================================================
# IMPACTO HIPOTÉTICO DA UNIÃO — SEM CRIAR OU FILTRAR A V3
# ============================================================

n_v2_atual = len(df_v2)
n_candidatos_uniao = int(uniao_regras.sum())
n_pos_uniao_hipotetico = n_v2_atual - n_candidatos_uniao

impacto_hipotetico = pd.DataFrame(
    {
        "Métrica": [
            "V2 atual",
            "Registros candidatos à remoção pela união R1 | R2 | R3 | R4 | R5",
            "V3 hipotética (somente contagem)",
            "Percentual total preservado desde V1",
            "Percentual total preservado desde a base original de apartamentos",
        ],
        "Valor": [
            n_v2_atual,
            n_candidatos_uniao,
            n_pos_uniao_hipotetico,
            n_pos_uniao_hipotetico / len(df_v1) * 100,
            n_pos_uniao_hipotetico / len(df_apartamentos) * 100,
        ],
    }
)
display(impacto_hipotetico)

print("Nenhum registro foi removido e nenhum objeto df_v3 foi criado.")

                                             Métrica         Valor
0                                           V2 atual  63881.000000
1  Registros candidatos à remoção pela união R1 |...   1098.000000
2                   V3 hipotética (somente contagem)  62783.000000
3               Percentual total preservado desde V1     96.662099
4  Percentual total preservado desde a base origi...     79.363655

Nenhum registro foi removido e nenhum objeto df_v3 foi criado.

### Recomendação metodológica antes da V3

A soma simples de R1–R5 seria 1.281, mas a união correta contém **1.098 registros**. Se todas as regras fossem aplicadas, restariam hipoteticamente 62.783 registros: 96,66% da V1 e 79,36% da base original de apartamentos. Essa união integral **não é recomendada**.

A evidência atual sustenta a seguinte decisão:

1. **R5 deve compor a V3**, removendo apenas as 48 cópias excedentes e preservando uma ocorrência de cada linha exata. É a regra com menor risco de eliminar informação real.
2. **R4 deve compor a V3 somente se a população-alvo for definida por `Data de Transação` em 2025.** Nesse caso, seus 669 registros são excluídos por escopo, não por serem inválidos. Como R4 e R5 não se sobrepõem, a aplicação somente dessas duas regras deixaria 63.164 registros, preservando 97,25% da V1 e 79,85% da base original de apartamentos. Se o objetivo for estudar guias pagas em 2025 independentemente da data da transação, R4 não deve ser aplicada.
3. **R1, R2 e R3 não devem compor a V3 como regras isoladas.** R1 deriva do próprio alvo e pode apagar vendas legítimas da cauda inferior. R2 não acrescenta nenhum registro exclusivo: seus 14 casos já pertencem a R1. R3 acrescenta 188 casos exclusivos e usa uma base fiscal que coincide com o próprio valor declarado em 79,86% da V2, portanto não funciona como validação independente do preço.
4. A interseção **`R1 & (R2 | R3)` reúne 168 registros** e é mais defensável como fila de revisão ou quarentena do que qualquer uma das três regras isoladas, pois combina preço/m² extremo com um segundo sinal fiscal. Ainda assim, não deve virar remoção automática antes de validar amostras na fonte e entender os casos de base zero.
5. **R6 não deve compor a V3 neste momento.** A chave ampla `CEP + área + valor + data` reuniu 1.262 registros e captura claramente vendas distintas de unidades semelhantes. As chaves mais fortes `SQL + área + valor + data` e `SQL + cartório + matrícula + valor + data` apontaram somente 22 registros em 11 grupos, mas ainda podem representar republicações ou eventos administrativos legítimos; falta uma chave única da guia/transação para decidir qual ocorrência seria redundante.

As regras mais perigosas para transações legítimas são **R1 e R3**, seguidas por R2. R4 também remove transações legítimas, mas de forma transparente por definição de coorte. A recomendação operacional, antes de criar a V3, é confirmar formalmente se o recorte temporal desejado é a data da transação; com essa confirmação, aplicar apenas `R4 | R5` e manter R1–R3 e R6 como flags auditáveis.

## BASE V3 - CRIAÇÃO E VALIDAÇÃO FORMAL

A V3 parte exclusivamente de `df_v2` e aplica somente estas regras, nesta ordem:

1. **Coorte temporal:** manter apenas registros cuja `Data de Transação` pertence ao ano de 2025. O motivo é definir a população temporal do estudo; registros de outros anos ficam fora do escopo, sem serem classificados como inválidos.
2. **Duplicatas exatas:** depois do recorte temporal, remover somente cópias excedentes de linhas iguais em todas as colunas da V2. A primeira ocorrência na ordem original da V2 é preservada deterministicamente, pois as demais não acrescentam informação.

`Preco_m2` baixo, `Base de Cálculo adotada == 0` e a razão entre valor de transação e base de cálculo não são regras de exclusão. Os casos anteriormente considerados suspeitos por `Preco_m2 < 2.000` permanecem identificados para auditoria. `df_v1` e `df_v2` são preservados, não há treinamento de modelo, análise da cauda superior ou criação de V4 nesta etapa.

In [66]:
# ============================================================
# PRÉ-VALIDAÇÃO DAS DUAS REGRAS DA V3
# ============================================================

registros_esperados_v3 = 63_164

n_v1_antes_v3 = len(df_v1)
n_v2_antes_v3 = len(df_v2)
colunas_v1_antes_v3 = df_v1.columns.tolist()
colunas_v2_antes_v3 = df_v2.columns.tolist()
hash_v1_antes_v3 = pd.util.hash_pandas_object(df_v1, index=True)
hash_v2_antes_v3 = pd.util.hash_pandas_object(df_v2, index=True)

base_v3_trabalho = df_v2.copy()
base_v3_trabalho["_Ordem_original_V2"] = np.arange(
    len(base_v3_trabalho),
    dtype="int64",
)
datas_v3_trabalho = pd.to_datetime(
    base_v3_trabalho["Data de Transação"],
    errors="coerce",
)

# Regra 1: o ano da data da transação define a coorte de 2025.
mask_data_2025 = datas_v3_trabalho.dt.year.eq(2025)
n_removidos_data_fora_2025 = int((~mask_data_2025).sum())
base_v3_2025 = base_v3_trabalho.loc[mask_data_2025].copy()

# Regra 2: todas as colunas da V2 devem ser iguais para caracterizar cópia exata.
base_v3_2025 = base_v3_2025.sort_values("_Ordem_original_V2", kind="mergesort")
mask_duplicata_exata_excedente = base_v3_2025.duplicated(
    subset=colunas_v2_antes_v3,
    keep="first",
)
n_removidos_duplicata_exata = int(mask_duplicata_exata_excedente.sum())
n_v3_prevalidacao = len(base_v3_2025) - n_removidos_duplicata_exata

validacao_previa_v3 = pd.DataFrame(
    {
        "Etapa": [
            "V2 inicial",
            "Após manter somente datas de 2025",
            "Cópias exatas excedentes a remover",
            "V3 projetada",
        ],
        "Registros": [
            len(df_v2),
            len(base_v3_2025),
            n_removidos_duplicata_exata,
            n_v3_prevalidacao,
        ],
    }
)
display(validacao_previa_v3)

if n_v3_prevalidacao != registros_esperados_v3:
    raise RuntimeError(
        "A pré-validação não resultou em 63.164 registros. "
        "Interrompa a criação da V3 e investigue a diferença sem alterar os filtros."
    )

                                Etapa  Registros
0                          V2 inicial      63881
1   Após manter somente datas de 2025      63212
2  Cópias exatas excedentes a remover         48
3                        V3 projetada      63164

In [67]:
# ============================================================
# CRIAÇÃO DA V3 APÓS A PRÉ-VALIDAÇÃO
# ============================================================

indices_removidos_duplicata_exata = base_v3_2025.index[
    mask_duplicata_exata_excedente
]

df_v3 = (
    base_v3_2025.loc[~mask_duplicata_exata_excedente]
    .sort_values("_Ordem_original_V2", kind="mergesort")
    .drop(columns="_Ordem_original_V2")
    .copy()
)

assert len(df_v3) == registros_esperados_v3
assert len(df_v1) == n_v1_antes_v3
assert len(df_v2) == n_v2_antes_v3
assert df_v1.columns.tolist() == colunas_v1_antes_v3
assert df_v2.columns.tolist() == colunas_v2_antes_v3
assert pd.util.hash_pandas_object(df_v1, index=True).equals(hash_v1_antes_v3)
assert pd.util.hash_pandas_object(df_v2, index=True).equals(hash_v2_antes_v3)

In [68]:
# ============================================================
# AUDITORIA DOS REGISTROS COM PREÇO/M² BAIXO, SEM EXCLUSÃO
# ============================================================

# O mesmo limiar já usado na investigação da V2 apenas identifica os casos.
limite_auditoria_preco_m2 = 2_000
mask_auditoria_preco_m2_v2 = df_v2["Preco_m2"].lt(
    limite_auditoria_preco_m2
)
indices_auditoria_preco_m2 = df_v2.index[mask_auditoria_preco_m2_v2]

df_auditoria_preco_m2_baixo = df_v2.loc[
    mask_auditoria_preco_m2_v2
].copy()
df_auditoria_preco_m2_baixo["Presente_na_V3"] = (
    df_auditoria_preco_m2_baixo.index.isin(df_v3.index)
)
df_auditoria_preco_m2_baixo["Fora_da_coorte_2025"] = (
    pd.to_datetime(
        df_auditoria_preco_m2_baixo["Data de Transação"],
        errors="coerce",
    ).dt.year.ne(2025)
)
df_auditoria_preco_m2_baixo["Copia_exata_excedente"] = (
    df_auditoria_preco_m2_baixo.index.isin(indices_removidos_duplicata_exata)
)

df_v3["Flag_auditoria_preco_m2_baixo"] = df_v3.index.isin(
    indices_auditoria_preco_m2
)

assert len(df_auditoria_preco_m2_baixo) == len(df_baixo_m2) == 2_734
assert int(df_v3["Flag_auditoria_preco_m2_baixo"].sum()) == 2_658

In [69]:
# ============================================================
# RELATÓRIO FINAL DE VALIDAÇÃO DA V3
# ============================================================

datas_v3 = pd.to_datetime(df_v3["Data de Transação"], errors="coerce")
todas_datas_v3_em_2025 = bool(
    datas_v3.notna().all() and datas_v3.dt.year.eq(2025).all()
)
duplicatas_exatas_excedentes_v3 = int(
    df_v3.duplicated(subset=colunas_v2_antes_v3, keep="first").sum()
)
percentual_v1_preservado_v3 = len(df_v3) / len(df_v1) * 100

relatorio_v3 = pd.DataFrame(
    {
        "Métrica": [
            "Quantidade de registros da V1",
            "Quantidade de registros da V2",
            "Quantidade de registros da V3",
            "Quantidade removida por data fora de 2025",
            "Quantidade removida como duplicata exata",
            "Todas as datas da V3 pertencem a 2025",
            "Não existem duplicatas exatas excedentes",
            "Percentual da V1 preservado na V3",
        ],
        "Resultado": [
            len(df_v1),
            len(df_v2),
            len(df_v3),
            n_removidos_data_fora_2025,
            n_removidos_duplicata_exata,
            todas_datas_v3_em_2025,
            duplicatas_exatas_excedentes_v3 == 0,
            percentual_v1_preservado_v3,
        ],
    }
)
display(relatorio_v3)

estatisticas_v3 = df_v3[[col_preco, col_area, "Preco_m2"]].describe().T
estatisticas_v3.columns = [
    "Contagem",
    "Média",
    "Desvio padrão",
    "Mínimo",
    "25%",
    "Mediana",
    "75%",
    "Máximo",
]
display(estatisticas_v3)

assert todas_datas_v3_em_2025
assert duplicatas_exatas_excedentes_v3 == 0
assert len(df_v1) == n_v1_antes_v3
assert len(df_v2) == n_v2_antes_v3
assert pd.util.hash_pandas_object(df_v1, index=True).equals(hash_v1_antes_v3)
assert pd.util.hash_pandas_object(df_v2, index=True).equals(hash_v2_antes_v3)

                                     Métrica  Resultado
0              Quantidade de registros da V1      64951
1              Quantidade de registros da V2      63881
2              Quantidade de registros da V3      63164
3  Quantidade removida por data fora de 2025        669
4   Quantidade removida como duplicata exata         48
5      Todas as datas da V3 pertencem a 2025       True
6   Não existem duplicatas exatas excedentes       True
7          Percentual da V1 preservado na V3  97.248695

,Contagem,Média,Desvio padrão,Mínimo,25%,Mediana,75%,Máximo
Valor de Transação (declarado pelo contribuinte),63164.0,756163.287415,1.354585e+06,10000.000000,290680.862500,448000.000000,795007.12500,7.000000e+07
Área Construída (m2),63164.0,126.898756,9.802349e+01,6.000000,71.000000,102.000000,148.00000,2.023000e+03
Preco_m2,63164.0,5457.724522,3.019584e+03,25.763359,3567.567568,4900.900932,6645.56962,5.686434e+04

## RESULTADO DA ETAPA — ÁREA E LOCALIZAÇÃO

Diagnóstico exclusivamente sobre a Base V3 validada. Os limiares usados abaixo servem para localizar casos a revisar; nenhum registro é removido, e `df_v1`, `df_v2` e `df_v3` permanecem intactos. `CEP_8` e `Bairro_normalizado` existem apenas em `df_area_localizacao`, uma cópia de diagnóstico.

In [70]:
# Conferência da base antes do diagnóstico e cópia isolada das colunas necessárias.
import re
import unicodedata

assert len(df_v3) == 63_164
assert pd.to_datetime(df_v3["Data de Transação"], errors="coerce").dt.year.eq(2025).all()
assert not df_v3.duplicated(subset=colunas_v2_antes_v3).any()

hashes_bases_antes_area_localizacao = {
    nome: pd.util.hash_pandas_object(base, index=True)
    for nome, base in (("df_v1", df_v1), ("df_v2", df_v2), ("df_v3", df_v3))
}
df_area_localizacao = df_v3[[col_area, col_preco, "Preco_m2", "CEP", "Bairro", "Nome do Logradouro", "Número"]].copy()
print(f"Base V3 validada: {len(df_area_localizacao):,} apartamentos.")

Base V3 validada: 63,164 apartamentos.

In [71]:
# área: distribuição, repetição, extremos e relação com valor/preço por m².
area = pd.to_numeric(df_area_localizacao[col_area], errors="coerce")
preco = pd.to_numeric(df_area_localizacao[col_preco], errors="coerce")
pm2 = pd.to_numeric(df_area_localizacao["Preco_m2"], errors="coerce")
print("área ausente:", int(area.isna().sum()), "| área <= 0:", int(area.le(0).sum()))
print("área não numérica não vazia:", int((area.isna() & df_area_localizacao[col_area].notna()).sum()))
print("Distribuição da área (m²):")
display(area.describe(percentiles=[.01,.05,.10,.25,.50,.75,.90,.95,.99,.995,.999]).to_frame("área_m2"))
print("Limiar exploratório: <20 m², <30 m², >500 m², >1000 m²:", *(int(x) for x in (area.lt(20).sum(),area.lt(30).sum(),area.gt(500).sum(),area.gt(1000).sum())))
print("áreas distintas:",area.nunique(),"| valores repetidos:",int(area.value_counts().gt(1).sum()))
print("áreas mais frequentes:")
display(area.value_counts().head(12).to_frame("Imóveis"))
print("Menores áreas (amostra):")
display(df_area_localizacao.loc[area.nsmallest(8).index,[col_area,col_preco,"Preco_m2","CEP","Bairro"]])
print("Maiores áreas (amostra):")
display(df_area_localizacao.loc[area.nlargest(8).index,[col_area,col_preco,"Preco_m2","CEP","Bairro"]])
print("Correlação com área (Pearson / Spearman):")
display(pd.DataFrame({"Pearson":{"Valor de Transação":area.corr(preco),"Preco_m2":area.corr(pm2)},"Spearman":{"Valor de Transação":area.corr(preco,method="spearman"),"Preco_m2":area.corr(pm2,method="spearman")}}))
faixas_area = pd.cut(area,[-float("inf"),20,30,50,75,100,150,250,500,float("inf")])
resumo_faixas_area = df_area_localizacao.groupby(faixas_area,observed=True).agg(
    Imoveis=(col_area,"size"), Valor_mediano=(col_preco,"median"), Preco_m2_mediano=("Preco_m2","median")
)
print("Valor e preço/m² por faixa de área:")
display(resumo_faixas_area)

área ausente: 0 | área <= 0: 0
área não numérica não vazia: 0
Distribuição da área (m²):
            área_m2
count  63164.000000
mean     126.898756
std       98.023490
min        6.000000
1%        32.000000
5%        39.000000
10%       46.000000
25%       71.000000
50%      102.000000
75%      148.000000
90%      230.000000
95%      305.000000
99%      523.370000
99.5%    629.000000
99.9%    879.511000
max     2023.000000
Limiar exploratório: <20 m², <30 m², >500 m², >1000 m²: 24 243 723 42
áreas distintas: 769 | valores repetidos: 647
áreas mais frequentes:
                      Imóveis
Área Construída (m2)
49                        805
37                        768
88                        685
89                        620
93                        597
96                        583
40                        564
81                        563
90                        562
92                        561
94                        560
80                        559
Menores áreas (amostra):
        Área Construída (m2)  Valor de Transação (declarado pelo contribuinte)     Preco_m2        CEP                Bairro
123929                     6                                           32500.0  5416.666667  5586060.0                   NaN
23561                      7                                           10000.0  1428.571429  5717240.0  COND RES SOUTH POINT
23590                      7                                           10000.0  1428.571429  5717240.0  COND RES SOUTH POINT
44626                      7                                           30000.0  4285.714286  5541030.0                  2 SS
72020                      7                                           10000.0  1428.571429  5717240.0  COND RES SOUTH POINT
159563                     7                                           10000.0  1428.571429  2402200.0                   NaN
205357                     7                                           15286.0  2183.714286  5541030.0                   2SS
11908                      8                                           50000.0  6250.000000  4362060.0                   NaN
Maiores áreas (amostra):
        Área Construída (m2)  Valor de Transação (declarado pelo contribuinte)      Preco_m2        CEP                Bairro
206459                  2023                                        10519608.5   5200.004202  5692140.0       01 DEP E 12 VGS
34762                   1544                                         9500000.0   6152.849741  5657230.0  JARDIM VITORIA REGIA
99826                   1491                                        47000000.0  31522.468142  1454010.0                 E 2DP
199535                  1491                                        57500000.0  38564.721663  1454010.0                 E 2DP
180199                  1490                                        50000000.0  33557.046980  4542012.0               TRIPLEX
27913                   1451                                        64765000.0  44634.734666  1454030.0                   NaN
31733                   1433                                        59700000.0  41660.851361  1454030.0                   NaN
169800                  1426                                        24610000.0  17258.064516  4538901.0           JD PAULISTA
Correlação com área (Pearson / Spearman):
                     Pearson  Spearman
Valor de Transação  0.705200  0.766939
Preco_m2            0.214824  0.025557
Valor e preço/m² por faixa de área:
                      Imoveis  Valor_mediano  Preco_m2_mediano
Área Construída (m2)
(-inf, 20.0]               27       50000.00       4000.000000
(20.0, 30.0]              291      215000.00       7857.142857
(30.0, 50.0]             8041      261499.37       6410.256410
(50.0, 75.0]             9456      288000.00       4590.577752
(75.0, 100.0]           13102      360000.00       4117.647059
(100.0, 150.0]          16913      540000.00       4537.815126
(150.0, 250.0]          10189     1027163.02       5559.210526
(250.0, 500.0]           4422     1950000.00       6295.708469
(500.0, inf]              723     4845000.00       7705.479452

`Preco_m2` é calculado a partir de valor dividido por área. Portanto, sua associação com área é parcialmente mecânica; os casos extremos exigem conferência documental antes de qualquer regra de tratamento.

In [72]:
# CEP_8: texto de oito algarismos; entradas inválidas ficam ausentes no diagnóstico.
def normalizar_cep(valor):
    if pd.isna(valor):
        return pd.NA
    if isinstance(valor, (int, np.integer)):
        digitos = str(valor)
    elif isinstance(valor, (float, np.floating)):
        if not np.isfinite(valor) or not valor.is_integer():
            return pd.NA
        digitos = str(int(valor))
    else:
        texto = str(valor).strip()
        if re.fullmatch(r"[0-9]{5}-[0-9]{3}", texto):
            texto = texto.replace("-", "")
        if not re.fullmatch(r"[0-9]{7,8}", texto):
            return pd.NA
        digitos = texto
    if not re.fullmatch(r"[0-9]{7,8}", digitos):
        return pd.NA
    return digitos.zfill(8)

assert normalizar_cep(1234567) == "01234567"
assert normalizar_cep("01234-567") == "01234567"
assert pd.isna(normalizar_cep("123"))
assert pd.isna(normalizar_cep("12A34567"))

cep_bruto_ausente = df_area_localizacao["CEP"].isna() | df_area_localizacao["CEP"].astype("string").str.strip().eq("").fillna(False)
df_area_localizacao["CEP_8"] = pd.Series(
    [normalizar_cep(x) for x in df_area_localizacao["CEP"]],
    index=df_area_localizacao.index, dtype="string"
)
cep_invalido = ~cep_bruto_ausente & df_area_localizacao["CEP_8"].isna()
assert df_area_localizacao["CEP_8"].dropna().str.fullmatch(r"[0-9]{8}").all()
contagem_cep = df_area_localizacao["CEP_8"].value_counts()
print("CEP bruto ausente:",int(cep_bruto_ausente.sum()),"| bruto inválido:",int(cep_invalido.sum()))
print("CEP_8 válido:",int(df_area_localizacao["CEP_8"].notna().sum()),"| CEPs únicos:",len(contagem_cep))
print("Imóveis/CEP: distribuição:")
display(contagem_cep.describe(percentiles=[.25,.50,.75,.90,.95,.99]).to_frame("Imóveis_por_CEP"))
print("CEPs com 1, <5 e >=100 imóveis:",int(contagem_cep.eq(1).sum()),int(contagem_cep.lt(5).sum()),int(contagem_cep.ge(100).sum()))
print("Imóveis nos CEPs com <5 e >=100 registros:",int(contagem_cep[contagem_cep.lt(5)].sum()),int(contagem_cep[contagem_cep.ge(100)].sum()))
print("CEPs mais frequentes:")
display(contagem_cep.head(12).to_frame("Imóveis"))
print("Exemplos de CEP bruto inválido:")
display(df_area_localizacao.loc[cep_invalido,["CEP","Bairro"]].head(12))

CEP bruto ausente: 0 | bruto inválido: 0
CEP_8 válido: 63164 | CEPs únicos: 7533
Imóveis/CEP: distribuição:
       Imóveis_por_CEP
count           7533.0
mean          8.384973
std          12.232586
min                1.0
25%                2.0
50%                4.0
75%               10.0
90%               19.0
95%               29.0
99%              60.68
max              200.0
CEPs com 1, <5 e >=100 imóveis: 1486 3888 15
Imóveis nos CEPs com <5 e >=100 registros: 8195 1920
CEPs mais frequentes:
          Imóveis
CEP_8
05144085      200
04546043      170
04709011      136
04546002      132
01032000      130
04102002      126
04729080      124
03511000      123
04582030      119
05093000      117
01136000      116
05145901      114
Exemplos de CEP bruto inválido:
Empty DataFrame
Columns: [CEP, Bairro]
Index: []

In [73]:
# Bairro: normalização só para comparar grafias; original preservado.
def normalizar_bairro(valor):
    if pd.isna(valor):
        return pd.NA
    texto = re.sub(r"\s+", " ", str(valor).strip())
    if not texto:
        return pd.NA
    texto = "".join(c for c in unicodedata.normalize("NFKD",texto) if not unicodedata.combining(c))
    return texto.upper()

bairro_bruto = df_area_localizacao["Bairro"].astype("string")
bairro_ausente = bairro_bruto.isna() | bairro_bruto.str.strip().eq("").fillna(False)
df_area_localizacao["Bairro_normalizado"] = pd.Series(
    [normalizar_bairro(x) for x in df_area_localizacao["Bairro"]],
    index=df_area_localizacao.index,dtype="string"
)
bairro_valido = bairro_bruto[~bairro_ausente]
bairro_espacos = bairro_valido.ne(bairro_valido.str.strip()) | bairro_valido.str.contains(r"\s{2,}")
bairro_caixa = bairro_valido.ne(bairro_valido.str.upper())
bairro_acento = bairro_valido.map(lambda x: any(unicodedata.combining(c) for c in unicodedata.normalize("NFKD",x)))
variantes_bairro = (df_area_localizacao.dropna(subset=["Bairro_normalizado"])
    .groupby("Bairro_normalizado")["Bairro"].agg(lambda s: sorted(set(s.astype(str)))))
variantes_bairro = variantes_bairro[variantes_bairro.map(len).gt(1)]
genericos = {"NAO INFORMADO","NAO IDENTIFICADO","DESCONHECIDO","SEM INFORMACAO","SEM BAIRRO","BAIRRO","OUTROS","OUTRO","INDEFINIDO","N/A","NA","-","0"}
bairro_generico = df_area_localizacao["Bairro_normalizado"].isin(genericos)
print("Bairro ausente/vazio:",int(bairro_ausente.sum()),"| únicos brutos:",bairro_valido.nunique(),"| únicos normalizados:",df_area_localizacao["Bairro_normalizado"].nunique())
print("Registros com variação de caixa, espaços extras e acentos:",int(bairro_caixa.sum()),int(bairro_espacos.sum()),int(bairro_acento.sum()))
print("Chaves normalizadas com mais de uma grafia:",len(variantes_bairro))
print("Exemplos de variantes:")
display(variantes_bairro.head(15).to_frame("Grafias originais"))
print("Valores genéricos explícitos:",int(bairro_generico.sum()))
print("Bairros mais frequentes:")
display(df_area_localizacao["Bairro_normalizado"].value_counts().head(15).to_frame("Imóveis"))
print("Valores curtos ou aparentemente genéricos:")
display(df_area_localizacao.loc[df_area_localizacao["Bairro_normalizado"].str.len().lt(4).fillna(False) | bairro_generico,"Bairro"].value_counts().head(20).to_frame("Imóveis"))

Bairro ausente/vazio: 23207 | únicos brutos: 5345 | únicos normalizados: 5292
Registros com variação de caixa, espaços extras e acentos: 0 932 0
Chaves normalizadas com mais de uma grafia: 49
Exemplos de variantes:
                                                   Grafias originais
Bairro_normalizado
AGUA BRANCA                              [AGUA  BRANCA, AGUA BRANCA]
BL 2 VG                                        [BL 2   VG, BL 2  VG]
BL 4 ESPORTE E VIDA  [BL  4   ESPORTE E VIDA, BL  4  ESPORTE E VIDA]
BL A                                                   [BL  A, BL A]
BLOCO 01                                       [BLOCO  01, BLOCO 01]
BLOCO 02                                       [BLOCO  02, BLOCO 02]
BLOCO 1                                          [BLOCO  1, BLOCO 1]
BLOCO 2                                          [BLOCO  2, BLOCO 2]
BLOCO 3                                          [BLOCO  3, BLOCO 3]
BLOCO 4                                          [BLOCO  4, BLOCO 4]
BLOCO 7 EDIFICIO              [BLOCO  7  EDIFICIO, BLOCO 7 EDIFICIO]
BLOCO A                                          [BLOCO  A, BLOCO A]
BLOCO B                               [BLOCO   B, BLOCO  B, BLOCO B]
BLOCO E                              [BLOCO    E, BLOCO  E, BLOCO E]
BLOCO G                                          [BLOCO  G, BLOCO G]
Valores genéricos explícitos: 13
Bairros mais frequentes:
                    Imóveis
Bairro_normalizado
TORRE 1                1137
TORRE B                 937
TORRE A                 936
TORRE 2                 804
BLOCO B                 655
BLOCO A                 580
PERDIZES                541
SAUDE                   501
TATUAPE                 492
TORRE 3                 406
SANTANA                 394
BELA VISTA              392
VILA MARIANA            373
CERQUEIRA CESAR         339
PINHEIROS               336
Valores curtos ou aparentemente genéricos:
        Imóveis
Bairro
B           103
A           101
LUZ          30
DEP          22
T1           18
ED.          13
T2           11
CD.          10
-            10
.             9
VG            9
SE            9
224           9
C             7
M             6
E             5
2             5
YOU           5
N             5
IPE           4

In [74]:
# CEP x Bairro: ambiguidade, concentração e casos para revisão manual.
pares_geo = df_area_localizacao.dropna(subset=["CEP_8","Bairro_normalizado"])
contagem_pares = pares_geo.groupby(["CEP_8","Bairro_normalizado"]).size().rename("Imóveis")
bairros_por_cep = pares_geo.groupby("CEP_8")["Bairro_normalizado"].nunique()
ceps_por_bairro = pares_geo.groupby("Bairro_normalizado")["CEP_8"].nunique()
conflito_cep = bairros_por_cep[bairros_por_cep.gt(1)]
varios_ceps = ceps_por_bairro[ceps_por_bairro.gt(1)]
total_cep = pares_geo.groupby("CEP_8").size()
maior_bairro_cep = contagem_pares.groupby(level=0).max()
minoria_cep = (total_cep-maior_bairro_cep).loc[conflito_cep.index]
print("Registros com CEP e Bairro preenchidos:",len(pares_geo))
print("CEPs ligados a >1 Bairro:",len(conflito_cep),"de",len(bairros_por_cep),"| imóveis no bairro minoritário:",int(minoria_cep.sum()))
print("Bairros ligados a >1 CEP:",len(varios_ceps),"de",len(ceps_por_bairro))
print("CEPs com mais bairros distintos:")
display(pd.DataFrame({"Bairros":bairros_por_cep,"Imóveis":total_cep,"Minoria":total_cep-maior_bairro_cep}).sort_values(["Bairros","Imóveis"],ascending=False).head(15))
print("Bairros com mais CEPs:")
display(pd.DataFrame({"CEPs":ceps_por_bairro,"Imóveis":pares_geo.groupby("Bairro_normalizado").size()}).sort_values(["CEPs","Imóveis"],ascending=False).head(15))
print("Pares de CEP e bairro nos CEPs com mais registros minoritários:")
ceps_revisao = minoria_cep.sort_values(ascending=False).head(10).index
display(contagem_pares.loc[ceps_revisao].groupby(level=0).head(5).to_frame())
chave_rua = pares_geo["Nome do Logradouro"].map(normalizar_bairro).astype("string")
pares_rua = pares_geo.assign(_Rua_diagnostico=chave_rua).dropna(subset=["_Rua_diagnostico"])
ruas_ambiguas = pares_rua.groupby(["CEP_8","_Rua_diagnostico"])["Bairro_normalizado"].nunique()
ruas_ambiguas = ruas_ambiguas[ruas_ambiguas.gt(1)]
print("Pares CEP + logradouro ligados a >1 Bairro:",len(ruas_ambiguas))
display(ruas_ambiguas.sort_values(ascending=False).head(10).to_frame("Bairros"))
for nome,base in (("df_v1",df_v1),("df_v2",df_v2),("df_v3",df_v3)):
    assert pd.util.hash_pandas_object(base,index=True).equals(hashes_bases_antes_area_localizacao[nome])
print("Hashes de V1, V2 e V3 preservados; nenhuma linha removida do diagnóstico.")

Registros com CEP e Bairro preenchidos: 39957
CEPs ligados a >1 Bairro: 2946 de 6052 | imóveis no bairro minoritário: 15832
Bairros ligados a >1 CEP: 791 de 5292
CEPs com mais bairros distintos:
          Bairros  Imóveis  Minoria
CEP_8
04194260       35       90       78
05541030       26       75       61
05303000       24       79       71
04582050       22       36       32
04444000       20       88       72
05145901       19       82       72
04297000       19       80       67
04184000       19       59       51
05038902       19       28       25
05036160       19       19       18
04904904       18       42       35
05005001       18       26       20
03220300       16       41       35
05017000       16       37       22
01307000       16       25       19
Bairros com mais CEPs:
                    CEPs  Imóveis
Bairro_normalizado
BLOCO B              178      655
BLOCO A              171      580
VILA MARIANA         169      373
TORRE B              161      937
TORRE 1              159     1137
TORRE A              156      936
SAUDE                153      501
TORRE 2              149      804
INDIANOPOLIS         142      330
TATUAPE              128      492
CERQUEIRA CESAR      126      339
JD PAULISTA          121      243
BELA VISTA           119      392
MOEMA                114      196
BLOCO 2              103      298
Pares de CEP e bairro nos CEPs com mais registros minoritários:
                               Imóveis
CEP_8    Bairro_normalizado
05144085 LOTE 23                    10
         LOTE 24                    14
         LOTE 25                    12
         LOTE 7                      9
         PIRITUBA                   22
05093000 ED. LUA - BLOCO 2           5
         ED. SOL - BLOCO 1           3
         ED. TERRA - BLOCO 3         1
         TORRE 1                     4
         TORRE 2                    19
04194260 BLOCO 1                     5
         BLOCO 2                     1
         BLOCO 3                     5
         BLOCO 6                     1
         BLOCO 7                     2
03511000 TORRE 1                    48
         TORRE 2                    33
         TORRE 3                    42
01136000 BARRA FUNDA                 1
         BLOCO 1                     3
         BLOCO 2                     4
         ED PALHINHA                 1
         TORRE A                     3
05145901 BLOCO 13                    4
         BLOCO 14                    9
         BLOCO 15                    3
         BLOCO 16                    3
         BLOCO 17                    5
04444000 BLOCO 1                     6
         BLOCO 2                     3
         BLOCO 3                     5
         BLOCO G                     5
         BLOCO I                     3
05303000 BL 1 ALA A VIVRE            4
         BL 1 ALA B ENJOY            8
         BL 2 ALA A VISAGE           3
         BL 2 ALA B FREEDOM          2
         BL B 1 DEP                  1
05503010 TORRE 1                    31
         TORRE 2                    28
         TORRE 3                    22
         TORRE 4                    19
04297000 BL III ED FLAMINGO          5
         BL IV ED PELICANO           4
         BLOCO A                     2
         BLOCO I ED GAIVOTA          1
         BLOCO II ED ALBATROZ        2
Pares CEP + logradouro ligados a >1 Bairro: 2948
                                           Bairros
CEP_8    _Rua_diagnostico
04194260 AV DOS OURIVES                         35
05541030 R TRAJANO REIS                         26
05303000 R CARLOS WEBER                         24
04582050 R GABRIEL DE LARA                      22
04444000 R MIGUEL YUNES                         20
05145901 AV RAIMUNDO PEREIRA DE MAGALHAES       19
05038902 R CORCOVADO                            19
04184000 R PROF ARNALDO JOAO SEMERARO           19
05036160 R PABLO PICASSO                        19
04297000 AV PDE ARLINDO VIEIRA                  19
Hashes de V1, V2 e V3 preservados; nenhuma linha removida do diagnóstico.

In [75]:
# Sinais semanticos de que Bairro guarda complemento, torre ou nome de empreendimento.
cep_tipo = df_area_localizacao["CEP"].map(lambda x: type(x).__name__).value_counts()
comprimento_cep_bruto = df_area_localizacao["CEP"].map(
    lambda x: len(str(int(x))) if isinstance(x,(int,float,np.integer,np.floating)) and pd.notna(x) and float(x).is_integer() else len(str(x).strip())
).value_counts().sort_index()
print("Tipos originais de CEP:")
display(cep_tipo.to_frame("Registros"))
print("Quantidade de algarismos no CEP bruto numerico (ou caracteres em texto):")
display(comprimento_cep_bruto.to_frame("Registros"))
print("CEP_8 com zero inicial:",int(df_area_localizacao["CEP_8"].str.startswith("0").sum()))

marcador_complemento = df_area_localizacao["Bairro_normalizado"].str.contains(
    r"^(?:TORRE|BLOCO|BL(?:\b|\.)|ED(?:\b|\.)|EDIFICIO|COND(?:\b|\.)|CONDOMINIO|RESIDENCIAL|DEP(?:\b|\.)|VAGA|VG(?:\b|\.)|SUBSOLO|LOTE)",
    regex=True,na=False
)
print("Bairro com padrao de complemento/empreendimento (sinal, nao validacao definitiva):",int(marcador_complemento.sum()))
print("Entre Bairros preenchidos:",round(marcador_complemento.sum() / (~bairro_ausente).sum() * 100,2),"%")
print("Exemplos frequentes:")
display(df_area_localizacao.loc[marcador_complemento,"Bairro_normalizado"].value_counts().head(15).to_frame("Registros"))
print("Mesmo CEP com grafias potencialmente equivalentes:")
exemplos_grafia = [("05303000","VL LEOPOLDINA","VILA LEOPOLDINA"),("05145901","JD IRIS","JARDIM IRIS"),("04444000","TORRE 1","TORRE 01")]
for cep,a,b in exemplos_grafia:
    print(cep,a,int(contagem_pares.get((cep,a),0)),"|",b,int(contagem_pares.get((cep,b),0)))

Tipos originais de CEP:
       Registros
CEP
float      63164
Quantidade de algarismos no CEP bruto numerico (ou caracteres em texto):
     Registros
CEP
7        63164
CEP_8 com zero inicial: 63164
Bairro com padrao de complemento/empreendimento (sinal, nao validacao definitiva): 15409
Entre Bairros preenchidos: 38.56 %
Exemplos frequentes:
                    Registros
Bairro_normalizado
TORRE 1                  1137
TORRE B                   937
TORRE A                   936
TORRE 2                   804
BLOCO B                   655
BLOCO A                   580
TORRE 3                   406
BLOCO 2                   298
BLOCO 1                   263
TORRE C                   240
TORRE 4                   192
BLOCO 3                   143
BLOCO C                   141
BLOCO 4                   115
RESIDENCIAL               105
Mesmo CEP com grafias potencialmente equivalentes:
05303000 VL LEOPOLDINA 4 | VILA LEOPOLDINA 3
05145901 JD IRIS 2 | JARDIM IRIS 5
04444000 TORRE 1 5 | TORRE 01 5

### Leitura e decisão desta etapa

- **Área Construída:** 63.164 valores presentes e positivos. A mediana é 102 m² (P1 32; P99 523,37), com 24 registros abaixo de 20 m² e 42 acima de 1.000 m². As áreas se repetem bastante (49 m² aparece 805 vezes), algo compatível com plantas padronizadas, mas extremos como 6 e 2.023 m² precisam de conferência. A associação entre área e valor declarado é positiva (Pearson 0,705; Spearman 0,767). A associação com `Preco_m2` é fraca em postos (Spearman 0,026) e parcialmente mecânica, pois o indicador divide valor por área.
- **CEP:** nenhum ausente ou inválido na V3. Os 63.164 valores originais são numéricos de sete algarismos; `CEP_8` os representa como texto de oito dígitos, restaurando o zero inicial. Existem 7.533 CEPs distintos. Desses, 3.888 têm menos de cinco registros (8.195 imóveis) e 15 têm pelo menos 100 (1.920 imóveis); o maior concentra 200. A validade postal e a localização real ainda não foram verificadas externamente.
- **Bairro:** 23.207 ausentes (36,74%). Há 5.345 grafias originais e 5.292 chaves após remoção de espaços extras e padronização de caixa/acentos. Nesta base não apareceram diferenças de caixa ou acentuação; 932 valores têm espaços extras e 49 chaves reúnem mais de uma grafia. Pelo menos 15.409 registros preenchidos (38,56%) começam com termos de complemento ou empreendimento como TORRE, BLOCO e CONDOMÍNIO. Esse é um sinal exploratório, não uma classificação definitiva. Há também abreviações não resolvidas, como `VL LEOPOLDINA`/`VILA LEOPOLDINA` e `JD IRIS`/`JARDIM IRIS`.
- **CEP x Bairro:** entre 39.957 linhas com ambos preenchidos, 2.946 dos 6.052 CEPs observáveis estão ligados a mais de um Bairro normalizado. A soma das linhas fora do Bairro mais frequente em cada CEP ambíguo é 15.832; isso mede discordância interna, não erro comprovado. Por sua vez, 791 dos 5.292 Bairros normalizados aparecem em vários CEPs, o que pode ser geograficamente normal. Muitos conflitos exibem nomes de torres/blocos no campo Bairro. O CEP parece **mais confiável nesta base** por cobertura e formato; ainda exige verificação geográfica e não deve ser tratado como número contínuo. Bairro pode ser útil após revisão semântica e padronização manual.

Tratamentos futuros a avaliar, sem aplicá-los agora: auditar as áreas extremas e seus valores; conferir CEPs com fontes postais; separar bairros reais de complementos e nomes de empreendimentos; revisar abreviações e pares CEP/Bairro discordantes; planejar categorias raras de CEP. Nenhum registro foi excluído nesta etapa, nenhuma V4 foi criada e nenhum modelo foi treinado.

## DATASET PARA O PRIMEIRO MODELO — escopo e diagnóstico

Objetivo: estimar o **Valor de Transação (declarado pelo contribuinte)** de apartamentos. Esta etapa prepara `df_modelagem`, `X`, `y` e a divisão treino/teste; não treina modelo nem calcula desempenho. O ponto de partida é `df_v3` validado (63.164 registros). Nenhuma linha será removida por preço, área, preço/m² ou ausência de feature.

Antes de selecionar colunas, conferimos novamente a população da V3 e a distribuição do target. A V3 contém apenas transações de 2025 e não possui duplicatas exatas. As assinaturas abaixo permitem conferir que V1, V2 e V3 permaneceram intactas durante esta etapa.

In [76]:
# Pré-condições e diagnóstico do target, sem filtrar registros.
assert len(df_v3) == 63_164
assert pd.to_datetime(df_v3["Data de Transação"], errors="coerce").dt.year.eq(2025).all()
assert not df_v3.duplicated(subset=df_v2.columns.tolist()).any()

assinaturas_bases_antes_modelagem = {
    nome: (len(base), base.columns.tolist(), pd.util.hash_pandas_object(base, index=True))
    for nome, base in (("df_v1", df_v1), ("df_v2", df_v2), ("df_v3", df_v3))
}

col_target = "Valor de Transação (declarado pelo contribuinte)"
target_numerico = pd.to_numeric(df_v3[col_target], errors="coerce")
print("Registros de df_v3:", len(df_v3))
print("Target ausente/não numérico:", int(target_numerico.isna().sum()))
print("Target <= 0:", int(target_numerico.le(0).sum()))
print("Distribuição do target (R$):")
display(target_numerico.describe(percentiles=[.01, .05, .10, .25, .50, .75, .90, .95, .99, .995, .999]).to_frame("Valor de Transação"))

catalogo_v3 = pd.DataFrame({
    "Coluna": df_v3.columns,
    "Tipo": df_v3.dtypes.astype(str).values,
    "Ausentes": df_v3.isna().sum().values,
    "Distintos": df_v3.nunique(dropna=True).values,
})
print("Catálogo de colunas disponíveis na V3:")
display(catalogo_v3)

if target_numerico.isna().any() or target_numerico.le(0).any():
    raise ValueError("O target requer revisão documental antes de preparar treino/teste; nenhum registro foi removido.")

Registros de df_v3: 63164
Target ausente/não numérico: 0
Target <= 0: 0
Distribuição do target (R$):
       Valor de Transação
count        6.316400e+04
mean         7.561633e+05
std          1.354585e+06
min          1.000000e+04
1%           7.817451e+04
5%           1.605389e+05
10%          2.178475e+05
25%          2.906809e+05
50%          4.480000e+05
75%          7.950071e+05
90%          1.450000e+06
95%          2.100000e+06
99%          5.150000e+06
99.5%        7.452210e+06
99.9%        1.696740e+07
max          7.000000e+07
Catálogo de colunas disponíveis na V3:
                                              Coluna            Tipo  Ausentes  Distintos
0                               N° do Cadastro (SQL)           int64         0      61951
1                                 Nome do Logradouro             str         0       5208
2                                             Número           int64         0       2413
3                                        Complemento          object        23      20779
4                                             Bairro          object     23207       5345
5                                         Referência          object     14581      11437
6                                                CEP         float64         0       7533
7                              Natureza de Transação          object         0          1
8   Valor de Transação (declarado pelo contribuinte)         float64         0      14579
9                                  Data de Transação  datetime64[us]         0        334
10                         Valor Venal de Referência         float64         0      28597
11                         Proporção Transmitida (%)         float64         0          1
12          Valor Venal de Referência (proporcional)         float64         0      28597
13                           Base de Cálculo adotada         float64         0      19701
14                             Tipo de Financiamento          object     42070          4
15                                  Valor Financiado          object         0       7951
16                              Cartório de Registro          object         0         18
17                               Matrícula do Imóvel          object         0      57210
18                                   Situação do SQL          object         0          3
19                              Área do Terreno (m2)          object         0       5275
20                                       Testada (m)         float64         0       4531
21                                      Fração Ideal         float64         0       1322
22                              Área Construída (m2)           int64         0        769
23                                        Uso (IPTU)           int64         0          1
24                           Descrição do uso (IPTU)          object         0          1
25                                     Padrão (IPTU)          object         0         11
26                        Descrição do padrão (IPTU)          object         0          3
27                                        ACC (IPTU)          object         0         96
28                                       Mes_Arquivo             str         0         12
29                                       Unnamed: 28         float64     63160          4
30                                          Preco_m2         float64         0      30119

### Seleção de features e disponibilidade no momento da estimativa

| Feature aprovada | Tipo | Motivo |
|---|---|---|
| `Área Construída (m2)` | Numérica | Tamanho físico conhecido antes da venda; relaciona-se diretamente com o porte do apartamento. |
| `CEP_8` | Categórica | Localização disponível na consulta. É texto de oito dígitos, incluindo o zero inicial, sem interpretação de distância ou ordem numérica. |
| `Padrão (IPTU)` | Categórica | Classificação cadastral prévia que pode representar diferenças construtivas e de acabamento. É código de classe, não medida contínua. |
| `ACC (IPTU)` | Numérica | Ano corrigido de conclusão da construção, conforme a aba `EXPLICAÇÕES` da fonte. Informa idade/reformas do imóvel e consta do cadastro IPTU. |

`Descrição do padrão (IPTU)` é derivada do código e resume apenas o tipo amplo da construção (3 descrições versus 11 códigos na V3); o código preserva mais detalhe. `Bairro` fica **fora do primeiro baseline**: 23.207 ausentes (36,74%), além de nomes de torres, blocos e empreendimentos no campo. `CEP_8` tem cobertura completa nesta V3 e já representa localização, embora sua validade postal ainda precise de auditoria externa.

Outras colunas não entram apenas por existirem: `Área do Terreno (m2)`, `Testada (m)` e `Fração Ideal` descrevem em parte o lote/condomínio e exigem análise de significado, cobertura e disponibilidade no pedido de estimativa. `Situação do SQL` é quase constante (63.068 ativos de 63.164). `Nome do Logradouro`, `Número`, `Complemento`, `N° do Cadastro (SQL)` e `Matrícula do Imóvel` identificam ou quase identificam imóveis; exigiriam tratamento e validação próprios. `Referência` é texto livre pouco definido, com 14.581 ausentes. `Uso (IPTU)`/`Descrição do uso (IPTU)` são constantes pela seleção de apartamentos. `Unnamed: 28` é uma coluna residual da planilha quase toda vazia (63.160 ausentes). O `CEP` bruto é substituído pela representação categórica `CEP_8`.

In [77]:
# Lista explícita de colunas vedadas a X por informação do resultado ou da transação.
FEATURES_EXCLUIDAS_POR_LEAKAGE = [
    {"coluna": col_target, "motivo": "É o próprio target (y)."},
    {"coluna": "Preco_m2", "motivo": "Calculado como valor da transação dividido pela área; revela y diretamente."},
    {"coluna": "Valor Venal de Referência", "motivo": "Valor fiscal monetário associado à operação; proxy de preço com disponibilidade e independência não garantidas no pedido."},
    {"coluna": "Valor Venal de Referência (proporcional)", "motivo": "Valor fiscal ajustado à fração transmitida; proxy monetária ligada à operação."},
    {"coluna": "Base de Cálculo adotada", "motivo": "Base fiscal da operação, possivelmente influenciada pelo valor declarado; proxy direta de y."},
    {"coluna": "Valor Financiado", "motivo": "Montante definido na negociação/financiamento, indisponível antes de estimar o imóvel."},
    {"coluna": "Tipo de Financiamento", "motivo": "Condição da operação definida durante a compra, não característica prévia do imóvel."},
    {"coluna": "Data de Transação", "motivo": "Data efetiva conhecida após a operação; usada apenas para dividir treino/teste, nunca em X."},
    {"coluna": "Mes_Arquivo", "motivo": "Mês administrativo de publicação da guia, conhecido após a operação."},
    {"coluna": "Natureza de Transação", "motivo": "Tipo da operação formalizada; além disso, é constante na V3 pela seleção anterior."},
    {"coluna": "Proporção Transmitida (%)", "motivo": "Fração negociada na operação; é constante em 100% na V3 pela seleção anterior."},
    {"coluna": "Cartório de Registro", "motivo": "Informação da formalização/registro da transação, não necessária à estimativa prévia."},
]
colunas_leakage = {item["coluna"] for item in FEATURES_EXCLUIDAS_POR_LEAKAGE}
assert len(colunas_leakage) == len(FEATURES_EXCLUIDAS_POR_LEAKAGE)
assert colunas_leakage.issubset(df_v3.columns)
print("Exclusões por leakage/indisponibilidade na consulta:")
display(pd.DataFrame(FEATURES_EXCLUIDAS_POR_LEAKAGE))

Exclusões por leakage/indisponibilidade na consulta:
                                              coluna                                                                                                                     motivo
0   Valor de Transação (declarado pelo contribuinte)                                                                                                    É o próprio target (y).
1                                           Preco_m2                                                Calculado como valor da transação dividido pela área; revela y diretamente.
2                          Valor Venal de Referência  Valor fiscal monetário associado à operação; proxy de preço com disponibilidade e independência não garantidas no pedido.
3           Valor Venal de Referência (proporcional)                                             Valor fiscal ajustado à fração transmitida; proxy monetária ligada à operação.
4                            Base de Cálculo adotada                               Base fiscal da operação, possivelmente influenciada pelo valor declarado; proxy direta de y.
5                                   Valor Financiado                                     Montante definido na negociação/financiamento, indisponível antes de estimar o imóvel.
6                              Tipo de Financiamento                                       Condição da operação definida durante a compra, não característica prévia do imóvel.
7                                  Data de Transação                                Data efetiva conhecida após a operação; usada apenas para dividir treino/teste, nunca em X.
8                                        Mes_Arquivo                                                       Mês administrativo de publicação da guia, conhecido após a operação.
9                              Natureza de Transação                                         Tipo da operação formalizada; além disso, é constante na V3 pela seleção anterior.
10                         Proporção Transmitida (%)                                             Fração negociada na operação; é constante em 100% na V3 pela seleção anterior.
11                              Cartório de Registro                                      Informação da formalização/registro da transação, não necessária à estimativa prévia.

### Preparação posterior das variáveis

`Área Construída (m2)` e `ACC (IPTU)` (ano de construção corrigido) serão numéricas. Se uma base futura tiver ausências, a imputação por mediana será **ajustada somente no treino**. `CEP_8` e `Padrão (IPTU)` serão categorias. O CEP tem **7.533 categorias** na V3; muitos CEPs são raros. No treino do primeiro modelo, agrupar categorias pouco frequentes e usar codificação categórica com tratamento para CEP desconhecido, ajustando frequência e vocabulário apenas no treino. Não usar o CEP bruto como número contínuo nem calcular médias do target por CEP antes da divisão. Ausências categóricas futuras podem receber uma categoria explícita, também definida no pipeline de treino.

Nenhuma dessas transformações estatísticas é aplicada aqui. A padronização de CEP para oito dígitos e a conversão do código IPTU para texto apenas preservam a semântica categórica em uma cópia; `df_v3` permanece inalterado.

In [78]:
# Cópia exclusiva de modelagem: target + quatro features; índice original preservado para auditoria.
FEATURES_APROVADAS = ["Área Construída (m2)", "CEP_8", "Padrão (IPTU)", "ACC (IPTU)"]
FEATURES_NUMERICAS = ["Área Construída (m2)", "ACC (IPTU)"]
FEATURES_CATEGORICAS = ["CEP_8", "Padrão (IPTU)"]
assert set(FEATURES_APROVADAS).isdisjoint(colunas_leakage)

df_modelagem = df_v3[[col_target, "Área Construída (m2)", "Padrão (IPTU)", "ACC (IPTU)"]].copy()
df_modelagem["CEP_8"] = pd.Series(
    [normalizar_cep(cep) for cep in df_v3["CEP"]],
    index=df_v3.index, dtype="string"
)
df_modelagem["Padrão (IPTU)"] = df_modelagem["Padrão (IPTU)"].astype("string")
df_modelagem["ACC (IPTU)"] = pd.to_numeric(df_modelagem["ACC (IPTU)"], errors="coerce")
df_modelagem = df_modelagem[[col_target] + FEATURES_APROVADAS]
assert df_modelagem["CEP_8"].equals(df_area_localizacao["CEP_8"])
assert df_modelagem["ACC (IPTU)"].notna().all()
assert df_modelagem["ACC (IPTU)"].between(1900, 2025).all()
assert df_modelagem["ACC (IPTU)"].le(df_v3["Data de Transação"].dt.year).all()
assert len(df_modelagem) == len(df_v3) == 63_164
assert df_modelagem.columns.tolist() == [col_target] + FEATURES_APROVADAS

X = df_modelagem[FEATURES_APROVADAS].copy()
y = df_modelagem[col_target].copy()
assert X.index.equals(y.index)
assert "Preco_m2" not in X.columns and col_target not in X.columns
print("Registros em df_modelagem:", len(df_modelagem))
print("Número de features:", X.shape[1])
print("Features:", FEATURES_APROVADAS)
print("Tipos e valores ausentes:")
display(pd.DataFrame({"Tipo": df_modelagem.dtypes.astype(str), "Ausentes": df_modelagem.isna().sum()}))
print("Nenhuma coluna de X deriva do target: área, CEP, padrão e ano de construção IPTU provêm de campos físicos/cadastrais independentes do valor declarado.")

Registros em df_modelagem: 63164
Número de features: 4
Features: ['Área Construída (m2)', 'CEP_8', 'Padrão (IPTU)', 'ACC (IPTU)']
Tipos e valores ausentes:
                                                     Tipo  Ausentes
Valor de Transação (declarado pelo contribuinte)  float64         0
Área Construída (m2)                                int64         0
CEP_8                                              string         0
Padrão (IPTU)                                      string         0
ACC (IPTU)                                        float64         0
Nenhuma coluna de X deriva do target: área, CEP, padrão e ano de construção IPTU provêm de campos físicos/cadastrais independentes do valor declarado.

### Estratégia de treino/teste

A V3 contém transações de janeiro a dezembro de 2025. Para simular uma estimativa futura, a avaliação deve usar **datas posteriores** às de treinamento. Uma divisão aleatória misturaria períodos e permitiria ao treino aprender padrões de preços posteriores aos exemplos de teste. A divisão abaixo escolhe a **data inteira** cuja contagem acumulada fica mais próxima de 80%; todos os registros de uma mesma data ficam no mesmo lado. A proporção resultante pode diferir ligeiramente de 80/20. A data é metadado de separação, não feature de `X` nem coluna de `df_modelagem`.

`random_state = 42` fica definido para futuras operações estocásticas. A divisão cronológica em si é determinística e não utiliza sorteio. As transformações que aprenderem parâmetros ou categorias da base deverão ser ajustadas após esta divisão, exclusivamente no treino.

In [79]:
# Divisão temporal, sem usar y para escolher o corte e sem pré-processamento ajustado no teste.
random_state = 42
datas_modelagem = pd.to_datetime(df_v3.loc[df_modelagem.index, "Data de Transação"], errors="coerce")
assert datas_modelagem.notna().all() and datas_modelagem.dt.year.eq(2025).all()

contagem_por_data = datas_modelagem.value_counts().sort_index()
acumulado_treino = contagem_por_data.cumsum().iloc[:-1]
alvo_treino = round(0.80 * len(df_modelagem))
data_corte_treino = (acumulado_treino - alvo_treino).abs().idxmin()
mask_treino = datas_modelagem.le(data_corte_treino)
mask_teste = ~mask_treino

X_train, X_test = X.loc[mask_treino].copy(), X.loc[mask_teste].copy()
y_train, y_test = y.loc[mask_treino].copy(), y.loc[mask_teste].copy()
assert len(X_train) + len(X_test) == len(df_modelagem)
assert len(X_train) == len(y_train) and len(X_test) == len(y_test)
assert X_train.index.intersection(X_test.index).empty
assert datas_modelagem.loc[X_train.index].max() < datas_modelagem.loc[X_test.index].min()
assert abs(len(X_train) / len(X) - 0.80) < 0.005

for nome, base in (("df_v1", df_v1), ("df_v2", df_v2), ("df_v3", df_v3)):
    n_antes, colunas_antes, hash_antes = assinaturas_bases_antes_modelagem[nome]
    assert len(base) == n_antes and base.columns.tolist() == colunas_antes
    assert pd.util.hash_pandas_object(base, index=True).equals(hash_antes)

print("Última data de treino:", datas_modelagem.loc[X_train.index].max().date())
print("Primeira data de teste:", datas_modelagem.loc[X_test.index].min().date())
print("Treino:", len(X_train), f"({len(X_train) / len(X):.2%})")
print("Teste:", len(X_test), f"({len(X_test) / len(X):.2%})")
print("Ausentes em X_train / X_test:")
display(pd.DataFrame({"Treino": X_train.isna().sum(), "Teste": X_test.isna().sum()}))
print("df_v1, df_v2 e df_v3: assinaturas de conteúdo e estrutura preservadas.")

Última data de treino: 2025-10-21
Primeira data de teste: 2025-10-22
Treino: 50598 (80.11%)
Teste: 12566 (19.89%)
Ausentes em X_train / X_test:
                      Treino  Teste
Área Construída (m2)       0      0
CEP_8                      0      0
Padrão (IPTU)              0      0
ACC (IPTU)                 0      0
df_v1, df_v2 e df_v3: assinaturas de conteúdo e estrutura preservadas.

In [80]:
# Resumo da etapa; nenhuma rotina de treinamento ou métrica é executada.
print("RESULTADO DA ETAPA — DATASET PARA MACHINE LEARNING")
print("1. Target:", col_target)
print("2. Features aprovadas:", ", ".join(FEATURES_APROVADAS))
print("3. Excluídas por leakage/indisponibilidade: ver FEATURES_EXCLUIDAS_POR_LEAKAGE e motivos acima.")
print("4. CEP: CEP_8 como categoria de oito dígitos; nunca número contínuo.")
print("5. Bairro: fora do primeiro baseline por ausência e inconsistência semântica.")
print("6. Registros em df_modelagem:", len(df_modelagem))
print("7. Número de features:", len(FEATURES_APROVADAS))
print("8. Registros de treino:", len(X_train))
print("9. Registros de teste:", len(X_test))
print("10. Ausentes relevantes: target=", int(y.isna().sum()), "; features=", X.isna().sum().to_dict())
print("11. Estratégia: corte cronológico por data inteira, aproximadamente 80/20; random_state=42 reservado para uso futuro.")
print("12. df_v3 permaneceu intacto: SIM (assinatura verificada).")
print("13. Nenhum modelo foi treinado: SIM.")
print("DATASET PRONTO PARA O PRIMEIRO MODELO: SIM")

RESULTADO DA ETAPA — DATASET PARA MACHINE LEARNING
1. Target: Valor de Transação (declarado pelo contribuinte)
2. Features aprovadas: Área Construída (m2), CEP_8, Padrão (IPTU), ACC (IPTU)
3. Excluídas por leakage/indisponibilidade: ver FEATURES_EXCLUIDAS_POR_LEAKAGE e motivos acima.
4. CEP: CEP_8 como categoria de oito dígitos; nunca número contínuo.
5. Bairro: fora do primeiro baseline por ausência e inconsistência semântica.
6. Registros em df_modelagem: 63164
7. Número de features: 4
8. Registros de treino: 50598
9. Registros de teste: 12566
10. Ausentes relevantes: target= 0 ; features= {'Área Construída (m2)': 0, 'CEP_8': 0, 'Padrão (IPTU)': 0, 'ACC (IPTU)': 0}
11. Estratégia: corte cronológico por data inteira, aproximadamente 80/20; random_state=42 reservado para uso futuro.
12. df_v3 permaneceu intacto: SIM (assinatura verificada).
13. Nenhum modelo foi treinado: SIM.
DATASET PRONTO PARA O PRIMEIRO MODELO: SIM

## SMARTPRICE AI — BASELINE V1

**Objetivo:** estimar `Valor de Transação (declarado pelo contribuinte)` com as quatro features aprovadas e a divisão cronológica já definida. Usamos uma única regressão Ridge (penalização L2 fixa em 1, sem busca de hiperparâmetros): é um modelo linear simples, com coeficientes interpretáveis, e a penalização estabiliza o ajuste com muitos CEPs categóricos.

O `ColumnTransformer` imputa as numéricas pela mediana e as padroniza. Para as categorias, imputa ausência com uma categoria explícita, agrupa CEPs com menos de cinco ocorrências **no treino** e aplica one-hot encoding. CEPs inéditos no teste usam o grupo infrequente, quando existente; categorias de padrão inéditas são ignoradas pelo codificador. Todo parâmetro do pré-processamento é aprendido dentro do `Pipeline.fit(X_train, y_train)`. `Preco_m2`, o próprio target e as demais colunas ligadas à transação ficam fora de `X`.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Contrato do dataset e da separação, antes de qualquer fit.
assert len(df_modelagem) == len(X) == len(y) == 63_164
assert len(X_train) == len(y_train) == 50_598
assert len(X_test) == len(y_test) == 12_566
assert X.columns.tolist() == FEATURES_APROVADAS
assert set(FEATURES_NUMERICAS) == {"Área Construída (m2)", "ACC (IPTU)"}
assert set(FEATURES_CATEGORICAS) == {"CEP_8", "Padrão (IPTU)"}
assert set(X.columns).isdisjoint(colunas_leakage)
assert "Preco_m2" not in X.columns and col_target not in X.columns
assert y.name == col_target
assert X_train.index.equals(y_train.index) and X_test.index.equals(y_test.index)
assert X_train.index.intersection(X_test.index).empty
assert datas_modelagem.loc[X_train.index].max() < datas_modelagem.loc[X_test.index].min()
for nome, base in (("df_v1", df_v1), ("df_v2", df_v2), ("df_v3", df_v3)):
    n_antes, colunas_antes, hash_antes = assinaturas_bases_antes_modelagem[nome]
    assert len(base) == n_antes and base.columns.tolist() == colunas_antes
    assert pd.util.hash_pandas_object(base, index=True).equals(hash_antes)

preprocessamento_baseline_v1 = ColumnTransformer(
    transformers=[
        ("numericas", Pipeline([
            ("imputacao", SimpleImputer(strategy="median")),
            ("escala", StandardScaler()),
        ]), FEATURES_NUMERICAS),
        ("cep", Pipeline([
            ("imputacao", SimpleImputer(strategy="constant", fill_value="__AUSENTE__")),
            ("one_hot", OneHotEncoder(min_frequency=5, handle_unknown="infrequent_if_exist")),
        ]), ["CEP_8"]),
        ("padrao", Pipeline([
            ("imputacao", SimpleImputer(strategy="constant", fill_value="__AUSENTE__")),
            ("one_hot", OneHotEncoder(handle_unknown="ignore")),
        ]), ["Padrão (IPTU)"]),
    ]
)
baseline_v1 = Pipeline([
    ("preprocessamento", preprocessamento_baseline_v1),
    ("regressao", Ridge(alpha=1.0, solver="lsqr")),
])
baseline_v1.fit(X_train, y_train)

cep_encoder_v1 = baseline_v1.named_steps["preprocessamento"].named_transformers_["cep"].named_steps["one_hot"]
ceps_treino_v1 = set(X_train["CEP_8"].dropna())
ceps_ineditos_teste_v1 = ~X_test["CEP_8"].isin(ceps_treino_v1)
print("Algoritmo: Ridge (alpha=1, solver=lsqr), sem tuning")
print("CEPs distintos no treino:", len(ceps_treino_v1))
print("CEPs inéditos no teste:", int(ceps_ineditos_teste_v1.sum()))
print("CEPs raros agrupados no fit:", len(cep_encoder_v1.infrequent_categories_[0]))
print("Período de treino:", datas_modelagem.loc[X_train.index].min().date(), "a", datas_modelagem.loc[X_train.index].max().date())
print("Período de teste:", datas_modelagem.loc[X_test.index].min().date(), "a", datas_modelagem.loc[X_test.index].max().date())

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

previsoes_baseline_v1 = baseline_v1.predict(X_test)
real_baseline_v1 = y_test.to_numpy(dtype=float)
erro_assinado_v1 = previsoes_baseline_v1 - real_baseline_v1  # positivo = superestimativa
erro_absoluto_v1 = np.abs(erro_assinado_v1)
assert np.isfinite(previsoes_baseline_v1).all()
assert (real_baseline_v1 > 0).all()

metricas_baseline_v1 = {
    "MAE (R$)": mean_absolute_error(real_baseline_v1, previsoes_baseline_v1),
    "RMSE (R$)": np.sqrt(mean_squared_error(real_baseline_v1, previsoes_baseline_v1)),
    "R²": r2_score(real_baseline_v1, previsoes_baseline_v1),
    "Mediana do erro absoluto (R$)": np.median(erro_absoluto_v1),
    "Erro percentual absoluto mediano (%)": 100 * np.median(erro_absoluto_v1 / real_baseline_v1),
}
avaliacao_baseline_v1 = pd.DataFrame({
    "Data": datas_modelagem.loc[X_test.index].to_numpy(),
    "Valor real (R$)": real_baseline_v1,
    "Valor previsto (R$)": previsoes_baseline_v1,
    "Erro assinado (R$)": erro_assinado_v1,
    "Erro absoluto (R$)": erro_absoluto_v1,
}, index=X_test.index)
print("MÉTRICAS — BASELINE V1 (teste cronológico)")
for nome, base in (("df_v1", df_v1), ("df_v2", df_v2), ("df_v3", df_v3)):
    n_antes, colunas_antes, hash_antes = assinaturas_bases_antes_modelagem[nome]
    assert len(base) == n_antes and base.columns.tolist() == colunas_antes
    assert pd.util.hash_pandas_object(base, index=True).equals(hash_antes)
for nome, valor in metricas_baseline_v1.items():
    print(f"{nome}: {valor:,.4f}" if nome == "R²" or "(%)" in nome else f"{nome}: R$ {valor:,.2f}")

In [ ]:
# Diagnóstico descritivo; nenhuma observação é excluída do cálculo das métricas.
print("Distribuição do erro assinado (previsto - real), em R$:")
print(avaliacao_baseline_v1["Erro assinado (R$)"].describe(percentiles=[.01, .10, .25, .50, .75, .90, .99]).to_string())
print("\nDez maiores erros absolutos (valores reais x previstos):")
print(avaliacao_baseline_v1.nlargest(10, "Erro absoluto (R$)").to_string())

faixas_valor_v1 = pd.cut(
    avaliacao_baseline_v1["Valor real (R$)"],
    bins=[0, 250_000, 500_000, 1_000_000, 2_000_000, 5_000_000, float("inf")],
    labels=["Até 250 mil", "250–500 mil", "500 mil–1 mi", "1–2 mi", "2–5 mi", "Acima de 5 mi"],
    include_lowest=True,
)
resumo_faixas_baseline_v1 = avaliacao_baseline_v1.groupby(faixas_valor_v1, observed=True).agg(
    Registros=("Valor real (R$)", "size"),
    Real_mediano=("Valor real (R$)", "median"),
    Previsto_mediano=("Valor previsto (R$)", "median"),
    Erro_assinado_mediano=("Erro assinado (R$)", "median"),
    Erro_absoluto_mediano=("Erro absoluto (R$)", "median"),
    Erro_assinado_medio=("Erro assinado (R$)", "mean"),
)
print("\nErros por faixa de valor real (R$):")
print(resumo_faixas_baseline_v1.to_string(float_format=lambda valor: f"{valor:,.2f}"))
print("\nPrevisões negativas:", int((previsoes_baseline_v1 < 0).sum()))

In [ ]:
# Gráfico 1: todos os imóveis do teste, inclusive extremos; escala simétrica acomoda previsões negativas.
fig, ax = plt.subplots(figsize=(7, 6))
ax.scatter(real_baseline_v1, previsoes_baseline_v1, s=8, alpha=.18, rasterized=True)
limite_superior = max(real_baseline_v1.max(), previsoes_baseline_v1.max())
ax.plot([0, limite_superior], [0, limite_superior], color="crimson", linestyle="--", linewidth=1, label="Previsão perfeita")
ax.set_xscale("symlog", linthresh=100_000)
ax.set_yscale("symlog", linthresh=100_000)
ax.set_xlabel("Valor real (R$)")
ax.set_ylabel("Valor previsto (R$)")
ax.set_title("Baseline V1 — valores reais x previstos")
ax.legend()
ax.grid(alpha=.2)
plt.tight_layout()
plt.show()

# Gráfico 2: viés por faixa; erro positivo indica superestimativa.
fig, ax = plt.subplots(figsize=(8, 4))
vies_faixa = resumo_faixas_baseline_v1["Erro_assinado_mediano"] / 1_000
ax.bar(vies_faixa.index.astype(str), vies_faixa, color=["#C54E48" if x < 0 else "#397C83" for x in vies_faixa])
ax.axhline(0, color="black", linewidth=.8)
ax.set_ylabel("Erro assinado mediano (R$ mil)")
ax.set_title("Baseline V1 — viés por faixa de valor real")
ax.tick_params(axis="x", labelrotation=25)
ax.grid(axis="y", alpha=.2)
plt.tight_layout()
plt.show()

### Registro do resultado — BASELINE V1

| Item | Resultado |
|---|---|
| Algoritmo | Regressão Ridge (alpha = 1, solver = lsqr); um único modelo, sem tuning |
| Features | Área Construída (m2), ACC (IPTU), CEP_8, Padrão (IPTU) |
| Target | Valor de Transação (declarado pelo contribuinte) |
| Treino | 50.598 registros; 02/01/2025 a 21/10/2025 |
| Teste | 12.566 registros; 22/10/2025 a 31/12/2025 |
| MAE | R$ 288.838,43 |
| RMSE | R$ 954.108,08 |
| R² | 0,6064 |
| Mediana do erro absoluto | R$ 124.050,79 |
| Erro percentual absoluto mediano | 25,15% (todos os valores reais do teste são positivos) |

O erro assinado é **previsto menos real**: valores negativos indicam subestimativa. A mediana global é −R$ 7.978,30, mas a dispersão é ampla (P1: −R$ 1,68 milhão; P99: +R$ 1,86 milhão). Os dez maiores erros absolutos são subestimativas de imóveis caros. Na faixa acima de R$ 5 milhões (141 imóveis), o erro assinado mediano é −R$ 2.271.821,95 e o erro absoluto mediano é R$ 2.370.760,51. Até R$ 250 mil, a mediana do erro assinado é +R$ 20.912,44.

**Limitações principais:** a relação linear subestima a cauda de alto valor e pode gerar preços impossíveis: houve 326 previsões negativas, preservadas no cálculo das métricas. A alta cardinalidade do CEP exige agrupamento: 3.996 CEPs de treino com menos de cinco ocorrências foram agrupados, e 532 imóveis do teste possuem CEP ausente do treino. Isso reduz a precisão local. Casos extremos elevam muito o RMSE; nenhum registro foi removido ou previsão truncada para melhorar o resultado.

**Controle de leakage:** X contém exclusivamente as quatro features físicas/cadastrais aprovadas. Preco_m2, valor da transação e proxies monetárias/operacionais estão fora de X. A divisão é cronológica; imputação, escala, vocabulário e agrupamento de CEP são ajustados no pipeline apenas com X_train. As assinaturas de df_v1, df_v2 e df_v3 foram conferidas antes e depois do fit. Não foi identificado vazamento pelas features ou pelo pré-processamento.

**Próxima implementação recomendada:** investigar documentalmente os casos de alto valor, as previsões negativas e a cobertura de CEP antes de definir um próximo experimento. Este registro encerra a etapa Baseline V1.

## RESULTADO DA ETAPA — DIAGNÓSTICO BASELINE V1

**08/10/2026 — Diagnóstico quantitativo bloqueado por ausência de artefatos verificáveis.** Nenhum treinamento ou reconstrução foi executado.

**Validação disponível:** as saídas salvas da preparação registram 63.164 observações, 50.598 no treino e 12.566 no teste, com corte entre 21 e 22/10/2025. Isso confirma o registro da preparação, sem revalidar bases em memória. As células de treinamento, avaliação, diagnóstico e gráficos do Baseline V1 (índices 95–98) têm execution_count nulo e outputs vazios. As métricas originais estão apenas no Markdown e foram preservadas, sem validação independente.

A inspeção recursiva, incluindo arquivos ocultos, de data, models, notebooks, src e app encontrou somente a planilha bruta e este notebook. data/processed e models estão vazios. Não há pipeline ajustado, previsões, avaliação ou partições persistidas; o notebook não contém código de serialização desses objetos. Eventual estado do kernel da IDE não foi disponibilizado nesta sessão.

1. **Alto valor:** o registro anterior informa 141 imóveis acima de R$ 5 milhões, viés mediano de −R$ 2.271.821,95 e erro absoluto mediano de R$ 2.370.760,51. São números reportados, não recalculados. MAE e viés médio do segmento não estão disponíveis. Mediana do erro absoluto não equivale a MAE. Sem previsões alinhadas às features, não é possível investigar associações com área, padrão ou CEP. Erro assinado = previsto − real.
2. **Previsões negativas:** 326 casos reportados, sem vetor ou lista para validar e identificar os registros. Valores reais, áreas, CEPs, padrão e ACC não puderam ser comparados com o restante do teste. A Ridge em reais não impõe positividade: isso explica a possibilidade matemática de preços negativos, mas não identifica os componentes responsáveis pelos casos reportados.
3. **Cobertura:** o texto anterior informa 532 registros de teste com CEP ausente do treino, não 532 CEPs distintos, e 3.996 CEPs raros agrupados no treino. Esses números não foram recalculados; quantidade de CEPs inéditos distintos indisponível.
4. **Desempenho por cobertura:** MAE, RMSE, R² e erros medianos para CEPs conhecidos versus inéditos não estão persistidos e não podem ser recuperados das métricas globais. Nenhuma diferença de desempenho foi inferida.
5. **Pipeline e padrões:** o código configura CEP com OneHotEncoder(min_frequency=5, handle_unknown="infrequent_if_exist"): inéditos usam o grupo infrequente se criado no ajuste; sem esse grupo, o bloco de CEP fica zerado. Padrão IPTU usa handle_unknown="ignore", zerando seu bloco para categorias desconhecidas. Foi verificada a configuração por leitura, sem acesso ao vocabulário aprendido. O agrupamento pode limitar distinções espaciais, mas seu impacto no erro não foi medido. Nenhum novo padrão empírico ou causalidade foi estabelecido.
6. **Até três candidatas condicionais para V2, sem implementação:** (a) avaliar target logarítmico com inversão adequada para suporte positivo, verificando viés de inversão e erros em reais; (b) avaliar não linearidades e interações entre área, padrão e localização, após validar a subestimação reportada e a qualidade cadastral; (c) avaliar representação hierárquica por prefixos de CEP para raros/inéditos, após medir cobertura e erros por grupo. São hipóteses para experimentos futuros, não melhorias comprovadas por este diagnóstico; parâmetros aprendidos devem usar somente o treino.
7. **Integridade:** somente esta célula Markdown foi acrescentada. Código, saídas e métricas anteriores permaneceram intactos. Não houve alteração de df_v1, df_v2, df_v3, df_modelagem, divisão ou pipeline, remoção de registros/outliers, truncamento de previsões, tuning ou treinamento. Modelo V2 não implementado.

**Para desbloquear:** disponibilizar X_train, X_test e y_test da divisão original, com índices e tipos preservados, e previsões originais alinhadas a X_test (ou pipeline V1 já ajustado para somente inferência). O pipeline ajustado também permite verificar o vocabulário e o grupo infrequente efetivos. Nenhum gráfico foi criado porque faltam pares reais/previsões verificáveis. A etapa termina com este bloqueio documentado.

## RESULTADO DA ETAPA — RECUPERAÇÃO BASELINE V1

**08/10/2026 — Pipeline recuperado: SIM. Diagnóstico desbloqueado: SIM, ainda não executado.** Uma reexecução autorizada da Ridge original; sem novos algoritmos, tuning ou V2. O bloqueio registrado acima descreve a inspeção anterior e foi resolvido pela persistência abaixo.

O script `src/recuperar_baseline_v1.py` executou o código original das células 0, 1, 2, 10, 11, 15, 31, 32, 33, 34, 36, 51, 52, 72, 73, 77, 80, 86, 88, 90, 92, 95 e 96 em processo isolado. As células 97–98 de diagnóstico de erros e gráficos não foram executadas. Filtros, concatenação dos meses, índices, normalização de CEP, features, pré-processamento e divisão não foram modificados. As bases foram reconstruídas exclusivamente pelo código original; suas assinaturas foram conferidas antes/depois do fit e após a persistência.

**Divisão:** 50.598 registros no treino (02/01/2025–21/10/2025) e 12.566 no teste (22/10/2025–31/12/2025), total 63.164. Índices selecionados conferidos diretamente contra a V3 e o corte original; treino e teste são disjuntos. Contagens e datas coincidem com as saídas históricas. **Limite de validação:** não existiam listas/hashes históricos das partições para confirmar independentemente cada registro da execução anterior. Agora os índices, conteúdo, tipos e hashes das partições estão persistidos para auditoria.

| Métrica | Valor recuperado | Valor anterior | Diferença na precisão publicada |
|---|---:|---:|---:|
| MAE | R$ 288.838,43 | R$ 288.838,43 | R$ 0,00 |
| RMSE | R$ 954.108,08 | R$ 954.108,08 | R$ 0,00 |
| R² | 0,6064 | 0,6064 | 0,0000 |
| Mediana do erro absoluto | R$ 124.050,79 | R$ 124.050,79 | R$ 0,00 |
| Erro percentual absoluto mediano | 25,15% | 25,15% | 0,00 ponto percentual |

Valores completos: MAE 288838.43365456635; RMSE 954108.0794786493; R² 0.6064064201089863; mediana absoluta 124050.78926702146; erro percentual absoluto mediano 25.148626479558757%. As diferenças em relação aos números anteriormente arredondados são, respectivamente, +0.00365456635 reais, −0.0005213507 reais, +0.000006420109, −0.00073297854 reais e −0.001373520441 ponto percentual. Todas ficam dentro do arredondamento publicado; não há divergência material identificada.

**Arquivos locais:**
- `../models/baseline_v1_recuperado.joblib`: pipeline ajustado completo.
- `../data/processed/baseline_v1_particoes.joblib`: X_train, X_test, y_train, y_test, datas_train e datas_test, com índices/tipos originais.
- `../data/processed/baseline_v1_previsoes_teste.csv`: indice_original, Data, Valor real (R$), Valor previsto (R$), sem truncar previsões; floats com 17 algarismos significativos.
- `../models/baseline_v1_manifesto.json`: métricas completas, diferenças, parâmetros inclusive defaults, versões, hashes dos arquivos/fontes/células/partições e evidências/limitações de validação.

Os arquivos não incluem SQL, nome, logradouro, número, complemento, bairro ou financiamento. As partições e previsões ficam ignoradas pelo Git; não foram exportadas as bases brutas.

**Parâmetros:** Ridge alpha=1, solver=lsqr; numéricas imputadas por mediana e StandardScaler; CEP com OneHotEncoder(min_frequency=5, handle_unknown="infrequent_if_exist"); padrão com handle_unknown="ignore". Features, na ordem original: Área Construída (m2), CEP_8, Padrão (IPTU), ACC (IPTU).

**Ambiente efetivo:** Python 3.13.5; pandas 3.0.3; NumPy 2.4.1; scikit-learn 1.8.0; SciPy 1.17.1; joblib 1.5.3; openpyxl 3.1.5; matplotlib 3.10.9. A .venv original referencia um Python 3.14.7 inexistente nesta máquina; requisitos anteriores e versão registrada no notebook estão preservados no manifesto. Apesar dessas diferenças, todas as métricas coincidiram na precisão anterior. Não foram instaladas nem alteradas dependências.

**Teste de carregamento: OK.** Pipeline e partições recarregados; previsões exatamente iguais (diferença máxima 0,0), índices, valores reais e datas alinhados. O CSV deve ser lido com `float_precision="round_trip"`, `index_col="indice_original"` e `parse_dates=["Data"]`. Verificação independente: `python -m unittest discover -s tests -v`, sem fit. O script de recuperação recusa arquivos existentes antes de iniciar qualquer treinamento.

**Ocorrências de persistência:** o manifesto foi finalizado sem repetir fit após corrigir a leitura do requirements.txt (UTF-16 com BOM) e a representação JSON do parâmetro missing_values=nan. O manifesto parcial foi inspecionado como JSON inválido antes da substituição. Pipeline, partições e previsões não foram sobrescritos. A serialização completa agora é validada antes de abrir o arquivo de manifesto.

As células e métricas anteriores foram preservadas. Nenhum diagnóstico aprofundado foi realizado. Esta etapa encerra a recuperação do Baseline V1.